// Code generated by codegen. DO NOT EDIT.

package commands

type AiMlopsPlatformCheckAiMlOpsPlatformVersionV1Cmd struct {
	ClusterId string `name:"cluster-id" help:"Cluster ID" required:""`
	Version   string `name:"version" help:"Version Get version by k8s.version value of imageAttr of Get List of AI&MLOps Platform Images" required:""`
}

func (c *AiMlopsPlatformCheckAiMlOpsPlatformVersionV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/clusters/{clusterId}/check-version",
		map[string]string{"clusterId": c.ClusterId},
		map[string]string{"version": c.Version},
		nil)
}

type AiMlopsPlatformCheckDuplicationAiMlOpsPlatformNameV1Cmd struct {
	ReleaseName string `name:"release-name" help:"AI&MLOps Platform name" required:""`
}

func (c *AiMlopsPlatformCheckDuplicationAiMlOpsPlatformNameV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/releases/check-duplication",
		map[string]string{},
		map[string]string{"releaseName": c.ReleaseName},
		nil)
}

type AiMlopsPlatformDeleteAiMlOpsPlatformV1Cmd struct {
	ReleaseId string `name:"release-id" help:"AI&MLOps Platform ID" required:""`
	WithK8s   string `name:"with-k8s" help:"Integrated deletion status"`
}

func (c *AiMlopsPlatformDeleteAiMlOpsPlatformV1Cmd) Run() error {
	return RunRequest("DELETE", "/ai-mlops-platform/v1/releases/{releaseId}",
		map[string]string{"releaseId": c.ReleaseId},
		map[string]string{"withK8s": c.WithK8s},
		nil)
}

type AiMlopsPlatformDeleteAiMlOpsPlatformV2Cmd struct {
	ReleaseId string `name:"release-id" help:"AI&MLOps Platform ID" required:""`
	WithK8s   string `name:"with-k8s" help:"Integrated deletion status"`
}

func (c *AiMlopsPlatformDeleteAiMlOpsPlatformV2Cmd) Run() error {
	return RunRequest("DELETE", "/ai-mlops-platform/v2/releases/{releaseId}",
		map[string]string{"releaseId": c.ReleaseId},
		map[string]string{"withK8s": c.WithK8s},
		nil)
}

type AiMlopsPlatformGetAiMlOpsPlatformImageListV1Cmd struct {
	ImageName string `name:"image-name" help:"Image name"`
	Page      string `name:"page" help:"Page (Default : 0)"`
	Size      string `name:"size" help:"The number of items per page (1~10000)"`
	Sort      string `name:"sort" help:"Field name and sort order (Ex. name:asc)"`
}

func (c *AiMlopsPlatformGetAiMlOpsPlatformImageListV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/images",
		map[string]string{},
		map[string]string{"imageName": c.ImageName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type AiMlopsPlatformGetAiMlOpsPlatformListV1Cmd struct {
	AiMlOpsPlatformType string `name:"ai-ml-ops-platform-type" help:"AI&MLOps Platform Type"`
	ClusterName         string `name:"cluster-name" help:"Cluster name"`
	ReleaseName         string `name:"release-name" help:"AI&MLOps Platform name"`
	Status              string `name:"status" help:"Status"`
	Version             string `name:"version" help:"Version"`
	CreatedBy           string `name:"created-by" help:"Creator"`
	Page                string `name:"page" help:"Page (Default : 0)"`
	Size                string `name:"size" help:"The number of items per page (1~10000)"`
	Sort                string `name:"sort" help:"Field name and sort order (Ex. name:asc)"`
}

func (c *AiMlopsPlatformGetAiMlOpsPlatformListV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/releases",
		map[string]string{},
		map[string]string{"aiMlOpsPlatformType": c.AiMlOpsPlatformType, "clusterName": c.ClusterName, "releaseName": c.ReleaseName, "status": c.Status, "version": c.Version, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type AiMlopsPlatformGetAiMlOpsPlatformV1Cmd struct {
	ReleaseId string `name:"release-id" help:"AI&MLOps Platform ID" required:""`
}

func (c *AiMlopsPlatformGetAiMlOpsPlatformV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/releases/{releaseId}",
		map[string]string{"releaseId": c.ReleaseId},
		map[string]string{},
		nil)
}

type AiMlopsPlatformReleaseAiMlOpsPlatformV1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AiMlopsPlatformReleaseAiMlOpsPlatformV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/ai-mlops-platform/v1/releases",
		map[string]string{},
		map[string]string{},
		b)
}

type AiMlopsPlatformReleaseAiMlOpsPlatformV2Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AiMlopsPlatformReleaseAiMlOpsPlatformV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/ai-mlops-platform/v2/releases",
		map[string]string{},
		map[string]string{},
		b)
}

type AiMlopsPlatformUpdateAiMlOpsPlatformV1Cmd struct {
	ReleaseId string `name:"release-id" help:"AI&MLOps Platform ID" required:""`
	Body      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AiMlopsPlatformUpdateAiMlOpsPlatformV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/ai-mlops-platform/v1/releases/{releaseId}",
		map[string]string{"releaseId": c.ReleaseId},
		map[string]string{},
		b)
}

type AiMlopsPlatformUpdateAiMlOpsPlatformV2Cmd struct {
	ReleaseId string `name:"release-id" help:"AI&MLOps Platform ID" required:""`
	Body      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AiMlopsPlatformUpdateAiMlOpsPlatformV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/ai-mlops-platform/v2/releases/{releaseId}",
		map[string]string{"releaseId": c.ReleaseId},
		map[string]string{},
		b)
}

type AiMlopsPlatformValidateClusterNamespaceForAiMlOpsPlatformV1Cmd struct {
	ClusterId string `name:"cluster-id" help:"Cluster ID" required:""`
}

func (c *AiMlopsPlatformValidateClusterNamespaceForAiMlOpsPlatformV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/clusters/{clusterId}/validate-namespaces",
		map[string]string{"clusterId": c.ClusterId},
		map[string]string{},
		nil)
}

type AiMlopsPlatformValidateClusterResourceSizeForAiMlOpsPlatformV1Cmd struct {
	ClusterId   string `name:"cluster-id" help:"Cluster ID" required:""`
	ProductType string `name:"product-type" help:"Product Type Allow only Enterprise / Mini" required:""`
}

func (c *AiMlopsPlatformValidateClusterResourceSizeForAiMlOpsPlatformV1Cmd) Run() error {
	return RunRequest("GET", "/ai-mlops-platform/v1/clusters/{clusterId}/validate-resources",
		map[string]string{"clusterId": c.ClusterId},
		map[string]string{"productType": c.ProductType},
		nil)
}

// AiMlopsPlatformCmd groups all ai-mlops-platform operations.
type AiMlopsPlatformCmd struct {
	CheckAiMlOpsPlatformVersionV1                   AiMlopsPlatformCheckAiMlOpsPlatformVersionV1Cmd                   `cmd:"" name:"check-ai-ml-ops-platform-version-v1" help:"Check AI&MLOps Platform Cluster Version"`
	CheckDuplicationAiMlOpsPlatformNameV1           AiMlopsPlatformCheckDuplicationAiMlOpsPlatformNameV1Cmd           `cmd:"" name:"check-duplication-ai-ml-ops-platform-name-v1" help:"Check Duplication AI&MLOps Platform Name"`
	DeleteAiMlOpsPlatformV1                         AiMlopsPlatformDeleteAiMlOpsPlatformV1Cmd                         `cmd:"" name:"delete-ai-ml-ops-platform-v1" help:"Delete AI&MLOps Platform"`
	DeleteAiMlOpsPlatformV2                         AiMlopsPlatformDeleteAiMlOpsPlatformV2Cmd                         `cmd:"" name:"delete-ai-ml-ops-platform-v2" help:"Delete AI&MLOps Platform"`
	GetAiMlOpsPlatformImageListV1                   AiMlopsPlatformGetAiMlOpsPlatformImageListV1Cmd                   `cmd:"" name:"get-ai-ml-ops-platform-image-list-v1" help:"Get List of AI&MLOps Platform Images"`
	GetAiMlOpsPlatformListV1                        AiMlopsPlatformGetAiMlOpsPlatformListV1Cmd                        `cmd:"" name:"get-ai-ml-ops-platform-list-v1" help:"Get List of AI&MLOps Platform"`
	GetAiMlOpsPlatformV1                            AiMlopsPlatformGetAiMlOpsPlatformV1Cmd                            `cmd:"" name:"get-ai-ml-ops-platform-v1" help:"Get AI&MLOps Platform details"`
	ReleaseAiMlOpsPlatformV1                        AiMlopsPlatformReleaseAiMlOpsPlatformV1Cmd                        `cmd:"" name:"release-ai-ml-ops-platform-v1" help:"Create AI&MLOps Platform"`
	ReleaseAiMlOpsPlatformV2                        AiMlopsPlatformReleaseAiMlOpsPlatformV2Cmd                        `cmd:"" name:"release-ai-ml-ops-platform-v2" help:"Create AI&MLOps Platform"`
	UpdateAiMlOpsPlatformV1                         AiMlopsPlatformUpdateAiMlOpsPlatformV1Cmd                         `cmd:"" name:"update-ai-ml-ops-platform-v1" help:"Update AI&MLOps Platform"`
	UpdateAiMlOpsPlatformV2                         AiMlopsPlatformUpdateAiMlOpsPlatformV2Cmd                         `cmd:"" name:"update-ai-ml-ops-platform-v2" help:"Update AI&MLOps Platform"`
	ValidateClusterNamespaceForAiMlOpsPlatformV1    AiMlopsPlatformValidateClusterNamespaceForAiMlOpsPlatformV1Cmd    `cmd:"" name:"validate-cluster-namespace-for-ai-ml-ops-platform-v1" help:"Validate Cluster Namespace for AI&MLOps Platform"`
	ValidateClusterResourceSizeForAiMlOpsPlatformV1 AiMlopsPlatformValidateClusterResourceSizeForAiMlOpsPlatformV1Cmd `cmd:"" name:"validate-cluster-resource-size-for-ai-ml-ops-platform-v1" help:"Validate Cluster Resource Size for AI&MLOps Platform"`
}
