// Code generated by codegen. DO NOT EDIT.

package commands

type AicrAsyncAnalyzeCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrAsyncAnalyzeCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/aicr/v1/aicrs/{aicrId}/async-analyze",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		b)
}

type AicrAsyncDetectTextCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrAsyncDetectTextCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/aicr/v1/aicrs/{aicrId}/async-detect-text",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		b)
}

type AicrCreateAicrCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrCreateAicrCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/aicr/v1/aicrs",
		map[string]string{},
		map[string]string{},
		b)
}

type AicrCreateAicrV2Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrCreateAicrV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/aicr/v2/aicrs",
		map[string]string{},
		map[string]string{},
		b)
}

type AicrDeleteAicrCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
}

func (c *AicrDeleteAicrCmd) Run() error {
	return RunRequest("DELETE", "/aicr/v1/aicrs/{aicrId}",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		nil)
}

type AicrDetailAicrCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
}

func (c *AicrDetailAicrCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs/{aicrId}",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		nil)
}

type AicrGetAicrAverageCmd struct {
	AicrId    string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	ApiName   string `name:"api-name" help:"API name" required:""`
	ApiType   string `name:"api-type" help:"API category" required:""`
	EndDate   string `name:"end-date" help:"End date (YYYY-MM-DD)" required:""`
	Offset    string `name:"offset" help:"오프셋 ex) +00:00, -01:00, +05:00" required:""`
	StartDate string `name:"start-date" help:"Start date (YYYY-MM-DD)" required:""`
	Term      string `name:"term" help:"Search term(day/week/month)" required:""`
}

func (c *AicrGetAicrAverageCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs/{aicrId}/avg",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{"apiName": c.ApiName, "apiType": c.ApiType, "endDate": c.EndDate, "offset": c.Offset, "startDate": c.StartDate, "term": c.Term},
		nil)
}

type AicrGetAicrAverageV2Cmd struct {
	ApiName    string `name:"api-name" help:"API name"`
	ApiType    string `name:"api-type" help:"API type"`
	EndDate    string `name:"end-date" help:"End date (YYYY-MM-DD)" required:""`
	Offset     string `name:"offset" help:"Offset ex) +00:00, -01:00, +05:00" required:""`
	PeriodUnit string `name:"period-unit" help:"Search term(day/week/month)" required:""`
	StartDate  string `name:"start-date" help:"Start date (YYYY-MM-DD)" required:""`
}

func (c *AicrGetAicrAverageV2Cmd) Run() error {
	return RunRequest("GET", "/aicr/v2/aicrs/average",
		map[string]string{},
		map[string]string{"apiName": c.ApiName, "apiType": c.ApiType, "endDate": c.EndDate, "offset": c.Offset, "periodUnit": c.PeriodUnit, "startDate": c.StartDate},
		nil)
}

type AicrGetAicrStatisticsCmd struct {
	AicrId    string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	ApiName   string `name:"api-name" help:"API name" required:""`
	ApiType   string `name:"api-type" help:"API category" required:""`
	EndDate   string `name:"end-date" help:"End date (YYYY-MM-DD)" required:""`
	Offset    string `name:"offset" help:"오프셋 ex) +00:00, -01:00, +05:00" required:""`
	StartDate string `name:"start-date" help:"Start date (YYYY-MM-DD)" required:""`
	Term      string `name:"term" help:"Search term(day/week/month)" required:""`
}

func (c *AicrGetAicrStatisticsCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs/{aicrId}/statistics",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{"apiName": c.ApiName, "apiType": c.ApiType, "endDate": c.EndDate, "offset": c.Offset, "startDate": c.StartDate, "term": c.Term},
		nil)
}

type AicrGetAicrStatisticsV2Cmd struct {
	ApiName    string `name:"api-name" help:"API name"`
	ApiType    string `name:"api-type" help:"API type"`
	EndDate    string `name:"end-date" help:"End date (YYYY-MM-DD)" required:""`
	Offset     string `name:"offset" help:"Offset ex) +00:00, -01:00, +05:00" required:""`
	PeriodUnit string `name:"period-unit" help:"Search term(day/week/month)" required:""`
	StartDate  string `name:"start-date" help:"Start date (YYYY-MM-DD)" required:""`
}

func (c *AicrGetAicrStatisticsV2Cmd) Run() error {
	return RunRequest("GET", "/aicr/v2/aicrs/statistics",
		map[string]string{},
		map[string]string{"apiName": c.ApiName, "apiType": c.ApiType, "endDate": c.EndDate, "offset": c.Offset, "periodUnit": c.PeriodUnit, "startDate": c.StartDate},
		nil)
}

type AicrGetAnalyzeResultCmd struct {
	AicrId    string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	AicrJobId string `name:"aicr-job-id" help:"Job ID to be used for getting results Job ID is obtained through Analyze the document (Async)" required:""`
}

func (c *AicrGetAnalyzeResultCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs/{aicrId}/analyze-results/{aicrJobId}",
		map[string]string{"aicrId": c.AicrId, "aicrJobId": c.AicrJobId},
		map[string]string{},
		nil)
}

type AicrGetCategoriesCmd struct {
}

func (c *AicrGetCategoriesCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs/categories",
		map[string]string{},
		map[string]string{},
		nil)
}

type AicrGetCategoriesV2Cmd struct {
}

func (c *AicrGetCategoriesV2Cmd) Run() error {
	return RunRequest("GET", "/aicr/v2/aicrs/categories",
		map[string]string{},
		map[string]string{},
		nil)
}

type AicrGetTextResultCmd struct {
	AicrId    string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	AicrJobId string `name:"aicr-job-id" help:"Job ID to be used for getting results Job ID is obtained through Detect AICR text (Async)" required:""`
}

func (c *AicrGetTextResultCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs/{aicrId}/detect-text-results/{aicrJobId}",
		map[string]string{"aicrId": c.AicrId, "aicrJobId": c.AicrJobId},
		map[string]string{},
		nil)
}

type AicrListAicrsCmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *AicrListAicrsCmd) Run() error {
	return RunRequest("GET", "/aicr/v1/aicrs",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type AicrSyncAnalyzeCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrSyncAnalyzeCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/aicr/v1/aicrs/{aicrId}/analyze",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		b)
}

type AicrSyncDetectTextCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrSyncDetectTextCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/aicr/v1/aicrs/{aicrId}/detect-text",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		b)
}

type AicrUpdateAicrDescriptionCmd struct {
	AicrId string `name:"aicr-id" help:"AICR ID AICR ID is obtained through Get list of AICR" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *AicrUpdateAicrDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/aicr/v1/aicrs/{aicrId}/description",
		map[string]string{"aicrId": c.AicrId},
		map[string]string{},
		b)
}

// AicrCmd groups all aicr operations.
type AicrCmd struct {
	AsyncAnalyze          AicrAsyncAnalyzeCmd          `cmd:"" name:"async-analyze" help:"Analyze the document (Async)"`
	AsyncDetectText       AicrAsyncDetectTextCmd       `cmd:"" name:"async-detect-text" help:"Detect AICR text (Async)"`
	CreateAicr            AicrCreateAicrCmd            `cmd:"" name:"create-aicr" help:"Create AICR"`
	CreateAicrV2          AicrCreateAicrV2Cmd          `cmd:"" name:"create-aicr-v2" help:"Create AICR"`
	DeleteAicr            AicrDeleteAicrCmd            `cmd:"" name:"delete-aicr" help:"Delete AICR"`
	DetailAicr            AicrDetailAicrCmd            `cmd:"" name:"detail-aicr" help:"Get AICR details"`
	GetAicrAverage        AicrGetAicrAverageCmd        `cmd:"" name:"get-aicr-average" help:"Get average data for the period"`
	GetAicrAverageV2      AicrGetAicrAverageV2Cmd      `cmd:"" name:"get-aicr-average-v2" help:"Get average data for the period"`
	GetAicrStatistics     AicrGetAicrStatisticsCmd     `cmd:"" name:"get-aicr-statistics" help:"Get statistics for each request"`
	GetAicrStatisticsV2   AicrGetAicrStatisticsV2Cmd   `cmd:"" name:"get-aicr-statistics-v2" help:"Get statistics for each request"`
	GetAnalyzeResult      AicrGetAnalyzeResultCmd      `cmd:"" name:"get-analyze-result" help:"Get analyzed text"`
	GetCategories         AicrGetCategoriesCmd         `cmd:"" name:"get-categories" help:"Get category data"`
	GetCategoriesV2       AicrGetCategoriesV2Cmd       `cmd:"" name:"get-categories-v2" help:"Get category data"`
	GetTextResult         AicrGetTextResultCmd         `cmd:"" name:"get-text-result" help:"Get detected text"`
	ListAicrs             AicrListAicrsCmd             `cmd:"" name:"list-aicrs" help:"Get list of AICR"`
	SyncAnalyze           AicrSyncAnalyzeCmd           `cmd:"" name:"sync-analyze" help:"Analyze the document (Sync)"`
	SyncDetectText        AicrSyncDetectTextCmd        `cmd:"" name:"sync-detect-text" help:"Detect AICR text (Sync)"`
	UpdateAicrDescription AicrUpdateAicrDescriptionCmd `cmd:"" name:"update-aicr-description" help:"Update AICR description"`
}
