// Code generated by codegen. DO NOT EDIT.

package commands

type ApacheKafkaAttachKafkaClusterSecurityGroupCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaAttachKafkaClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/security-groups/attach",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

type ApacheKafkaCreateKafkaClusterCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaCreateKafkaClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka",
		map[string]string{},
		map[string]string{},
		b)
}

type ApacheKafkaDeleteKafkaClusterCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
}

func (c *ApacheKafkaDeleteKafkaClusterCmd) Run() error {
	return RunRequest("DELETE", "/analytics/kafka/v1/kafka/{kafkaClusterId}",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		nil)
}

type ApacheKafkaDetachKafkaClusterSecurityGroupCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaDetachKafkaClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/security-groups/detach",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

type ApacheKafkaDetailKafkaClusterCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
}

func (c *ApacheKafkaDetailKafkaClusterCmd) Run() error {
	return RunRequest("GET", "/analytics/kafka/v1/kafka/{kafkaClusterId}",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		nil)
}

type ApacheKafkaListKafkaClustersCmd struct {
	KafkaClusterName string `name:"kafka-cluster-name" help:"Kafka cluster name"`
	Page             string `name:"page" help:"Request page number"`
	Size             string `name:"size" help:"Number of items in the Page"`
	Sort             string `name:"sort" help:"Sort condition"`
}

func (c *ApacheKafkaListKafkaClustersCmd) Run() error {
	return RunRequest("GET", "/analytics/kafka/v1/kafka",
		map[string]string{},
		map[string]string{"kafkaClusterName": c.KafkaClusterName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApacheKafkaResizeKafkaClusterBlockStoragesCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaResizeKafkaClusterBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/block-storages/resize",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

type ApacheKafkaResizeKafkaClusterVirtualServersCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaResizeKafkaClusterVirtualServersCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/virtual-servers/resize",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

type ApacheKafkaRestartKafkaClusterCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaRestartKafkaClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/restart",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

type ApacheKafkaStartKafkaClusterCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaStartKafkaClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/start",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

type ApacheKafkaStopKafkaClusterCmd struct {
	KafkaClusterId string `name:"kafka-cluster-id" help:"Kafka cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApacheKafkaStopKafkaClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/kafka/v1/kafka/{kafkaClusterId}/stop",
		map[string]string{"kafkaClusterId": c.KafkaClusterId},
		map[string]string{},
		b)
}

// ApacheKafkaCmd groups all apache-kafka operations.
type ApacheKafkaCmd struct {
	AttachKafkaClusterSecurityGroup  ApacheKafkaAttachKafkaClusterSecurityGroupCmd  `cmd:"" name:"attach-kafka-cluster-security-group" help:"Attach Security Group to Kafka cluster"`
	CreateKafkaCluster               ApacheKafkaCreateKafkaClusterCmd               `cmd:"" name:"create-kafka-cluster" help:"Create Kafka cluster"`
	DeleteKafkaCluster               ApacheKafkaDeleteKafkaClusterCmd               `cmd:"" name:"delete-kafka-cluster" help:"Delete Kafka cluster"`
	DetachKafkaClusterSecurityGroup  ApacheKafkaDetachKafkaClusterSecurityGroupCmd  `cmd:"" name:"detach-kafka-cluster-security-group" help:"Detach Security Group to Kafka cluster"`
	DetailKafkaCluster               ApacheKafkaDetailKafkaClusterCmd               `cmd:"" name:"detail-kafka-cluster" help:"Detail Kafka cluster"`
	ListKafkaClusters                ApacheKafkaListKafkaClustersCmd                `cmd:"" name:"list-kafka-clusters" help:"List Kafka cluster"`
	ResizeKafkaClusterBlockStorages  ApacheKafkaResizeKafkaClusterBlockStoragesCmd  `cmd:"" name:"resize-kafka-cluster-block-storages" help:"Resize Kafka cluster block storages"`
	ResizeKafkaClusterVirtualServers ApacheKafkaResizeKafkaClusterVirtualServersCmd `cmd:"" name:"resize-kafka-cluster-virtual-servers" help:"Resize Kafka cluster virtual servers"`
	RestartKafkaCluster              ApacheKafkaRestartKafkaClusterCmd              `cmd:"" name:"restart-kafka-cluster" help:"Restart Kafka cluster"`
	StartKafkaCluster                ApacheKafkaStartKafkaClusterCmd                `cmd:"" name:"start-kafka-cluster" help:"Start Kafka cluster"`
	StopKafkaCluster                 ApacheKafkaStopKafkaClusterCmd                 `cmd:"" name:"stop-kafka-cluster" help:"Stop Kafka cluster"`
}
