// Code generated by codegen. DO NOT EDIT.

package commands

type ApiGatewayCheckApiCollectionNameDuplicationCmd struct {
	ApiCollectionName string `name:"api-collection-name" help:"API Collection name" required:""`
	ApiGatewayId      string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
}

func (c *ApiGatewayCheckApiCollectionNameDuplicationCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-collections/check-duplication",
		map[string]string{},
		map[string]string{"apiCollectionName": c.ApiCollectionName, "apiGatewayId": c.ApiGatewayId},
		nil)
}

type ApiGatewayCheckApiCollectionWhitelistDuplicationCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	EndIpAddress    string `name:"end-ip-address" help:"end IP address" required:""`
	StartIpAddress  string `name:"start-ip-address" help:"start IP address" required:""`
}

func (c *ApiGatewayCheckApiCollectionWhitelistDuplicationCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-collections/{apiCollectionId}/whitelist/check-duplication",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{"endIpAddress": c.EndIpAddress, "startIpAddress": c.StartIpAddress},
		nil)
}

type ApiGatewayCheckApiContextDuplicationCmd struct {
	ApiGatewayId string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
	Context      string `name:"context" help:"context" required:""`
}

func (c *ApiGatewayCheckApiContextDuplicationCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis/check-context-duplication",
		map[string]string{},
		map[string]string{"apiGatewayId": c.ApiGatewayId, "context": c.Context},
		nil)
}

type ApiGatewayCheckApiGatewayNameDuplicationCmd struct {
	ApiGatewayName string `name:"api-gateway-name" help:"apiGatewayName" required:""`
}

func (c *ApiGatewayCheckApiGatewayNameDuplicationCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/check-duplication",
		map[string]string{},
		map[string]string{"apiGatewayName": c.ApiGatewayName},
		nil)
}

type ApiGatewayCheckApiNameDuplicationCmd struct {
	ApiGatewayId string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
	ApiName      string `name:"api-name" help:"API Name" required:""`
}

func (c *ApiGatewayCheckApiNameDuplicationCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis/check-apiName-duplication",
		map[string]string{},
		map[string]string{"apiGatewayId": c.ApiGatewayId, "apiName": c.ApiName},
		nil)
}

type ApiGatewayCheckUsagePlanNameDuplicationCmd struct {
	ApiGatewayId  string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
	UsagePlanName string `name:"usage-plan-name" help:"Usage Plan Name" required:""`
}

func (c *ApiGatewayCheckUsagePlanNameDuplicationCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/usage-plans/check-duplication",
		map[string]string{},
		map[string]string{"apiGatewayId": c.ApiGatewayId, "usagePlanName": c.UsagePlanName},
		nil)
}

type ApiGatewayCreateApiCollectionCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateApiCollectionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v1/api-collections",
		map[string]string{},
		map[string]string{},
		b)
}

type ApiGatewayCreateApiCollectionConnectionListCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateApiCollectionConnectionListCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v1/api-collections/{apiCollectionId}/connection",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayCreateApiCollectionWhitelistCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateApiCollectionWhitelistCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v1/api-collections/{apiCollectionId}/whitelist",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayCreateApiGatewayCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateApiGatewayCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v1/api-gateways",
		map[string]string{},
		map[string]string{},
		b)
}

type ApiGatewayCreateApiNewVersionCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateApiNewVersionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v1/apis/{apiId}/version",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayCreateApi2Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateApi2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v3/apis",
		map[string]string{},
		map[string]string{},
		b)
}

type ApiGatewayCreateUsagePlanCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayCreateUsagePlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/api-gateway/v1/usage-plans",
		map[string]string{},
		map[string]string{},
		b)
}

type ApiGatewayDeleteApiCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
}

func (c *ApiGatewayDeleteApiCmd) Run() error {
	return RunRequest("DELETE", "/api-gateway/v1/apis/{apiId}",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		nil)
}

type ApiGatewayDeleteApiCollectionCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
}

func (c *ApiGatewayDeleteApiCollectionCmd) Run() error {
	return RunRequest("DELETE", "/api-gateway/v1/api-collections/{apiCollectionId}",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		nil)
}

type ApiGatewayDeleteApiCollectionConnectionCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayDeleteApiCollectionConnectionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/api-gateway/v1/api-collections/{apiCollectionId}/connection",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayDeleteApiCollectionWhitelistCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayDeleteApiCollectionWhitelistCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/api-gateway/v1/api-collections/{apiCollectionId}/whitelist",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayDeleteApiGatewayCmd struct {
	ApiGatewayId string `name:"api-gateway-id" help:"apiGatewayId API Gateway ID is obtained through ListApiGateway" required:""`
}

func (c *ApiGatewayDeleteApiGatewayCmd) Run() error {
	return RunRequest("DELETE", "/api-gateway/v1/api-gateways/{apiGatewayId}",
		map[string]string{"apiGatewayId": c.ApiGatewayId},
		map[string]string{},
		nil)
}

type ApiGatewayDeleteUsagePlanCmd struct {
	UsagePlanId string `name:"usage-plan-id" help:"Usage Plan ID Usage Plan ID is obtained through List Usage Plan" required:""`
}

func (c *ApiGatewayDeleteUsagePlanCmd) Run() error {
	return RunRequest("DELETE", "/api-gateway/v1/usage-plans/{usagePlanId}",
		map[string]string{"usagePlanId": c.UsagePlanId},
		map[string]string{},
		nil)
}

type ApiGatewayDetailApiCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
}

func (c *ApiGatewayDetailApiCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis/{apiId}",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		nil)
}

type ApiGatewayDetailApiCollectionCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
}

func (c *ApiGatewayDetailApiCollectionCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-collections/{apiCollectionId}",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		nil)
}

type ApiGatewayDetailApiGatewayCmd struct {
	ApiGatewayId string `name:"api-gateway-id" help:"apiGatewayId API Gateway ID is obtained through ListApiGateway" required:""`
}

func (c *ApiGatewayDetailApiGatewayCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/{apiGatewayId}",
		map[string]string{"apiGatewayId": c.ApiGatewayId},
		map[string]string{},
		nil)
}

type ApiGatewayDetailUsagePlanCmd struct {
	UsagePlanId string `name:"usage-plan-id" help:"Usage Plan ID Usage Plan ID is obtained through List Usage Plan" required:""`
}

func (c *ApiGatewayDetailUsagePlanCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/usage-plans/{usagePlanId}",
		map[string]string{"usagePlanId": c.UsagePlanId},
		map[string]string{},
		nil)
}

type ApiGatewayGetApiGatewayEngineUrlCmd struct {
}

func (c *ApiGatewayGetApiGatewayEngineUrlCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/engine-url",
		map[string]string{},
		map[string]string{},
		nil)
}

type ApiGatewayGetApiSwaggerCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
}

func (c *ApiGatewayGetApiSwaggerCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis/{apiId}/swagger",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		nil)
}

type ApiGatewayGetAverageCmd struct {
	ApiGatewayId    string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
	ApiCollectionId string `name:"api-collection-id" help:"apiCollectionId API Collection ID is obtained through Get List of API Collections"`
	ApiName         string `name:"api-name" help:"apiName"`
	EndDate         string `name:"end-date" help:"endDate" required:""`
	StartDate       string `name:"start-date" help:"startDate" required:""`
	Term            string `name:"term" help:"term" required:""`
	Version         string `name:"version" help:"apiVersion"`
}

func (c *ApiGatewayGetAverageCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/{apiGatewayId}/average",
		map[string]string{"apiGatewayId": c.ApiGatewayId},
		map[string]string{"apiCollectionId": c.ApiCollectionId, "apiName": c.ApiName, "endDate": c.EndDate, "startDate": c.StartDate, "term": c.Term, "version": c.Version},
		nil)
}

type ApiGatewayGetAverageAboutAllCmd struct {
	EndDate   string `name:"end-date" help:"endDate" required:""`
	StartDate string `name:"start-date" help:"startDate" required:""`
	Term      string `name:"term" help:"term" required:""`
}

func (c *ApiGatewayGetAverageAboutAllCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/average",
		map[string]string{},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "term": c.Term},
		nil)
}

type ApiGatewayGetConnectableApiGatewayApiListCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayGetConnectableApiGatewayApiListCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis/connectable-apis",
		map[string]string{},
		map[string]string{"apiCollectionId": c.ApiCollectionId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayGetConnectedApiGatewayApiListCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayGetConnectedApiGatewayApiListCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis/connected-apis",
		map[string]string{},
		map[string]string{"apiCollectionId": c.ApiCollectionId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayGetStatisticsCmd struct {
	ApiGatewayId    string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
	ApiCollectionId string `name:"api-collection-id" help:"apiCollectionId API Collection ID is obtained through Get List of API Collections"`
	ApiName         string `name:"api-name" help:"apiName"`
	EndDate         string `name:"end-date" help:"endDate" required:""`
	StartDate       string `name:"start-date" help:"startDate" required:""`
	Term            string `name:"term" help:"term" required:""`
	Version         string `name:"version" help:"apiVersion"`
}

func (c *ApiGatewayGetStatisticsCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/{apiGatewayId}/statistics",
		map[string]string{"apiGatewayId": c.ApiGatewayId},
		map[string]string{"apiCollectionId": c.ApiCollectionId, "apiName": c.ApiName, "endDate": c.EndDate, "startDate": c.StartDate, "term": c.Term, "version": c.Version},
		nil)
}

type ApiGatewayGetStatisticsAboutAllCmd struct {
	EndDate   string `name:"end-date" help:"endDate" required:""`
	StartDate string `name:"start-date" help:"startDate" required:""`
	Term      string `name:"term" help:"term" required:""`
}

func (c *ApiGatewayGetStatisticsAboutAllCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/statistics",
		map[string]string{},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "term": c.Term},
		nil)
}

type ApiGatewayGetTopResourcesCmd struct {
	ApiGatewayId    string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway" required:""`
	ApiCollectionId string `name:"api-collection-id" help:"apiCollectionId API Collection ID is obtained through Get List of API Collections"`
	ApiName         string `name:"api-name" help:"apiName"`
	EndDate         string `name:"end-date" help:"endDate" required:""`
	StartDate       string `name:"start-date" help:"startDate" required:""`
	Term            string `name:"term" help:"term" required:""`
	Version         string `name:"version" help:"apiVersion"`
}

func (c *ApiGatewayGetTopResourcesCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/{apiGatewayId}/top-resources",
		map[string]string{"apiGatewayId": c.ApiGatewayId},
		map[string]string{"apiCollectionId": c.ApiCollectionId, "apiName": c.ApiName, "endDate": c.EndDate, "startDate": c.StartDate, "term": c.Term, "version": c.Version},
		nil)
}

type ApiGatewayGetTopResourcesAboutAllCmd struct {
	EndDate   string `name:"end-date" help:"endDate" required:""`
	StartDate string `name:"start-date" help:"startDate" required:""`
	Term      string `name:"term" help:"term" required:""`
}

func (c *ApiGatewayGetTopResourcesAboutAllCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways/top-resources",
		map[string]string{},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "term": c.Term},
		nil)
}

type ApiGatewayListApiCmd struct {
	ApiGatewayId   string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway"`
	ApiGatewayName string `name:"api-gateway-name" help:"API Gateway Name"`
	ApiId          string `name:"api-id" help:"API ID API ID is obtained through ListApi"`
	ApiName        string `name:"api-name" help:"API Name"`
	ApiStates      string `name:"api-states" help:"API States"`
	Context        string `name:"context" help:"context"`
	CreatedBy      string `name:"created-by" help:"API Creator ID"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayListApiCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/apis",
		map[string]string{},
		map[string]string{"apiGatewayId": c.ApiGatewayId, "apiGatewayName": c.ApiGatewayName, "apiId": c.ApiId, "apiName": c.ApiName, "apiStates": c.ApiStates, "context": c.Context, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayListApiCollectionCmd struct {
	ApiCollectionName string `name:"api-collection-name" help:"API Collection name"`
	ApiGatewayId      string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway"`
	ApiGatewayName    string `name:"api-gateway-name" help:"API Gateway name"`
	CreatedBy         string `name:"created-by" help:"Created By"`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayListApiCollectionCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-collections",
		map[string]string{},
		map[string]string{"apiCollectionName": c.ApiCollectionName, "apiGatewayId": c.ApiGatewayId, "apiGatewayName": c.ApiGatewayName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayListApiCollectionWhitelistCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayListApiCollectionWhitelistCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-collections/{apiCollectionId}/whitelist",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayListApiGatewayCmd struct {
	ApiGatewayName string `name:"api-gateway-name" help:"apiGatewayName"`
	CreatedBy      string `name:"created-by" help:"createdBy"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayListApiGatewayCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-gateways",
		map[string]string{},
		map[string]string{"apiGatewayName": c.ApiGatewayName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayListConnectedApiCollectionsCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Page  string `name:"page" help:"Request page number"`
	Size  string `name:"size" help:"Number of items in the Page"`
	Sort  string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayListConnectedApiCollectionsCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/api-collections/connected-api-collections",
		map[string]string{},
		map[string]string{"apiId": c.ApiId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayListUsagePlanCmd struct {
	ApiGatewayId   string `name:"api-gateway-id" help:"API Gateway ID API Gateway ID is obtained through ListApiGateway"`
	ApiGatewayName string `name:"api-gateway-name" help:"API Gateway Name"`
	UsagePlanName  string `name:"usage-plan-name" help:"Usage Plan Name"`
	CreatedBy      string `name:"created-by" help:"Created By"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *ApiGatewayListUsagePlanCmd) Run() error {
	return RunRequest("GET", "/api-gateway/v1/usage-plans",
		map[string]string{},
		map[string]string{"apiGatewayId": c.ApiGatewayId, "apiGatewayName": c.ApiGatewayName, "usagePlanName": c.UsagePlanName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ApiGatewayPublishApiCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayPublishApiCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/publish",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiCacheTtlCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiCacheTtlCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/cache-ttl",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiCollectionDescriptionCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiCollectionDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/api-collections/{apiCollectionId}/description",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiCollectionKeyCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiCollectionKeyCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/api-collections/{apiCollectionId}/key",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiCollectionUsagePlanCmd struct {
	ApiCollectionId string `name:"api-collection-id" help:"API Collection ID API Collection ID is obtained through Get List of API Collections" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiCollectionUsagePlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/api-collections/{apiCollectionId}/usage-plan",
		map[string]string{"apiCollectionId": c.ApiCollectionId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiCorsConfiguration1Cmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiCorsConfiguration1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v2/apis/{apiId}/corsConfiguration",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiDescriptionCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/description",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiEndpointSecurityCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiEndpointSecurityCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/endpointSecurity",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiGatewayDescriptionCmd struct {
	ApiGatewayId string `name:"api-gateway-id" help:"apiGatewayId API Gateway ID is obtained through ListApiGateway" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiGatewayDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/api-gateways/{apiGatewayId}/description",
		map[string]string{"apiGatewayId": c.ApiGatewayId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiProtocolTypeCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiProtocolTypeCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/protocolType",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateApiResourcesCmd struct {
	ApiId string `name:"api-id" help:"API ID API ID is obtained through ListApi" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateApiResourcesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/resource",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateUsagePlanDescriptionCmd struct {
	UsagePlanId string `name:"usage-plan-id" help:"Usage Plan ID Usage Plan ID is obtained through List Usage Plan" required:""`
	Body        string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateUsagePlanDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/usage-plans/{usagePlanId}/description",
		map[string]string{"usagePlanId": c.UsagePlanId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateUsagePlanLimitCmd struct {
	UsagePlanId string `name:"usage-plan-id" help:"Usage Plan ID Usage Plan ID is obtained through List Usage Plan" required:""`
	Body        string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateUsagePlanLimitCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/usage-plans/{usagePlanId}/limit",
		map[string]string{"usagePlanId": c.UsagePlanId},
		map[string]string{},
		b)
}

type ApiGatewayUpdateEndpointCmd struct {
	ApiId string `name:"api-id" help:"API ID" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ApiGatewayUpdateEndpointCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/api-gateway/v1/apis/{apiId}/endpoint",
		map[string]string{"apiId": c.ApiId},
		map[string]string{},
		b)
}

// ApiGatewayCmd groups all api-gateway operations.
type ApiGatewayCmd struct {
	CheckApiCollectionNameDuplication      ApiGatewayCheckApiCollectionNameDuplicationCmd      `cmd:"" name:"check-api-collection-name-duplication" help:"Check API Collection name duplication"`
	CheckApiCollectionWhitelistDuplication ApiGatewayCheckApiCollectionWhitelistDuplicationCmd `cmd:"" name:"check-api-collection-whitelist-duplication" help:"Check API Collection Whitelist Duplication"`
	CheckApiContextDuplication             ApiGatewayCheckApiContextDuplicationCmd             `cmd:"" name:"check-api-context-duplication" help:"CheckAPIContextDuplication"`
	CheckApiGatewayNameDuplication         ApiGatewayCheckApiGatewayNameDuplicationCmd         `cmd:"" name:"check-api-gateway-name-duplication" help:"CheckApiGatewayNameDuplication"`
	CheckApiNameDuplication                ApiGatewayCheckApiNameDuplicationCmd                `cmd:"" name:"check-api-name-duplication" help:"CheckAPINameDuplication"`
	CheckUsagePlanNameDuplication          ApiGatewayCheckUsagePlanNameDuplicationCmd          `cmd:"" name:"check-usage-plan-name-duplication" help:"Check Usage Plan Name Duplication"`
	CreateApiCollection                    ApiGatewayCreateApiCollectionCmd                    `cmd:"" name:"create-api-collection" help:"Create API Collection"`
	CreateApiCollectionConnectionList      ApiGatewayCreateApiCollectionConnectionListCmd      `cmd:"" name:"create-api-collection-connection-list" help:"Create connection between API Collection and APIs"`
	CreateApiCollectionWhitelist           ApiGatewayCreateApiCollectionWhitelistCmd           `cmd:"" name:"create-api-collection-whitelist" help:"Create API Collection Whitelist"`
	CreateApiGateway                       ApiGatewayCreateApiGatewayCmd                       `cmd:"" name:"create-api-gateway" help:"CreateApiGateway"`
	CreateApiNewVersion                    ApiGatewayCreateApiNewVersionCmd                    `cmd:"" name:"create-api-new-version" help:"CreateApiNewVersion"`
	CreateApi2                             ApiGatewayCreateApi2Cmd                             `cmd:"" name:"create-api_2" help:"CreateApi"`
	CreateUsagePlan                        ApiGatewayCreateUsagePlanCmd                        `cmd:"" name:"create-usage-plan" help:"Create Usage Plan"`
	DeleteApi                              ApiGatewayDeleteApiCmd                              `cmd:"" name:"delete-api" help:"DeleteApi"`
	DeleteApiCollection                    ApiGatewayDeleteApiCollectionCmd                    `cmd:"" name:"delete-api-collection" help:"Delete API Collection"`
	DeleteApiCollectionConnection          ApiGatewayDeleteApiCollectionConnectionCmd          `cmd:"" name:"delete-api-collection-connection" help:"Delete connection between API Collection and API"`
	DeleteApiCollectionWhitelist           ApiGatewayDeleteApiCollectionWhitelistCmd           `cmd:"" name:"delete-api-collection-whitelist" help:"Delete API Collection Whitelist"`
	DeleteApiGateway                       ApiGatewayDeleteApiGatewayCmd                       `cmd:"" name:"delete-api-gateway" help:"DeleteApiGateway"`
	DeleteUsagePlan                        ApiGatewayDeleteUsagePlanCmd                        `cmd:"" name:"delete-usage-plan" help:"Delete Usage Plan"`
	DetailApi                              ApiGatewayDetailApiCmd                              `cmd:"" name:"detail-api" help:"DetailApi"`
	DetailApiCollection                    ApiGatewayDetailApiCollectionCmd                    `cmd:"" name:"detail-api-collection" help:"Get API Collection details"`
	DetailApiGateway                       ApiGatewayDetailApiGatewayCmd                       `cmd:"" name:"detail-api-gateway" help:"DetailApiGateway"`
	DetailUsagePlan                        ApiGatewayDetailUsagePlanCmd                        `cmd:"" name:"detail-usage-plan" help:"Detail Usage Plan"`
	GetApiGatewayEngineUrl                 ApiGatewayGetApiGatewayEngineUrlCmd                 `cmd:"" name:"get-api-gateway-engine-url" help:"GetApiGatewayEngineUrl"`
	GetApiSwagger                          ApiGatewayGetApiSwaggerCmd                          `cmd:"" name:"get-api-swagger" help:"GetApiSwagger"`
	GetAverage                             ApiGatewayGetAverageCmd                             `cmd:"" name:"get-average" help:"Get Average"`
	GetAverageAboutAll                     ApiGatewayGetAverageAboutAllCmd                     `cmd:"" name:"get-average-about-all" help:"Get Average of entire API Gateway in the project"`
	GetConnectableApiGatewayApiList        ApiGatewayGetConnectableApiGatewayApiListCmd        `cmd:"" name:"get-connectable-api-gateway-api-list" help:"GetConnectableApiGatewayApiList"`
	GetConnectedApiGatewayApiList          ApiGatewayGetConnectedApiGatewayApiListCmd          `cmd:"" name:"get-connected-api-gateway-api-list" help:"GetConnectedApiGatewayApiList"`
	GetStatistics                          ApiGatewayGetStatisticsCmd                          `cmd:"" name:"get-statistics" help:"Get Statistics"`
	GetStatisticsAboutAll                  ApiGatewayGetStatisticsAboutAllCmd                  `cmd:"" name:"get-statistics-about-all" help:"Get Statistics of entire API Gateway in the project"`
	GetTopResources                        ApiGatewayGetTopResourcesCmd                        `cmd:"" name:"get-top-resources" help:"Get Top Resources"`
	GetTopResourcesAboutAll                ApiGatewayGetTopResourcesAboutAllCmd                `cmd:"" name:"get-top-resources-about-all" help:"Get Top Resources of entire API Gateway in the project"`
	ListApi                                ApiGatewayListApiCmd                                `cmd:"" name:"list-api" help:"ListApi"`
	ListApiCollection                      ApiGatewayListApiCollectionCmd                      `cmd:"" name:"list-api-collection" help:"Get List of API Collections"`
	ListApiCollectionWhitelist             ApiGatewayListApiCollectionWhitelistCmd             `cmd:"" name:"list-api-collection-whitelist" help:"Get List of API Collection Whitelist"`
	ListApiGateway                         ApiGatewayListApiGatewayCmd                         `cmd:"" name:"list-api-gateway" help:"ListApiGateway"`
	ListConnectedApiCollections            ApiGatewayListConnectedApiCollectionsCmd            `cmd:"" name:"list-connected-api-collections" help:"Get List of API Collections connected to api"`
	ListUsagePlan                          ApiGatewayListUsagePlanCmd                          `cmd:"" name:"list-usage-plan" help:"List Usage Plan"`
	PublishApi                             ApiGatewayPublishApiCmd                             `cmd:"" name:"publish-api" help:"PublishApi"`
	UpdateApiCacheTtl                      ApiGatewayUpdateApiCacheTtlCmd                      `cmd:"" name:"update-api-cache-ttl" help:"UpdateCacheTtl"`
	UpdateApiCollectionDescription         ApiGatewayUpdateApiCollectionDescriptionCmd         `cmd:"" name:"update-api-collection-description" help:"Update description of API Collection"`
	UpdateApiCollectionKey                 ApiGatewayUpdateApiCollectionKeyCmd                 `cmd:"" name:"update-api-collection-key" help:"Update keys of API Collection"`
	UpdateApiCollectionUsagePlan           ApiGatewayUpdateApiCollectionUsagePlanCmd           `cmd:"" name:"update-api-collection-usage-plan" help:"Update usage plan of API Collection"`
	UpdateApiCorsConfiguration1            ApiGatewayUpdateApiCorsConfiguration1Cmd            `cmd:"" name:"update-api-cors-configuration_1" help:"UpdateApiCorsConfiguration"`
	UpdateApiDescription                   ApiGatewayUpdateApiDescriptionCmd                   `cmd:"" name:"update-api-description" help:"UpdateApiDescription"`
	UpdateApiEndpointSecurity              ApiGatewayUpdateApiEndpointSecurityCmd              `cmd:"" name:"update-api-endpoint-security" help:"UpdateApiEndpointSecurity"`
	UpdateApiGatewayDescription            ApiGatewayUpdateApiGatewayDescriptionCmd            `cmd:"" name:"update-api-gateway-description" help:"UpdateApiGatewayDescription"`
	UpdateApiProtocolType                  ApiGatewayUpdateApiProtocolTypeCmd                  `cmd:"" name:"update-api-protocol-type" help:"UpdateApiProtocolType"`
	UpdateApiResources                     ApiGatewayUpdateApiResourcesCmd                     `cmd:"" name:"update-api-resources" help:"UpdateApiResources"`
	UpdateUsagePlanDescription             ApiGatewayUpdateUsagePlanDescriptionCmd             `cmd:"" name:"update-usage-plan-description" help:"Update Usage Plan Description"`
	UpdateUsagePlanLimit                   ApiGatewayUpdateUsagePlanLimitCmd                   `cmd:"" name:"update-usage-plan-limit" help:"Update Usage Plan Limit Count or Time"`
	UpdateEndpoint                         ApiGatewayUpdateEndpointCmd                         `cmd:"" name:"update-endpoint" help:"UpdateApiEndpoint"`
}
