// Code generated by codegen. DO NOT EDIT.

package commands

type ArchiveStorageCreateArchiveStorageCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ArchiveStorageCreateArchiveStorageCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/archive-storage/v1/buckets",
		map[string]string{},
		map[string]string{},
		b)
}

type ArchiveStorageDeleteArchiveStorageCmd struct {
	BucketId string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
}

func (c *ArchiveStorageDeleteArchiveStorageCmd) Run() error {
	return RunRequest("DELETE", "/archive-storage/v1/buckets/{bucketId}",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{},
		nil)
}

type ArchiveStorageDeleteArchiveStorageObjectsCmd struct {
	BucketId string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ArchiveStorageDeleteArchiveStorageObjectsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/archive-storage/v1/buckets/{bucketId}/objects",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{},
		b)
}

type ArchiveStorageDeleteArchivingJobCmd struct {
	ArchivingId string `name:"archiving-id" help:"Archiving ID" required:""`
	BucketId    string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	ExecutionId string `name:"execution-id" help:"Archiving Execution ID" required:""`
}

func (c *ArchiveStorageDeleteArchivingJobCmd) Run() error {
	return RunRequest("DELETE", "/archive-storage/v1/buckets/{bucketId}/archiving/{archivingId}/archiving-job/{executionId}",
		map[string]string{"archivingId": c.ArchivingId, "bucketId": c.BucketId, "executionId": c.ExecutionId},
		map[string]string{},
		nil)
}

type ArchiveStorageDetailArchiveStorageBucketCmd struct {
	BucketId string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
}

func (c *ArchiveStorageDetailArchiveStorageBucketCmd) Run() error {
	return RunRequest("GET", "/archive-storage/v1/buckets/{bucketId}",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{},
		nil)
}

type ArchiveStorageDetailArchivingJobCmd struct {
	BucketId      string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	ExecutionId   string `name:"execution-id" help:"Archiving Execution ID" required:""`
	ArchivingType string `name:"archiving-type" help:"Archiving Type" required:""`
	TimeZoneName  string `name:"time-zone-name" help:"Time Zone Name"`
}

func (c *ArchiveStorageDetailArchivingJobCmd) Run() error {
	return RunRequest("GET", "/archive-storage/v1/buckets/{bucketId}/archiving-job/{executionId}",
		map[string]string{"bucketId": c.BucketId, "executionId": c.ExecutionId},
		map[string]string{"archivingType": c.ArchivingType, "timeZoneName": c.TimeZoneName},
		nil)
}

type ArchiveStorageListArchiveStorageBucketObjectsCmd struct {
	BucketId                       string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	ArchiveStorageBucketObjectPath string `name:"archive-storage-bucket-object-path" help:"Archive Storage Bucket Object Path"`
	ArchiveStorageObjectSearchName string `name:"archive-storage-object-search-name" help:"Archive Storage Object Search Name"`
	ArchiveStorageObjectType       string `name:"archive-storage-object-type" help:"Archive Storage Object Type"`
	Marker                         string `name:"marker" help:"Marker"`
	Size                           string `name:"size" help:"Number of items in the Page"`
}

func (c *ArchiveStorageListArchiveStorageBucketObjectsCmd) Run() error {
	return RunRequest("GET", "/archive-storage/v1/buckets/{bucketId}/objects",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{"archiveStorageBucketObjectPath": c.ArchiveStorageBucketObjectPath, "archiveStorageObjectSearchName": c.ArchiveStorageObjectSearchName, "archiveStorageObjectType": c.ArchiveStorageObjectType, "marker": c.Marker, "size": c.Size},
		nil)
}

type ArchiveStorageListArchiveStorageBucketsCmd struct {
	ArchiveStorageBucketName        string `name:"archive-storage-bucket-name" help:"Archive Storage Bucket Name"`
	ArchiveStorageBucketUserPurpose string `name:"archive-storage-bucket-user-purpose" help:"Archive Storage Bucket User Purpose"`
	ArchivingSourceId               string `name:"archiving-source-id" help:"Archiving Source ID"`
	ArchivingSourceName             string `name:"archiving-source-name" help:"Archiving Source Name"`
	CreatedBy                       string `name:"created-by" help:"creator"`
	Page                            string `name:"page" help:"Request page number"`
	Size                            string `name:"size" help:"Number of items in the Page"`
	Sort                            string `name:"sort" help:"Sort condition"`
}

func (c *ArchiveStorageListArchiveStorageBucketsCmd) Run() error {
	return RunRequest("GET", "/archive-storage/v1/buckets",
		map[string]string{},
		map[string]string{"archiveStorageBucketName": c.ArchiveStorageBucketName, "archiveStorageBucketUserPurpose": c.ArchiveStorageBucketUserPurpose, "archivingSourceId": c.ArchivingSourceId, "archivingSourceName": c.ArchivingSourceName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ArchiveStorageListArchivingJobsCmd struct {
	BucketId             string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	ArchivingCompletedDt string `name:"archiving-completed-dt" help:"Archiving Completed Date" required:""`
	ArchivingExecutionDt string `name:"archiving-execution-dt" help:"Archiving Execution Date" required:""`
	ArchivingState       string `name:"archiving-state" help:"Archiving State"`
	ArchivingType        string `name:"archiving-type" help:"Archiving Type" required:""`
	TimeZoneName         string `name:"time-zone-name" help:"Time Zone Name"`
	Page                 string `name:"page" help:"Request page number"`
	Size                 string `name:"size" help:"Number of items in the Page"`
	Sort                 string `name:"sort" help:"Sort condition"`
}

func (c *ArchiveStorageListArchivingJobsCmd) Run() error {
	return RunRequest("GET", "/archive-storage/v1/buckets/{bucketId}/archiving-job",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{"archivingCompletedDt": c.ArchivingCompletedDt, "archivingExecutionDt": c.ArchivingExecutionDt, "archivingState": c.ArchivingState, "archivingType": c.ArchivingType, "timeZoneName": c.TimeZoneName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ArchiveStorageRestoreArchivingCmd struct {
	BucketId string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ArchiveStorageRestoreArchivingCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/archive-storage/v2/buckets/{bucketId}/archiving-job/restore",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{},
		b)
}

type ArchiveStorageUpdateArchiveStorageScheduleCmd struct {
	BucketId string `name:"bucket-id" help:"Archive Storage Bucket ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ArchiveStorageUpdateArchiveStorageScheduleCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/archive-storage/v1/buckets/{bucketId}/archiving-schedules",
		map[string]string{"bucketId": c.BucketId},
		map[string]string{},
		b)
}

// ArchiveStorageCmd groups all archive-storage operations.
type ArchiveStorageCmd struct {
	CreateArchiveStorage            ArchiveStorageCreateArchiveStorageCmd            `cmd:"" name:"create-archive-storage" help:"Create Archive Storage"`
	DeleteArchiveStorage            ArchiveStorageDeleteArchiveStorageCmd            `cmd:"" name:"delete-archive-storage" help:"Delete Archive Storage"`
	DeleteArchiveStorageObjects     ArchiveStorageDeleteArchiveStorageObjectsCmd     `cmd:"" name:"delete-archive-storage-objects" help:"Delete Archive Storage Objects"`
	DeleteArchivingJob              ArchiveStorageDeleteArchivingJobCmd              `cmd:"" name:"delete-archiving-job" help:"Delete Archiving Job"`
	DetailArchiveStorageBucket      ArchiveStorageDetailArchiveStorageBucketCmd      `cmd:"" name:"detail-archive-storage-bucket" help:"Detail ArchiveStorage Bucket"`
	DetailArchivingJob              ArchiveStorageDetailArchivingJobCmd              `cmd:"" name:"detail-archiving-job" help:"Detail Archiving Job"`
	ListArchiveStorageBucketObjects ArchiveStorageListArchiveStorageBucketObjectsCmd `cmd:"" name:"list-archive-storage-bucket-objects" help:"List ArchiveStorage Bucket Object"`
	ListArchiveStorageBuckets       ArchiveStorageListArchiveStorageBucketsCmd       `cmd:"" name:"list-archive-storage-buckets" help:"List ArchiveStorage Bucket"`
	ListArchivingJobs               ArchiveStorageListArchivingJobsCmd               `cmd:"" name:"list-archiving-jobs" help:"List Archiving Job"`
	RestoreArchiving                ArchiveStorageRestoreArchivingCmd                `cmd:"" name:"restore-archiving" help:"Restore Archiving"`
	UpdateArchiveStorageSchedule    ArchiveStorageUpdateArchiveStorageScheduleCmd    `cmd:"" name:"update-archive-storage-schedule" help:"Update Archiving Schedule Policy"`
}
