// Code generated by codegen. DO NOT EDIT.

package commands

type BackupBackupMasterConnectionCheckCmd struct {
	BackupAgentId string `name:"backup-agent-id" help:"Backup Agent Id" required:""`
}

func (c *BackupBackupMasterConnectionCheckCmd) Run() error {
	return RunRequest("GET", "/backup/v1/backup-agents/{backupAgentId}/connection-state",
		map[string]string{"backupAgentId": c.BackupAgentId},
		map[string]string{},
		nil)
}

type BackupCancelBackupDrRelationshipCmd struct {
	BackupDrId string `name:"backup-dr-id" help:"Backup DR ID" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupCancelBackupDrRelationshipCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/backup/v2/backups/dr/{backupDrId}",
		map[string]string{"backupDrId": c.BackupDrId},
		map[string]string{},
		b)
}

type BackupCancelBackupJobCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	JobId    string `name:"job-id" help:"Job ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupCancelBackupJobCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v2/backups/{backupId}/jobs/{jobId}/cancel",
		map[string]string{"backupId": c.BackupId, "jobId": c.JobId},
		map[string]string{},
		b)
}

type BackupCreateBackupAgentCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupCreateBackupAgentCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v1/backup-agents",
		map[string]string{},
		map[string]string{},
		b)
}

type BackupCreateBackup2Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupCreateBackup2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v5/backups",
		map[string]string{},
		map[string]string{},
		b)
}

type BackupDeleteBackupCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
}

func (c *BackupDeleteBackupCmd) Run() error {
	return RunRequest("DELETE", "/backup/v2/backups/{backupId}",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		nil)
}

type BackupDeleteBackupAgentCmd struct {
	BackupAgentId string `name:"backup-agent-id" help:"Backup Agent Id" required:""`
}

func (c *BackupDeleteBackupAgentCmd) Run() error {
	return RunRequest("DELETE", "/backup/v1/backup-agents/{backupAgentId}",
		map[string]string{"backupAgentId": c.BackupAgentId},
		map[string]string{},
		nil)
}

type BackupDeleteBackupDrCmd struct {
	BackupDrId string `name:"backup-dr-id" help:"Backup DR ID" required:""`
}

func (c *BackupDeleteBackupDrCmd) Run() error {
	return RunRequest("DELETE", "/backup/v2/backups/dr/{backupDrId}",
		map[string]string{"backupDrId": c.BackupDrId},
		map[string]string{},
		nil)
}

type BackupDeleteBackupImagesCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupDeleteBackupImagesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/backup/v2/backups/{backupId}/backup-images",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		b)
}

type BackupDeleteBackupImagesDrCmd struct {
	BackupDrId string `name:"backup-dr-id" help:"Backup DR ID" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupDeleteBackupImagesDrCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/backup/v2/backups/dr/{backupDrId}/backup-images",
		map[string]string{"backupDrId": c.BackupDrId},
		map[string]string{},
		b)
}

type BackupDetailBackupCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
}

func (c *BackupDetailBackupCmd) Run() error {
	return RunRequest("GET", "/backup/v4/backups/{backupId}",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		nil)
}

type BackupDetailBackupAgentCmd struct {
	BackupAgentId string `name:"backup-agent-id" help:"Backup Agent Id" required:""`
}

func (c *BackupDetailBackupAgentCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backup-agents/{backupAgentId}",
		map[string]string{"backupAgentId": c.BackupAgentId},
		map[string]string{},
		nil)
}

type BackupExecuteManualBackupCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupExecuteManualBackupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v2/backups/{backupId}/manual-backup",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		b)
}

type BackupGetBackupAgentInstallFilePathCmd struct {
	AzCode        string `name:"az-code" help:"AZ Code"`
	ObjectOsType  string `name:"object-os-type" help:"Object OS Type" required:""`
	ServiceZoneId string `name:"service-zone-id" help:"Zone ID" required:""`
}

func (c *BackupGetBackupAgentInstallFilePathCmd) Run() error {
	return RunRequest("GET", "/backup/v1/backup-agents/install-file-path",
		map[string]string{},
		map[string]string{"azCode": c.AzCode, "objectOsType": c.ObjectOsType, "serviceZoneId": c.ServiceZoneId},
		nil)
}

type BackupGetFilesystemRestoreCandidateObjectListCmd struct {
	AzCode         string `name:"az-code" help:"AZ Code"`
	ObjectName     string `name:"object-name" help:"Object Name"`
	ObjectType     string `name:"object-type" help:"Object Type" required:""`
	OriginObjectId string `name:"origin-object-id" help:"Backup Object ID" required:""`
	ServiceZoneId  string `name:"service-zone-id" help:"Zone ID" required:""`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *BackupGetFilesystemRestoreCandidateObjectListCmd) Run() error {
	return RunRequest("GET", "/backup/v1/backups/restore-filesystem-candidate-objects",
		map[string]string{},
		map[string]string{"azCode": c.AzCode, "objectName": c.ObjectName, "objectType": c.ObjectType, "originObjectId": c.OriginObjectId, "serviceZoneId": c.ServiceZoneId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListBackupAgentsCmd struct {
	BackupAgentId       string `name:"backup-agent-id" help:"Backup Agent Id"`
	BackupAgentName     string `name:"backup-agent-name" help:"Backup Agent Name"`
	ObjectBackupAgentIp string `name:"object-backup-agent-ip" help:"Object Backup Agent Ip"`
	ObjectId            string `name:"object-id" help:"Backup Object ID"`
	ObjectIds           string `name:"object-ids" help:"Backup Object ID List"`
	ObjectName          string `name:"object-name" help:"Backup Object Name"`
	CreatedBy           string `name:"created-by" help:"creator"`
	Page                string `name:"page" help:"Request page number"`
	Size                string `name:"size" help:"Number of items in the Page"`
	Sort                string `name:"sort" help:"Sort condition"`
}

func (c *BackupListBackupAgentsCmd) Run() error {
	return RunRequest("GET", "/backup/v1/backup-agents",
		map[string]string{},
		map[string]string{"backupAgentId": c.BackupAgentId, "backupAgentName": c.BackupAgentName, "objectBackupAgentIp": c.ObjectBackupAgentIp, "objectId": c.ObjectId, "objectIds": c.ObjectIds, "objectName": c.ObjectName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListBackupImagesCmd struct {
	BackupId     string `name:"backup-id" help:"Backup ID" required:""`
	EndDate      string `name:"end-date" help:"Search End Date"`
	StartDate    string `name:"start-date" help:"Search Start Date"`
	TimeZoneName string `name:"time-zone-name" help:"Time Zone Name"`
	Page         string `name:"page" help:"Request page number"`
	Size         string `name:"size" help:"Number of items in the Page"`
	Sort         string `name:"sort" help:"Sort condition"`
}

func (c *BackupListBackupImagesCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/{backupId}/backup-images",
		map[string]string{"backupId": c.BackupId},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "timeZoneName": c.TimeZoneName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListBackupsCmd struct {
	BackupName               string `name:"backup-name" help:"Backup Name"`
	BackupPolicyTypeCategory string `name:"backup-policy-type-category" help:"Backup policy Type Category"`
	CreatedBy                string `name:"created-by" help:"ID of User who created"`
	Page                     string `name:"page" help:"Request page number"`
	Size                     string `name:"size" help:"Number of items in the Page"`
	Sort                     string `name:"sort" help:"Sort condition"`
}

func (c *BackupListBackupsCmd) Run() error {
	return RunRequest("GET", "/backup/v3/backups",
		map[string]string{},
		map[string]string{"backupName": c.BackupName, "backupPolicyTypeCategory": c.BackupPolicyTypeCategory, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListCandidateObjectsForBackupAgentCmd struct {
	AzCode        string `name:"az-code" help:"AZ Code"`
	ObjectName    string `name:"object-name" help:"Object Name"`
	ObjectType    string `name:"object-type" help:"Object Type" required:""`
	Operation     string `name:"operation" help:"" required:""`
	ServiceZoneId string `name:"service-zone-id" help:"Zone ID" required:""`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *BackupListCandidateObjectsForBackupAgentCmd) Run() error {
	return RunRequest("GET", "/backup/v1/backup-agents/candidate-objects",
		map[string]string{},
		map[string]string{"azCode": c.AzCode, "objectName": c.ObjectName, "objectType": c.ObjectType, "operation": c.Operation, "serviceZoneId": c.ServiceZoneId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListDrBackupImagesCmd struct {
	BackupDrId   string `name:"backup-dr-id" help:"Backup DR ID" required:""`
	EndDate      string `name:"end-date" help:"Search End Date"`
	StartDate    string `name:"start-date" help:"Search Start Date"`
	TimeZoneName string `name:"time-zone-name" help:"Time Zone Name"`
	Page         string `name:"page" help:"Request page number"`
	Size         string `name:"size" help:"Number of items in the Page"`
	Sort         string `name:"sort" help:"Sort condition"`
}

func (c *BackupListDrBackupImagesCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/dr/{backupDrId}/backup-images",
		map[string]string{"backupDrId": c.BackupDrId},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "timeZoneName": c.TimeZoneName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListDrRestoreHistoriesCmd struct {
	BackupDrId   string `name:"backup-dr-id" help:"Backup DR ID" required:""`
	EndDate      string `name:"end-date" help:"Search End Date"`
	StartDate    string `name:"start-date" help:"Search Start Date"`
	TimeZoneName string `name:"time-zone-name" help:"Time Zone Name"`
	Page         string `name:"page" help:"Request page number"`
	Size         string `name:"size" help:"Number of items in the Page"`
	Sort         string `name:"sort" help:"Sort condition"`
}

func (c *BackupListDrRestoreHistoriesCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/dr/{backupDrId}/restore-histories",
		map[string]string{"backupDrId": c.BackupDrId},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "timeZoneName": c.TimeZoneName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListJobHistoriesCmd struct {
	BackupId     string `name:"backup-id" help:"Backup ID" required:""`
	BackupState  string `name:"backup-state" help:"Backup State" required:""`
	EndDate      string `name:"end-date" help:"Search End Date"`
	StartDate    string `name:"start-date" help:"Search Start Date"`
	TimeZoneName string `name:"time-zone-name" help:"Time Zone Name"`
	Page         string `name:"page" help:"Request page number"`
	Size         string `name:"size" help:"Number of items in the Page"`
	Sort         string `name:"sort" help:"Sort condition"`
}

func (c *BackupListJobHistoriesCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/{backupId}/job-histories",
		map[string]string{"backupId": c.BackupId},
		map[string]string{"backupState": c.BackupState, "endDate": c.EndDate, "startDate": c.StartDate, "timeZoneName": c.TimeZoneName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListRestoreHistoriesCmd struct {
	BackupId     string `name:"backup-id" help:"Backup ID" required:""`
	EndDate      string `name:"end-date" help:"Search End Date"`
	StartDate    string `name:"start-date" help:"Search Start Date"`
	TimeZoneName string `name:"time-zone-name" help:"Time Zone Name"`
	Page         string `name:"page" help:"Request page number"`
	Size         string `name:"size" help:"Number of items in the Page"`
	Sort         string `name:"sort" help:"Sort condition"`
}

func (c *BackupListRestoreHistoriesCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/{backupId}/restore-histories",
		map[string]string{"backupId": c.BackupId},
		map[string]string{"endDate": c.EndDate, "startDate": c.StartDate, "timeZoneName": c.TimeZoneName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupListSchedulesCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Page     string `name:"page" help:"Request page number"`
	Size     string `name:"size" help:"Number of items in the Page"`
	Sort     string `name:"sort" help:"Sort condition"`
}

func (c *BackupListSchedulesCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/{backupId}/schedules",
		map[string]string{"backupId": c.BackupId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BackupPolicyDupliCheckCmd struct {
	FileSystemBackupSelection string `name:"file-system-backup-selection" help:"Target Filesystem" required:""`
	ObjectId                  string `name:"object-id" help:"Backup Object ID" required:""`
}

func (c *BackupPolicyDupliCheckCmd) Run() error {
	return RunRequest("GET", "/backup/v2/backups/check-policy-duplication",
		map[string]string{},
		map[string]string{"fileSystemBackupSelection": c.FileSystemBackupSelection, "objectId": c.ObjectId},
		nil)
}

type BackupRestoreBackupCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupRestoreBackupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v2/backups/{backupId}/restore",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		b)
}

type BackupRestoreBackupDrCmd struct {
	BackupDrId string `name:"backup-dr-id" help:"Backup DR ID" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupRestoreBackupDrCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v2/backups/dr/{backupDrId}/restore",
		map[string]string{"backupDrId": c.BackupDrId},
		map[string]string{},
		b)
}

type BackupRestoreBackupFilesystemCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupRestoreBackupFilesystemCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/backup/v1/backups/{backupId}/restore-filesystem",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		b)
}

type BackupUpdateAgentBackupFilesystemCmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupUpdateAgentBackupFilesystemCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/backup/v2/backups/{backupId}/filesystem-backup-selection",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		b)
}

type BackupUpdateBackupSchedule1Cmd struct {
	BackupId string `name:"backup-id" help:"Backup ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BackupUpdateBackupSchedule1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/backup/v3/backups/{backupId}/schedules",
		map[string]string{"backupId": c.BackupId},
		map[string]string{},
		b)
}

// BackupCmd groups all backup operations.
type BackupCmd struct {
	BackupMasterConnectionCheck             BackupBackupMasterConnectionCheckCmd             `cmd:"" name:"backup-master-connection-check" help:"Check Connection State Between Backup Agent And Backup Master"`
	CancelBackupDrRelationship              BackupCancelBackupDrRelationshipCmd              `cmd:"" name:"cancel-backup-dr-relationship" help:"Cancel Backup DR Relationship"`
	CancelBackupJob                         BackupCancelBackupJobCmd                         `cmd:"" name:"cancel-backup-job" help:"Cancel Backup Job"`
	CreateBackupAgent                       BackupCreateBackupAgentCmd                       `cmd:"" name:"create-backup-agent" help:"Create Backup Agent"`
	CreateBackup2                           BackupCreateBackup2Cmd                           `cmd:"" name:"create-backup_2" help:"Create Backup"`
	DeleteBackup                            BackupDeleteBackupCmd                            `cmd:"" name:"delete-backup" help:"Delete Backup"`
	DeleteBackupAgent                       BackupDeleteBackupAgentCmd                       `cmd:"" name:"delete-backup-agent" help:"Delete Backup Agent"`
	DeleteBackupDr                          BackupDeleteBackupDrCmd                          `cmd:"" name:"delete-backup-dr" help:"Delete Backup DR"`
	DeleteBackupImages                      BackupDeleteBackupImagesCmd                      `cmd:"" name:"delete-backup-images" help:"Delete Backup Images"`
	DeleteBackupImagesDr                    BackupDeleteBackupImagesDrCmd                    `cmd:"" name:"delete-backup-images-dr" help:"Delete Backup DR Images"`
	DetailBackup                            BackupDetailBackupCmd                            `cmd:"" name:"detail-backup" help:"Get Backup Detail"`
	DetailBackupAgent                       BackupDetailBackupAgentCmd                       `cmd:"" name:"detail-backup-agent" help:"Get Backup Agent Detail"`
	ExecuteManualBackup                     BackupExecuteManualBackupCmd                     `cmd:"" name:"execute-manual-backup" help:"Execute Manual Backup"`
	GetBackupAgentInstallFilePath           BackupGetBackupAgentInstallFilePathCmd           `cmd:"" name:"get-backup-agent-install-file-path" help:"Get Backup Agent Install File Path"`
	GetFilesystemRestoreCandidateObjectList BackupGetFilesystemRestoreCandidateObjectListCmd `cmd:"" name:"get-filesystem-restore-candidate-object-list" help:"Get Filesystem Restore Candidate Object List"`
	ListBackupAgents                        BackupListBackupAgentsCmd                        `cmd:"" name:"list-backup-agents" help:"Get Backup Agent List"`
	ListBackupImages                        BackupListBackupImagesCmd                        `cmd:"" name:"list-backup-images" help:"Get the List of Backup Images"`
	ListBackups                             BackupListBackupsCmd                             `cmd:"" name:"list-backups" help:"Get Backup List"`
	ListCandidateObjectsForBackupAgent      BackupListCandidateObjectsForBackupAgentCmd      `cmd:"" name:"list-candidate-objects-for-backup-agent" help:"Get Backup Agents Candidate Object List"`
	ListDrBackupImages                      BackupListDrBackupImagesCmd                      `cmd:"" name:"list-dr-backup-images" help:"Get the List of Backup DR Images"`
	ListDrRestoreHistories                  BackupListDrRestoreHistoriesCmd                  `cmd:"" name:"list-dr-restore-histories" help:"Get the List of Backup DR Restore Histories"`
	ListJobHistories                        BackupListJobHistoriesCmd                        `cmd:"" name:"list-job-histories" help:"Get the List of Job Histories"`
	ListRestoreHistories                    BackupListRestoreHistoriesCmd                    `cmd:"" name:"list-restore-histories" help:"Get the List of Restore Histories"`
	ListSchedules                           BackupListSchedulesCmd                           `cmd:"" name:"list-schedules" help:"Get the List of Backup Schedules"`
	PolicyDupliCheck                        BackupPolicyDupliCheckCmd                        `cmd:"" name:"policy-dupli-check" help:"Check the Duplication of Policy"`
	RestoreBackup                           BackupRestoreBackupCmd                           `cmd:"" name:"restore-backup" help:"Restore Backup"`
	RestoreBackupDr                         BackupRestoreBackupDrCmd                         `cmd:"" name:"restore-backup-dr" help:"Restore Backup DR"`
	RestoreBackupFilesystem                 BackupRestoreBackupFilesystemCmd                 `cmd:"" name:"restore-backup-filesystem" help:"Restore Backup Agent Filesystem"`
	UpdateAgentBackupFilesystem             BackupUpdateAgentBackupFilesystemCmd             `cmd:"" name:"update-agent-backup-filesystem" help:"Update Agent Backup Filesystem"`
	UpdateBackupSchedule1                   BackupUpdateBackupSchedule1Cmd                   `cmd:"" name:"update-backup-schedule_1" help:"Update Backup Schedule"`
}
