// Code generated by codegen. DO NOT EDIT.

package commands

type BillingDetailBillComparisonCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
}

func (c *BillingDetailBillComparisonCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/{billYearMonth}/comparison",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		nil)
}

type BillingDetailBillInfoCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
}

func (c *BillingDetailBillInfoCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/months/{billYearMonth}",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		nil)
}

type BillingDetailBillInfo1Cmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDetailBillInfo1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v3/bills/months/{billYearMonth}",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		b)
}

type BillingDetailBillSummaryCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
}

func (c *BillingDetailBillSummaryCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/{billYearMonth}",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		nil)
}

type BillingDetailLedgerBillCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
	ContractId    string `name:"contract-id" help:"Contract Id" required:""`
}

func (c *BillingDetailLedgerBillCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/{billYearMonth}/ledgers/{contractId}",
		map[string]string{"billYearMonth": c.BillYearMonth, "contractId": c.ContractId},
		map[string]string{},
		nil)
}

type BillingDetailLedgerUsageCmd struct {
	ContractId         string `name:"contract-id" help:"Contract Id" required:""`
	UsedEndYearMonth   string `name:"used-end-year-month" help:"Used End Year Month" required:""`
	UsedStartYearMonth string `name:"used-start-year-month" help:"Used Start Year Month" required:""`
}

func (c *BillingDetailLedgerUsageCmd) Run() error {
	return RunRequest("GET", "/billing/v2/usages/{contractId}",
		map[string]string{"contractId": c.ContractId},
		map[string]string{"usedEndYearMonth": c.UsedEndYearMonth, "usedStartYearMonth": c.UsedStartYearMonth},
		nil)
}

type BillingDetailUsageInfoCmd struct {
	UsedDate string `name:"used-date" help:"Used Date" required:""`
}

func (c *BillingDetailUsageInfoCmd) Run() error {
	return RunRequest("GET", "/billing/v2/usages/days/{usedDate}",
		map[string]string{"usedDate": c.UsedDate},
		map[string]string{},
		nil)
}

type BillingDetailUsageInfo1Cmd struct {
	UsedDate string `name:"used-date" help:"Used Date" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDetailUsageInfo1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v3/usages/days/{usedDate}",
		map[string]string{"usedDate": c.UsedDate},
		map[string]string{},
		b)
}

type BillingDetailUsageSummaryCmd struct {
	UsedYearMonth string `name:"used-year-month" help:"Used Year Month" required:""`
}

func (c *BillingDetailUsageSummaryCmd) Run() error {
	return RunRequest("GET", "/billing/v2/usages/summary/{usedYearMonth}",
		map[string]string{"usedYearMonth": c.UsedYearMonth},
		map[string]string{},
		nil)
}

type BillingDownloadBillComparisonCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDownloadBillComparisonCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v2/bills/{billYearMonth}/comparison/download",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		b)
}

type BillingDownloadEstimateChargeCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDownloadEstimateChargeCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v2/charges/estimate/download",
		map[string]string{},
		map[string]string{},
		b)
}

type BillingDownloadLedgerUsageCmd struct {
	ContractId         string `name:"contract-id" help:"Contract Id" required:""`
	UsedEndYearMonth   string `name:"used-end-year-month" help:"Used End Year Month" required:""`
	UsedStartYearMonth string `name:"used-start-year-month" help:"Used Start Year Month" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDownloadLedgerUsageCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v2/usages/{contractId}/download",
		map[string]string{"contractId": c.ContractId},
		map[string]string{"usedEndYearMonth": c.UsedEndYearMonth, "usedStartYearMonth": c.UsedStartYearMonth},
		b)
}

type BillingDownloadLedgerUsagesCmd struct {
	ProductGroupName   string `name:"product-group-name" help:"Product Group Name"`
	UsedEndYearMonth   string `name:"used-end-year-month" help:"Used End Year Month" required:""`
	UsedStartYearMonth string `name:"used-start-year-month" help:"Used Start Year Month" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDownloadLedgerUsagesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v2/usages/download",
		map[string]string{},
		map[string]string{"productGroupName": c.ProductGroupName, "usedEndYearMonth": c.UsedEndYearMonth, "usedStartYearMonth": c.UsedStartYearMonth},
		b)
}

type BillingDownloadLedgersBillsCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingDownloadLedgersBillsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v2/bills/{billYearMonth}/ledgers/download",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		b)
}

type BillingEsgdetailCmd struct {
	EmissionEndYearMonth   string `name:"emission-end-year-month" help:"Emission End Year Month" required:""`
	EmissionStartYearMonth string `name:"emission-start-year-month" help:"Emission Start Year Month" required:""`
	ProductGroupName       string `name:"product-group-name" help:"Product Group Name" required:""`
}

func (c *BillingEsgdetailCmd) Run() error {
	return RunRequest("GET", "/billing/v2/esg/detail",
		map[string]string{},
		map[string]string{"emissionEndYearMonth": c.EmissionEndYearMonth, "emissionStartYearMonth": c.EmissionStartYearMonth, "productGroupName": c.ProductGroupName},
		nil)
}

type BillingEsgsummaryCmd struct {
	EmissionEndYearMonth   string `name:"emission-end-year-month" help:"Emission End Year Month" required:""`
	EmissionStartYearMonth string `name:"emission-start-year-month" help:"Emission Start Year Month" required:""`
}

func (c *BillingEsgsummaryCmd) Run() error {
	return RunRequest("GET", "/billing/v2/esg/summary",
		map[string]string{},
		map[string]string{"emissionEndYearMonth": c.EmissionEndYearMonth, "emissionStartYearMonth": c.EmissionStartYearMonth},
		nil)
}

type BillingEstimateChargeCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingEstimateChargeCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/billing/v2/charges/estimate",
		map[string]string{},
		map[string]string{},
		b)
}

type BillingListAccountBudgetsCmd struct {
}

func (c *BillingListAccountBudgetsCmd) Run() error {
	return RunRequest("GET", "/billing/v2/budgets/accounts",
		map[string]string{},
		map[string]string{},
		nil)
}

type BillingListBillMonthsCmd struct {
}

func (c *BillingListBillMonthsCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/months",
		map[string]string{},
		map[string]string{},
		nil)
}

type BillingListBillTrendsCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
}

func (c *BillingListBillTrendsCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/{billYearMonth}/trend",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		nil)
}

type BillingListDashboardTrendCmd struct {
}

func (c *BillingListDashboardTrendCmd) Run() error {
	return RunRequest("GET", "/billing/v2/dashboard/trend",
		map[string]string{},
		map[string]string{},
		nil)
}

type BillingListLedgerUsagesCmd struct {
	ProductGroupName   string `name:"product-group-name" help:"Product Group Name"`
	UsedEndYearMonth   string `name:"used-end-year-month" help:"Used End Year Month" required:""`
	UsedStartYearMonth string `name:"used-start-year-month" help:"Used Start Year Month" required:""`
}

func (c *BillingListLedgerUsagesCmd) Run() error {
	return RunRequest("GET", "/billing/v2/usages",
		map[string]string{},
		map[string]string{"productGroupName": c.ProductGroupName, "usedEndYearMonth": c.UsedEndYearMonth, "usedStartYearMonth": c.UsedStartYearMonth},
		nil)
}

type BillingListLedgersBillsCmd struct {
	BillYearMonth string `name:"bill-year-month" help:"Bill Year Month" required:""`
}

func (c *BillingListLedgersBillsCmd) Run() error {
	return RunRequest("GET", "/billing/v2/bills/{billYearMonth}/ledgers",
		map[string]string{"billYearMonth": c.BillYearMonth},
		map[string]string{},
		nil)
}

type BillingListProjectBudgetsCmd struct {
	AccountId  string `name:"account-id" help:"Account Id" required:""`
	ProjectIds string `name:"project-ids" help:"ProjectId List"`
	Page       string `name:"page" help:"Request page number"`
	Size       string `name:"size" help:"Number of items in the Page"`
	Sort       string `name:"sort" help:"Sort condition"`
}

func (c *BillingListProjectBudgetsCmd) Run() error {
	return RunRequest("GET", "/billing/v2/budgets/accounts/{accountId}/projects",
		map[string]string{"accountId": c.AccountId},
		map[string]string{"projectIds": c.ProjectIds, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BillingListProjectDashboardTrendCmd struct {
}

func (c *BillingListProjectDashboardTrendCmd) Run() error {
	return RunRequest("GET", "/billing/v2/dashboard/project/trend",
		map[string]string{},
		map[string]string{},
		nil)
}

type BillingListProjectUsagesCmd struct {
	SearchKeyword string `name:"search-keyword" help:"Search Keyword"`
	SearchType    string `name:"search-type" help:"No Search Criteria = 0, Account Name = 1, Project Type = 2, Creator = 3"`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *BillingListProjectUsagesCmd) Run() error {
	return RunRequest("GET", "/billing/v2/usages/projects",
		map[string]string{},
		map[string]string{"searchKeyword": c.SearchKeyword, "searchType": c.SearchType, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BillingProjectBudgetCmd struct {
	ProjectId string `name:"project-id" help:"Project Id" required:""`
}

func (c *BillingProjectBudgetCmd) Run() error {
	return RunRequest("GET", "/billing/v2/budgets/project/{projectId}",
		map[string]string{"projectId": c.ProjectId},
		map[string]string{},
		nil)
}

type BillingSaveProjectBudgetCmd struct {
	ProjectId string `name:"project-id" help:"Project Id" required:""`
	Body      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BillingSaveProjectBudgetCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/billing/v2/budgets/project/{projectId}",
		map[string]string{"projectId": c.ProjectId},
		map[string]string{},
		b)
}

// BillingCmd groups all billing operations.
type BillingCmd struct {
	DetailBillComparison      BillingDetailBillComparisonCmd      `cmd:"" name:"detail-bill-comparison" help:"Get Bill Comparison Detail"`
	DetailBillInfo            BillingDetailBillInfoCmd            `cmd:"" name:"detail-bill-info" help:"Get Bill Information"`
	DetailBillInfo1           BillingDetailBillInfo1Cmd           `cmd:"" name:"detail-bill-info_1" help:"Get Bill Information"`
	DetailBillSummary         BillingDetailBillSummaryCmd         `cmd:"" name:"detail-bill-summary" help:"Get Bill Summary Detail"`
	DetailLedgerBill          BillingDetailLedgerBillCmd          `cmd:"" name:"detail-ledger-bill" help:"Get Bill Detail"`
	DetailLedgerUsage         BillingDetailLedgerUsageCmd         `cmd:"" name:"detail-ledger-usage" help:"Get Usage Detail"`
	DetailUsageInfo           BillingDetailUsageInfoCmd           `cmd:"" name:"detail-usage-info" help:"Get Daily Usage Information"`
	DetailUsageInfo1          BillingDetailUsageInfo1Cmd          `cmd:"" name:"detail-usage-info_1" help:"Get Daily Usage Information"`
	DetailUsageSummary        BillingDetailUsageSummaryCmd        `cmd:"" name:"detail-usage-summary" help:"Get Usage Summary Detail"`
	DownloadBillComparison    BillingDownloadBillComparisonCmd    `cmd:"" name:"download-bill-comparison" help:"Download Bill Comparision Detail"`
	DownloadEstimateCharge    BillingDownloadEstimateChargeCmd    `cmd:"" name:"download-estimate-charge" help:"Download Estimated Charge"`
	DownloadLedgerUsage       BillingDownloadLedgerUsageCmd       `cmd:"" name:"download-ledger-usage" help:"Download Usage Detail"`
	DownloadLedgerUsages      BillingDownloadLedgerUsagesCmd      `cmd:"" name:"download-ledger-usages" help:"Download Usage List"`
	DownloadLedgersBills      BillingDownloadLedgersBillsCmd      `cmd:"" name:"download-ledgers-bills" help:"Download Bill Detail List"`
	Esgdetail                 BillingEsgdetailCmd                 `cmd:"" name:"esgdetail" help:"Get ESG Detail"`
	Esgsummary                BillingEsgsummaryCmd                `cmd:"" name:"esgsummary" help:"Get ESG Summary"`
	EstimateCharge            BillingEstimateChargeCmd            `cmd:"" name:"estimate-charge" help:"Calculate Estimated Charge"`
	ListAccountBudgets        BillingListAccountBudgetsCmd        `cmd:"" name:"list-account-budgets" help:"Search Account Budget List"`
	ListBillMonths            BillingListBillMonthsCmd            `cmd:"" name:"list-bill-months" help:"Search Bill Month List"`
	ListBillTrends            BillingListBillTrendsCmd            `cmd:"" name:"list-bill-trends" help:"Search Bill Trends for 6 Months"`
	ListDashboardTrend        BillingListDashboardTrendCmd        `cmd:"" name:"list-dashboard-trend" help:"Search Last 3 Months Amount For All Projects"`
	ListLedgerUsages          BillingListLedgerUsagesCmd          `cmd:"" name:"list-ledger-usages" help:"Search Usage List"`
	ListLedgersBills          BillingListLedgersBillsCmd          `cmd:"" name:"list-ledgers-bills" help:"Search Bill Detail List"`
	ListProjectBudgets        BillingListProjectBudgetsCmd        `cmd:"" name:"list-project-budgets" help:"Search Project Budget List"`
	ListProjectDashboardTrend BillingListProjectDashboardTrendCmd `cmd:"" name:"list-project-dashboard-trend" help:"Search Last 3 Months Amount For A project"`
	ListProjectUsages         BillingListProjectUsagesCmd         `cmd:"" name:"list-project-usages" help:"Search Project List"`
	ProjectBudget             BillingProjectBudgetCmd             `cmd:"" name:"project-budget" help:"Get Project Budget Detail"`
	SaveProjectBudget         BillingSaveProjectBudgetCmd         `cmd:"" name:"save-project-budget" help:"Save Project Budget"`
}
