// Code generated by codegen. DO NOT EDIT.

package commands

type BlockStorageAttachBlockStorageCmd struct {
	BlockStorageId string `name:"block-storage-id" help:"Block Storage ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BlockStorageAttachBlockStorageCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/block-storage/v2/block-storages/{blockStorageId}/attach",
		map[string]string{"blockStorageId": c.BlockStorageId},
		map[string]string{},
		b)
}

type BlockStorageCreateBlockStorageV3Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BlockStorageCreateBlockStorageV3Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/block-storage/v3/block-storages",
		map[string]string{},
		map[string]string{},
		b)
}

type BlockStorageDeleteBlockStorageCmd struct {
	BlockStorageId string `name:"block-storage-id" help:"Block Storage ID" required:""`
}

func (c *BlockStorageDeleteBlockStorageCmd) Run() error {
	return RunRequest("DELETE", "/block-storage/v2/block-storages/{blockStorageId}",
		map[string]string{"blockStorageId": c.BlockStorageId},
		map[string]string{},
		nil)
}

type BlockStorageDetachBlockStorageCmd struct {
	BlockStorageId string `name:"block-storage-id" help:"Block Storage ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BlockStorageDetachBlockStorageCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/block-storage/v2/block-storages/{blockStorageId}/detach",
		map[string]string{"blockStorageId": c.BlockStorageId},
		map[string]string{},
		b)
}

type BlockStorageDetailBlockStorageCmd struct {
	BlockStorageId string `name:"block-storage-id" help:"Block Storage ID" required:""`
}

func (c *BlockStorageDetailBlockStorageCmd) Run() error {
	return RunRequest("GET", "/block-storage/v2/block-storages/{blockStorageId}",
		map[string]string{"blockStorageId": c.BlockStorageId},
		map[string]string{},
		nil)
}

type BlockStorageListBlockStorageVirtualServersCmd struct {
	BlockStorageId string `name:"block-storage-id" help:"Block Storage ID" required:""`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *BlockStorageListBlockStorageVirtualServersCmd) Run() error {
	return RunRequest("GET", "/block-storage/v2/block-storages/{blockStorageId}/virtual-servers",
		map[string]string{"blockStorageId": c.BlockStorageId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BlockStorageListBlockStoragesCmd struct {
	BlockStorageName  string `name:"block-storage-name" help:"Block Storage Name"`
	VirtualServerId   string `name:"virtual-server-id" help:"Virtual Server ID virtualServerId is obtained through Get List of Virtual Servers"`
	VirtualServerName string `name:"virtual-server-name" help:"Virtual Server Name"`
	CreatedBy         string `name:"created-by" help:"Creator"`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *BlockStorageListBlockStoragesCmd) Run() error {
	return RunRequest("GET", "/block-storage/v2/block-storages",
		map[string]string{},
		map[string]string{"blockStorageName": c.BlockStorageName, "virtualServerId": c.VirtualServerId, "virtualServerName": c.VirtualServerName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type BlockStorageResizeBlockStorageV3Cmd struct {
	BlockStorageId string `name:"block-storage-id" help:"Block Storage ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *BlockStorageResizeBlockStorageV3Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/block-storage/v3/block-storages/{blockStorageId}/resize",
		map[string]string{"blockStorageId": c.BlockStorageId},
		map[string]string{},
		b)
}

// BlockStorageCmd groups all block-storage operations.
type BlockStorageCmd struct {
	AttachBlockStorage             BlockStorageAttachBlockStorageCmd             `cmd:"" name:"attach-block-storage" help:"Attach Multi Attach Block storage to Virtual Server"`
	CreateBlockStorageV3           BlockStorageCreateBlockStorageV3Cmd           `cmd:"" name:"create-block-storage-v3" help:"Create Block Storage(v3)"`
	DeleteBlockStorage             BlockStorageDeleteBlockStorageCmd             `cmd:"" name:"delete-block-storage" help:"Delete Block Storage"`
	DetachBlockStorage             BlockStorageDetachBlockStorageCmd             `cmd:"" name:"detach-block-storage" help:"Detach Multi Attach Block storage from Virtual Server"`
	DetailBlockStorage             BlockStorageDetailBlockStorageCmd             `cmd:"" name:"detail-block-storage" help:"Get Block Storage details"`
	ListBlockStorageVirtualServers BlockStorageListBlockStorageVirtualServersCmd `cmd:"" name:"list-block-storage-virtual-servers" help:"Get the List of Virtual Servers that use given Block Storage"`
	ListBlockStorages              BlockStorageListBlockStoragesCmd              `cmd:"" name:"list-block-storages" help:"Get the List of Block Storage"`
	ResizeBlockStorageV3           BlockStorageResizeBlockStorageV3Cmd           `cmd:"" name:"resize-block-storage-v3" help:"Resize Block Storage(v3)"`
}
