// Code generated by codegen. DO NOT EDIT.

package commands

type CertificateCreateCertificateCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *CertificateCreateCertificateCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/certificate/v2/certificates",
		map[string]string{},
		map[string]string{},
		b)
}

type CertificateCreateSelfSignedCertificateCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *CertificateCreateSelfSignedCertificateCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/certificate/v2/certificates/self-signed",
		map[string]string{},
		map[string]string{},
		b)
}

type CertificateDeleteCertificateCmd struct {
	CertificateId string `name:"certificate-id" help:"CertificateId" required:""`
}

func (c *CertificateDeleteCertificateCmd) Run() error {
	return RunRequest("DELETE", "/certificate/v2/certificates/{certificateId}",
		map[string]string{"certificateId": c.CertificateId},
		map[string]string{},
		nil)
}

type CertificateDetailCertificateCmd struct {
	CertificateId string `name:"certificate-id" help:"CertificateId" required:""`
}

func (c *CertificateDetailCertificateCmd) Run() error {
	return RunRequest("GET", "/certificate/v2/certificates/{certificateId}",
		map[string]string{"certificateId": c.CertificateId},
		map[string]string{},
		nil)
}

type CertificateListCertificatesCmd struct {
	CertificateName string `name:"certificate-name" help:"Certificate Name"`
	CommonName      string `name:"common-name" help:"Common Name"`
	IsMine          string `name:"is-mine" help:"isMine"`
	Mine            string `name:"mine" help:""`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *CertificateListCertificatesCmd) Run() error {
	return RunRequest("GET", "/certificate/v2/certificates",
		map[string]string{},
		map[string]string{"certificateName": c.CertificateName, "commonName": c.CommonName, "isMine": c.IsMine, "mine": c.Mine, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

// CertificateCmd groups all certificate operations.
type CertificateCmd struct {
	CreateCertificate           CertificateCreateCertificateCmd           `cmd:"" name:"create-certificate" help:"Create Certificate"`
	CreateSelfSignedCertificate CertificateCreateSelfSignedCertificateCmd `cmd:"" name:"create-self-signed-certificate" help:"Create Certificate"`
	DeleteCertificate           CertificateDeleteCertificateCmd           `cmd:"" name:"delete-certificate" help:"Delete Cert"`
	DetailCertificate           CertificateDetailCertificateCmd           `cmd:"" name:"detail-certificate" help:"Get Cert Detail"`
	ListCertificates            CertificateListCertificatesCmd            `cmd:"" name:"list-certificates" help:"Search Cert List"`
}
