// Code generated by codegen. DO NOT EDIT.

package commands

type CloudHadoopDetailHadoopClusterCmd struct {
	HadoopClusterId string `name:"hadoop-cluster-id" help:"Hadoop cluster ID" required:""`
}

func (c *CloudHadoopDetailHadoopClusterCmd) Run() error {
	return RunRequest("GET", "/analytics/hadoop/v1/hadoop/{hadoopClusterId}",
		map[string]string{"hadoopClusterId": c.HadoopClusterId},
		map[string]string{},
		nil)
}

type CloudHadoopListHadoopClustersCmd struct {
	HadoopClusterName string `name:"hadoop-cluster-name" help:"Hadoop cluster name"`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *CloudHadoopListHadoopClustersCmd) Run() error {
	return RunRequest("GET", "/analytics/hadoop/v1/hadoop",
		map[string]string{},
		map[string]string{"hadoopClusterName": c.HadoopClusterName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

// CloudHadoopCmd groups all cloud-hadoop operations.
type CloudHadoopCmd struct {
	DetailHadoopCluster CloudHadoopDetailHadoopClusterCmd `cmd:"" name:"detail-hadoop-cluster" help:"Detail Hadoop cluster"`
	ListHadoopClusters  CloudHadoopListHadoopClustersCmd  `cmd:"" name:"list-hadoop-clusters" help:"List Hadoop cluster"`
}
