// Code generated by codegen. DO NOT EDIT.

package commands

type ContainerRegistryCheckDuplicationRegistryNameV1Cmd struct {
	RegistryName string `name:"registry-name" help:"Registry Name" required:""`
}

func (c *ContainerRegistryCheckDuplicationRegistryNameV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/check-duplication",
		map[string]string{},
		map[string]string{"registryName": c.RegistryName},
		nil)
}

type ContainerRegistryCheckPrivateAclRegistrationV2Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	ResourceId   string `name:"resource-id" help:"Resource ID" required:""`
	Location     string `name:"location" help:"Location" required:""`
	ResourceType string `name:"resource-type" help:"Resource Type" required:""`
}

func (c *ContainerRegistryCheckPrivateAclRegistrationV2Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v2/registries/{registryId}/private-acl-registration/{resourceId}/check",
		map[string]string{"registryId": c.RegistryId, "resourceId": c.ResourceId},
		map[string]string{"location": c.Location, "resourceType": c.ResourceType},
		nil)
}

type ContainerRegistryCheckVulnerabilityV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	TagId        string `name:"tag-id" help:"Tag ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryCheckVulnerabilityV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/check-vulnerability",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{},
		b)
}

type ContainerRegistryCreateRegistryV1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryCreateRegistryV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/container-registry/v1/registries",
		map[string]string{},
		map[string]string{},
		b)
}

type ContainerRegistryDeleteRegistryV1Cmd struct {
	RegistryId string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	Region     string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDeleteRegistryV1Cmd) Run() error {
	return RunRequest("DELETE", "/container-registry/v1/registries/{registryId}",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDeleteRepositoryV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Region       string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDeleteRepositoryV1Cmd) Run() error {
	return RunRequest("DELETE", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDeleteTagV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	TagId        string `name:"tag-id" help:"Tag ID" required:""`
	Region       string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDeleteTagV1Cmd) Run() error {
	return RunRequest("DELETE", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDeleteTagsV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID Get repositoryId by ListRepositories" required:""`
	Region       string `name:"region" help:"Region" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryDeleteTagsV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/delete",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{"region": c.Region},
		b)
}

type ContainerRegistryDetailRegistryV1Cmd struct {
	RegistryId string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	Region     string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDetailRegistryV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDetailRepositoryV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Region       string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDetailRepositoryV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDetailTagManifestV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	TagId        string `name:"tag-id" help:"Tag ID" required:""`
	Region       string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDetailTagManifestV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/manifest",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDetailTagPackagesV1Cmd struct {
	RegistryId         string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId       string `name:"repository-id" help:"Repository ID" required:""`
	TagId              string `name:"tag-id" help:"Tag ID" required:""`
	PackageNameKeyword string `name:"package-name-keyword" help:"Package Name"`
	Region             string `name:"region" help:"Region" required:""`
	Page               string `name:"page" help:"Page"`
	Size               string `name:"size" help:"Size"`
	Sort               string `name:"sort" help:"Sort"`
}

func (c *ContainerRegistryDetailTagPackagesV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/packages",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"packageNameKeyword": c.PackageNameKeyword, "region": c.Region, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ContainerRegistryDetailTagSecretsCmd struct {
	RegistryId        string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId      string `name:"repository-id" help:"Repository ID" required:""`
	TagId             string `name:"tag-id" help:"Tag ID" required:""`
	Region            string `name:"region" help:"Region" required:""`
	SecretFileKeyword string `name:"secret-file-keyword" help:"Secret File Name"`
	Page              string `name:"page" help:"Page"`
	Size              string `name:"size" help:"Size"`
	Sort              string `name:"sort" help:"Sort"`
}

func (c *ContainerRegistryDetailTagSecretsCmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/secrets",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"region": c.Region, "secretFileKeyword": c.SecretFileKeyword, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ContainerRegistryDetailTagV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	TagId        string `name:"tag-id" help:"Tag ID" required:""`
	Region       string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDetailTagV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryDetailTagVulnerabilitiesV1Cmd struct {
	RegistryId           string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId         string `name:"repository-id" help:"Repository ID" required:""`
	TagId                string `name:"tag-id" help:"Tag ID" required:""`
	FilterCategory       string `name:"filter-category" help:"Category(OS/Language)"`
	FilterSeverity       string `name:"filter-severity" help:"Severity"`
	IsUpdateVersionExist string `name:"is-update-version-exist" help:"Whether a fix version of the vulnerability exists"`
	PackageNameKeyword   string `name:"package-name-keyword" help:"Package Name"`
	Region               string `name:"region" help:"Region" required:""`
	SearchOsLanguageName string `name:"search-os-language-name" help:"OS name or Language name"`
	Page                 string `name:"page" help:"Page"`
	Size                 string `name:"size" help:"Size"`
	Sort                 string `name:"sort" help:"Sort"`
}

func (c *ContainerRegistryDetailTagVulnerabilitiesV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/vulnerabilities",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"filterCategory": c.FilterCategory, "filterSeverity": c.FilterSeverity, "isUpdateVersionExist": c.IsUpdateVersionExist, "packageNameKeyword": c.PackageNameKeyword, "region": c.Region, "searchOsLanguageName": c.SearchOsLanguageName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ContainerRegistryDownloadManifestV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	TagId        string `name:"tag-id" help:"Tag ID" required:""`
	Region       string `name:"region" help:"Region" required:""`
}

func (c *ContainerRegistryDownloadManifestV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/manifest/download",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{"region": c.Region},
		nil)
}

type ContainerRegistryListRegistriesV1Cmd struct {
	Page string `name:"page" help:"Page"`
	Size string `name:"size" help:"Size"`
	Sort string `name:"sort" help:"Sort"`
}

func (c *ContainerRegistryListRegistriesV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ContainerRegistryListRegistriesWithAuthInfoV2Cmd struct {
	Location string `name:"location" help:"Location" required:""`
}

func (c *ContainerRegistryListRegistriesWithAuthInfoV2Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v2/registries-auth-info",
		map[string]string{},
		map[string]string{"location": c.Location},
		nil)
}

type ContainerRegistryListReplicationZoneV1Cmd struct {
	OriginZoneId string `name:"origin-zone-id" help:"Zone ID where the original registry will be created" required:""`
}

func (c *ContainerRegistryListReplicationZoneV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/replication-zones",
		map[string]string{},
		map[string]string{"originZoneId": c.OriginZoneId},
		nil)
}

type ContainerRegistryListRepositoriesV1Cmd struct {
	RegistryId     string `name:"registry-id" help:"Registry ID" required:""`
	Region         string `name:"region" help:"Region" required:""`
	RepositoryName string `name:"repository-name" help:"Repository Name"`
	Page           string `name:"page" help:"Page"`
	Size           string `name:"size" help:"Size"`
	Sort           string `name:"sort" help:"Sort"`
}

func (c *ContainerRegistryListRepositoriesV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{"region": c.Region, "repositoryName": c.RepositoryName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ContainerRegistryListTagsV1Cmd struct {
	RegistryId    string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId  string `name:"repository-id" help:"Repository ID" required:""`
	Region        string `name:"region" help:"Region" required:""`
	SearchDigest  string `name:"search-digest" help:"Digest"`
	SearchTagName string `name:"search-tag-name" help:"Tag Name"`
	Page          string `name:"page" help:"Page"`
	Size          string `name:"size" help:"Size"`
	Sort          string `name:"sort" help:"Sort"`
}

func (c *ContainerRegistryListTagsV1Cmd) Run() error {
	return RunRequest("GET", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{"region": c.Region, "searchDigest": c.SearchDigest, "searchTagName": c.SearchTagName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type ContainerRegistryUpdateAutoScanV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateAutoScanV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/auto-scan",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateDescriptionV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateDescriptionV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/description",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdatePullLimitV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdatePullLimitV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/pull-limit",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateRepositoryLockV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateRepositoryLockV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/lock",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateTagLockV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	TagId        string `name:"tag-id" help:"Tag ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateTagLockV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/tags/{tagId}/lock",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId, "tagId": c.TagId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateLifecyclePolicyV1Cmd struct {
	RegistryId   string `name:"registry-id" help:"Registry ID" required:""`
	RepositoryId string `name:"repository-id" help:"Repository ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateLifecyclePolicyV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/repositories/{repositoryId}/lifecycle",
		map[string]string{"registryId": c.RegistryId, "repositoryId": c.RepositoryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdatePublicEndpointUseYnV1Cmd struct {
	RegistryId string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdatePublicEndpointUseYnV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/is-public-endpoint",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateRegistryAclV1Cmd struct {
	RegistryId string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateRegistryAclV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/acl",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateRegistryPrivateAclV1Cmd struct {
	RegistryId string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateRegistryPrivateAclV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/private-acl",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{},
		b)
}

type ContainerRegistryUpdateReplicationV1Cmd struct {
	RegistryId string `name:"registry-id" help:"Registry ID Get registryId by ListRegistries" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *ContainerRegistryUpdateReplicationV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/container-registry/v1/registries/{registryId}/update-replication",
		map[string]string{"registryId": c.RegistryId},
		map[string]string{},
		b)
}

// ContainerRegistryCmd groups all container-registry operations.
type ContainerRegistryCmd struct {
	CheckDuplicationRegistryNameV1 ContainerRegistryCheckDuplicationRegistryNameV1Cmd `cmd:"" name:"check-duplication-registry-name-v1" help:"CheckDuplicationRegistryName"`
	CheckPrivateAclRegistrationV2  ContainerRegistryCheckPrivateAclRegistrationV2Cmd  `cmd:"" name:"check-private-acl-registration-v2" help:"Check private acl registration"`
	CheckVulnerabilityV1           ContainerRegistryCheckVulnerabilityV1Cmd           `cmd:"" name:"check-vulnerability-v1" help:"CheckVulnerability"`
	CreateRegistryV1               ContainerRegistryCreateRegistryV1Cmd               `cmd:"" name:"create-registry-v1" help:"CreateRegistry"`
	DeleteRegistryV1               ContainerRegistryDeleteRegistryV1Cmd               `cmd:"" name:"delete-registry-v1" help:"DeleteRegistry"`
	DeleteRepositoryV1             ContainerRegistryDeleteRepositoryV1Cmd             `cmd:"" name:"delete-repository-v1" help:"DeleteRepository"`
	DeleteTagV1                    ContainerRegistryDeleteTagV1Cmd                    `cmd:"" name:"delete-tag-v1" help:"DeleteTag"`
	DeleteTagsV1                   ContainerRegistryDeleteTagsV1Cmd                   `cmd:"" name:"delete-tags-v1" help:"DeleteTags"`
	DetailRegistryV1               ContainerRegistryDetailRegistryV1Cmd               `cmd:"" name:"detail-registry-v1" help:"DetailRegistry"`
	DetailRepositoryV1             ContainerRegistryDetailRepositoryV1Cmd             `cmd:"" name:"detail-repository-v1" help:"DetailRepository"`
	DetailTagManifestV1            ContainerRegistryDetailTagManifestV1Cmd            `cmd:"" name:"detail-tag-manifest-v1" help:"GetTagManifest"`
	DetailTagPackagesV1            ContainerRegistryDetailTagPackagesV1Cmd            `cmd:"" name:"detail-tag-packages-v1" help:"DetailTagPackages"`
	DetailTagSecrets               ContainerRegistryDetailTagSecretsCmd               `cmd:"" name:"detail-tag-secrets" help:"DetailTagSecrets"`
	DetailTagV1                    ContainerRegistryDetailTagV1Cmd                    `cmd:"" name:"detail-tag-v1" help:"DetailTag"`
	DetailTagVulnerabilitiesV1     ContainerRegistryDetailTagVulnerabilitiesV1Cmd     `cmd:"" name:"detail-tag-vulnerabilities-v1" help:"DetailTagVulnerabilities"`
	DownloadManifestV1             ContainerRegistryDownloadManifestV1Cmd             `cmd:"" name:"download-manifest-v1" help:"DownloadManifest"`
	ListRegistriesV1               ContainerRegistryListRegistriesV1Cmd               `cmd:"" name:"list-registries-v1" help:"ListRegistries"`
	ListRegistriesWithAuthInfoV2   ContainerRegistryListRegistriesWithAuthInfoV2Cmd   `cmd:"" name:"list-registries-with-auth-info-v2" help:"ListRegistriesWithAuthInfo"`
	ListReplicationZoneV1          ContainerRegistryListReplicationZoneV1Cmd          `cmd:"" name:"list-replication-zone-v1" help:"Retrieving the Replicable Zone List"`
	ListRepositoriesV1             ContainerRegistryListRepositoriesV1Cmd             `cmd:"" name:"list-repositories-v1" help:"ListRepositories"`
	ListTagsV1                     ContainerRegistryListTagsV1Cmd                     `cmd:"" name:"list-tags-v1" help:"ListTags"`
	UpdateAutoScanV1               ContainerRegistryUpdateAutoScanV1Cmd               `cmd:"" name:"update-auto-scan-v1" help:"UpdateAutoScan"`
	UpdateDescriptionV1            ContainerRegistryUpdateDescriptionV1Cmd            `cmd:"" name:"update-description-v1" help:"UpdateDescription"`
	UpdatePullLimitV1              ContainerRegistryUpdatePullLimitV1Cmd              `cmd:"" name:"update-pull-limit-v1" help:"UpdatePullLimit"`
	UpdateRepositoryLockV1         ContainerRegistryUpdateRepositoryLockV1Cmd         `cmd:"" name:"update-repository-lock-v1" help:"UpdateRepositoryLock"`
	UpdateTagLockV1                ContainerRegistryUpdateTagLockV1Cmd                `cmd:"" name:"update-tag-lock-v1" help:"Tag Lock/Unlock setting update"`
	UpdateLifecyclePolicyV1        ContainerRegistryUpdateLifecyclePolicyV1Cmd        `cmd:"" name:"update-lifecycle-policy-v1" help:"UpdateLifecyclePolicy"`
	UpdatePublicEndpointUseYnV1    ContainerRegistryUpdatePublicEndpointUseYnV1Cmd    `cmd:"" name:"update-public-endpoint-use-yn-v1" help:"UpdatePublicEndpointUseYn"`
	UpdateRegistryAclV1            ContainerRegistryUpdateRegistryAclV1Cmd            `cmd:"" name:"update-registry-acl-v1" help:"UpdatePublicAcl"`
	UpdateRegistryPrivateAclV1     ContainerRegistryUpdateRegistryPrivateAclV1Cmd     `cmd:"" name:"update-registry-private-acl-v1" help:"UpdatePrivateAcl"`
	UpdateReplicationV1            ContainerRegistryUpdateReplicationV1Cmd            `cmd:"" name:"update-replication-v1" help:"Replication Not Used Settings"`
}
