// Code generated by codegen. DO NOT EDIT.

package commands

type DataCatalogAddDataCatalogBlockStoragesCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogAddDataCatalogBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/block-storages",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogAttachDataCatalogSecurityGroupsCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogAttachDataCatalogSecurityGroupsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/security-groups",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogCreateDataCatalogCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogCreateDataCatalogCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs",
		map[string]string{},
		map[string]string{},
		b)
}

type DataCatalogDeleteDataCatalogCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
}

func (c *DataCatalogDeleteDataCatalogCmd) Run() error {
	return RunRequest("DELETE", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		nil)
}

type DataCatalogDetachDataCatalogSecurityGroupsCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogDetachDataCatalogSecurityGroupsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/security-groups",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogGetDataCatalogDetailCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
}

func (c *DataCatalogGetDataCatalogDetailCmd) Run() error {
	return RunRequest("GET", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		nil)
}

type DataCatalogGetDataCatalogListCmd struct {
	DataCatalogName string `name:"data-catalog-name" help:""`
	CreatedBy       string `name:"created-by" help:"Creator ID"`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *DataCatalogGetDataCatalogListCmd) Run() error {
	return RunRequest("GET", "/analytics/data-catalog/v1/data-catalogs",
		map[string]string{},
		map[string]string{"dataCatalogName": c.DataCatalogName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type DataCatalogResizeDataCatalogCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogResizeDataCatalogCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/resize",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogResizeDataCatalogBlockStoragesCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogResizeDataCatalogBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/block-storages/resize",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogRestartDataCatalogCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogRestartDataCatalogCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/restart",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogStartDataCatalogCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogStartDataCatalogCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/start",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

type DataCatalogStopDataCatalogCmd struct {
	DataCatalogId string `name:"data-catalog-id" help:"Data Catalog ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataCatalogStopDataCatalogCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/analytics/data-catalog/v1/data-catalogs/{dataCatalogId}/stop",
		map[string]string{"dataCatalogId": c.DataCatalogId},
		map[string]string{},
		b)
}

// DataCatalogCmd groups all data-catalog operations.
type DataCatalogCmd struct {
	AddDataCatalogBlockStorages     DataCatalogAddDataCatalogBlockStoragesCmd     `cmd:"" name:"add-data-catalog-block-storages" help:"Add Data Catalog Block Storages"`
	AttachDataCatalogSecurityGroups DataCatalogAttachDataCatalogSecurityGroupsCmd `cmd:"" name:"attach-data-catalog-security-groups" help:"Attach Security Groups to Data Catalog"`
	CreateDataCatalog               DataCatalogCreateDataCatalogCmd               `cmd:"" name:"create-data-catalog" help:"Create Data Catalog"`
	DeleteDataCatalog               DataCatalogDeleteDataCatalogCmd               `cmd:"" name:"delete-data-catalog" help:"Delete Data Catalog"`
	DetachDataCatalogSecurityGroups DataCatalogDetachDataCatalogSecurityGroupsCmd `cmd:"" name:"detach-data-catalog-security-groups" help:"Detach Security Groups from Data Catalog"`
	GetDataCatalogDetail            DataCatalogGetDataCatalogDetailCmd            `cmd:"" name:"get-data-catalog-detail" help:"Get Data Catalog Detail"`
	GetDataCatalogList              DataCatalogGetDataCatalogListCmd              `cmd:"" name:"get-data-catalog-list" help:"Get Data Catalog List"`
	ResizeDataCatalog               DataCatalogResizeDataCatalogCmd               `cmd:"" name:"resize-data-catalog" help:"Resize Data Catalog Servers"`
	ResizeDataCatalogBlockStorages  DataCatalogResizeDataCatalogBlockStoragesCmd  `cmd:"" name:"resize-data-catalog-block-storages" help:"Resize Data Catalog Block Storages"`
	RestartDataCatalog              DataCatalogRestartDataCatalogCmd              `cmd:"" name:"restart-data-catalog" help:"Restart Data Catalog"`
	StartDataCatalog                DataCatalogStartDataCatalogCmd                `cmd:"" name:"start-data-catalog" help:"Start Data Catalog"`
	StopDataCatalog                 DataCatalogStopDataCatalogCmd                 `cmd:"" name:"stop-data-catalog" help:"Stop Data Catalog"`
}
