// Code generated by codegen. DO NOT EDIT.

package commands

type DataOpsCreateDataOpsCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataOpsCreateDataOpsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/data-ops/v2/data-ops",
		map[string]string{},
		map[string]string{},
		b)
}

type DataOpsCreateDataOpsServiceCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataOpsCreateDataOpsServiceCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/data-ops/v2/data-ops-services",
		map[string]string{},
		map[string]string{},
		b)
}

type DataOpsDeleteDataOpsCmd struct {
	DataOpsId string `name:"data-ops-id" help:"Data Ops Id" required:""`
}

func (c *DataOpsDeleteDataOpsCmd) Run() error {
	return RunRequest("DELETE", "/data-ops/v1/data-ops/{dataOpsId}",
		map[string]string{"dataOpsId": c.DataOpsId},
		map[string]string{},
		nil)
}

type DataOpsDeleteDataOpsServiceCmd struct {
	DataOpsServiceId string `name:"data-ops-service-id" help:"Data Ops Service Id" required:""`
}

func (c *DataOpsDeleteDataOpsServiceCmd) Run() error {
	return RunRequest("DELETE", "/data-ops/v1/data-ops-services/{dataOpsServiceId}",
		map[string]string{"dataOpsServiceId": c.DataOpsServiceId},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsCmd struct {
	DataOpsId string `name:"data-ops-id" help:"Data Ops Id" required:""`
}

func (c *DataOpsGetDataOpsCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops/{dataOpsId}",
		map[string]string{"dataOpsId": c.DataOpsId},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsCheckDuplicationCmd struct {
	DataOpsName string `name:"data-ops-name" help:"Data Ops name" required:""`
}

func (c *DataOpsGetDataOpsCheckDuplicationCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops/{dataOpsName}/check-duplication",
		map[string]string{"dataOpsName": c.DataOpsName},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsImagesCmd struct {
}

func (c *DataOpsGetDataOpsImagesCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops/image-versions",
		map[string]string{},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsListCmd struct {
	ClusterName string `name:"cluster-name" help:"Cluster name"`
	DataOpsName string `name:"data-ops-name" help:"Data Ops name"`
	State       string `name:"state" help:"State"`
	Version     string `name:"version" help:"Version"`
	CreatedBy   string `name:"created-by" help:"Creator"`
	Page        string `name:"page" help:"Page (Default : 0)"`
	Size        string `name:"size" help:"The number of items per page (1~10000)"`
	Sort        string `name:"sort" help:"Field name and sort order (Ex. name:asc)"`
}

func (c *DataOpsGetDataOpsListCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops",
		map[string]string{},
		map[string]string{"clusterName": c.ClusterName, "dataOpsName": c.DataOpsName, "state": c.State, "version": c.Version, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type DataOpsGetDataOpsServiceCmd struct {
	DataOpsServiceId string `name:"data-ops-service-id" help:"Data Ops Service Id" required:""`
}

func (c *DataOpsGetDataOpsServiceCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops-services/{dataOpsServiceId}",
		map[string]string{"dataOpsServiceId": c.DataOpsServiceId},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsServiceCheckDuplicationCmd struct {
	DataOpsServiceName string `name:"data-ops-service-name" help:"Data Ops Service Name" required:""`
}

func (c *DataOpsGetDataOpsServiceCheckDuplicationCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops-services/{dataOpsServiceName}/check-duplication",
		map[string]string{"dataOpsServiceName": c.DataOpsServiceName},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsServiceListCmd struct {
	DataOpsName        string `name:"data-ops-name" help:"Data Ops name"`
	DataOpsServiceName string `name:"data-ops-service-name" help:"Data Ops Service Name"`
	State              string `name:"state" help:"State"`
	CreatedBy          string `name:"created-by" help:"Creator"`
	Page               string `name:"page" help:"Page (Default : 0)"`
	Size               string `name:"size" help:"The number of items per page (1~10000)"`
	Sort               string `name:"sort" help:"Field name and sort order (Ex. name:asc)"`
}

func (c *DataOpsGetDataOpsServiceListCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops-services",
		map[string]string{},
		map[string]string{"dataOpsName": c.DataOpsName, "dataOpsServiceName": c.DataOpsServiceName, "state": c.State, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type DataOpsGetDataOpsServiceSubVersionsCmd struct {
	DataOpsId string `name:"data-ops-id" help:"Data Ops Id" required:""`
}

func (c *DataOpsGetDataOpsServiceSubVersionsCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/data-ops-services/data-ops/{dataOpsId}/sub-versions",
		map[string]string{"dataOpsId": c.DataOpsId},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsServiceValidateResourcesCmd struct {
	ClusterId string `name:"cluster-id" help:"Cluster ID" required:""`
	Cpu       string `name:"cpu" help:"CPU(vCore)" required:""`
	Memory    string `name:"memory" help:"Memory(GB)" required:""`
}

func (c *DataOpsGetDataOpsServiceValidateResourcesCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/clusters/{clusterId}/cpu/{cpu}/memory/{memory}/validate-resources",
		map[string]string{"clusterId": c.ClusterId, "cpu": c.Cpu, "memory": c.Memory},
		map[string]string{},
		nil)
}

type DataOpsGetDataOpsValidateResourcesCmd struct {
	ClusterId string `name:"cluster-id" help:"Cluster ID" required:""`
}

func (c *DataOpsGetDataOpsValidateResourcesCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/clusters/{clusterId}/validate-resources",
		map[string]string{"clusterId": c.ClusterId},
		map[string]string{},
		nil)
}

type DataOpsGetIngressControllerListCmd struct {
	ClusterId string `name:"cluster-id" help:"Cluster ID" required:""`
}

func (c *DataOpsGetIngressControllerListCmd) Run() error {
	return RunRequest("GET", "/data-ops/v1/clusters/{clusterId}/ingress-controllers",
		map[string]string{"clusterId": c.ClusterId},
		map[string]string{},
		nil)
}

type DataOpsUpdateDataOpsCmd struct {
	DataOpsId string `name:"data-ops-id" help:"Data Ops Id" required:""`
	Body      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataOpsUpdateDataOpsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/data-ops/v1/data-ops/{dataOpsId}",
		map[string]string{"dataOpsId": c.DataOpsId},
		map[string]string{},
		b)
}

type DataOpsUpdateDataOpsServiceCmd struct {
	DataOpsServiceId string `name:"data-ops-service-id" help:"Data Ops Service Id" required:""`
	Body             string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DataOpsUpdateDataOpsServiceCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/data-ops/v1/data-ops-services/{dataOpsServiceId}",
		map[string]string{"dataOpsServiceId": c.DataOpsServiceId},
		map[string]string{},
		b)
}

// DataOpsCmd groups all data-ops operations.
type DataOpsCmd struct {
	CreateDataOps                      DataOpsCreateDataOpsCmd                      `cmd:"" name:"create-data-ops" help:"Create Data Ops"`
	CreateDataOpsService               DataOpsCreateDataOpsServiceCmd               `cmd:"" name:"create-data-ops-service" help:"Create Data Ops Service"`
	DeleteDataOps                      DataOpsDeleteDataOpsCmd                      `cmd:"" name:"delete-data-ops" help:"Delete Data Ops"`
	DeleteDataOpsService               DataOpsDeleteDataOpsServiceCmd               `cmd:"" name:"delete-data-ops-service" help:"Delete Data Ops Service"`
	GetDataOps                         DataOpsGetDataOpsCmd                         `cmd:"" name:"get-data-ops" help:"Get Data Ops details"`
	GetDataOpsCheckDuplication         DataOpsGetDataOpsCheckDuplicationCmd         `cmd:"" name:"get-data-ops-check-duplication" help:"Check Duplication Data Ops Name"`
	GetDataOpsImages                   DataOpsGetDataOpsImagesCmd                   `cmd:"" name:"get-data-ops-images" help:"Get List of Data Ops Images"`
	GetDataOpsList                     DataOpsGetDataOpsListCmd                     `cmd:"" name:"get-data-ops-list" help:"Get List of Data Ops"`
	GetDataOpsService                  DataOpsGetDataOpsServiceCmd                  `cmd:"" name:"get-data-ops-service" help:"Get Data Ops Service details"`
	GetDataOpsServiceCheckDuplication  DataOpsGetDataOpsServiceCheckDuplicationCmd  `cmd:"" name:"get-data-ops-service-check-duplication" help:"Check Duplication Data Ops Service Name"`
	GetDataOpsServiceList              DataOpsGetDataOpsServiceListCmd              `cmd:"" name:"get-data-ops-service-list" help:"Get List of Data Ops Service"`
	GetDataOpsServiceSubVersions       DataOpsGetDataOpsServiceSubVersionsCmd       `cmd:"" name:"get-data-ops-service-sub-versions" help:"Get List of Data Ops Service Versions"`
	GetDataOpsServiceValidateResources DataOpsGetDataOpsServiceValidateResourcesCmd `cmd:"" name:"get-data-ops-service-validate-resources" help:"Validate Cluster Resource Size for Data Ops Service"`
	GetDataOpsValidateResources        DataOpsGetDataOpsValidateResourcesCmd        `cmd:"" name:"get-data-ops-validate-resources" help:"Validate Cluster Resource Size for Data Ops"`
	GetIngressControllerList           DataOpsGetIngressControllerListCmd           `cmd:"" name:"get-ingress-controller-list" help:"Get List of Ingress Controllers"`
	UpdateDataOps                      DataOpsUpdateDataOpsCmd                      `cmd:"" name:"update-data-ops" help:"Update Data Ops"`
	UpdateDataOpsService               DataOpsUpdateDataOpsServiceCmd               `cmd:"" name:"update-data-ops-service" help:"Update Data Ops Service"`
}
