// Code generated by codegen. DO NOT EDIT.

package commands

type DevopsCodeCheckCodeTenantDeletableV1Cmd struct {
	TenantId string `name:"tenant-id" help:"Tenant Id tenantId is obtained through DevOps Code List" required:""`
}

func (c *DevopsCodeCheckCodeTenantDeletableV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/codes/{tenantId}/check-deletable",
		map[string]string{"tenantId": c.TenantId},
		map[string]string{},
		nil)
}

type DevopsCodeCheckCodeTenantUsableV1Cmd struct {
	TenantCode string `name:"tenant-code" help:"Tenant Code" required:""`
}

func (c *DevopsCodeCheckCodeTenantUsableV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/codes/check-duplication",
		map[string]string{},
		map[string]string{"tenantCode": c.TenantCode},
		nil)
}

type DevopsCodeCreateDevOpsCodeV1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DevopsCodeCreateDevOpsCodeV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/devops/v1/codes",
		map[string]string{},
		map[string]string{},
		b)
}

type DevopsCodeDeleteDevOpsCodeV1Cmd struct {
	TenantId string `name:"tenant-id" help:"Tenant Id tenantId is obtained through DevOps Code List" required:""`
}

func (c *DevopsCodeDeleteDevOpsCodeV1Cmd) Run() error {
	return RunRequest("DELETE", "/devops/v1/codes/{tenantId}",
		map[string]string{"tenantId": c.TenantId},
		map[string]string{},
		nil)
}

type DevopsCodeDetailDevOpsCodeV1Cmd struct {
	TenantId string `name:"tenant-id" help:"Tenant Id tenantId is obtained through DevOps Code List" required:""`
}

func (c *DevopsCodeDetailDevOpsCodeV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/codes/{tenantId}",
		map[string]string{"tenantId": c.TenantId},
		map[string]string{},
		nil)
}

type DevopsCodeListDevOpsCodesV1Cmd struct {
	Page string `name:"page" help:"page"`
	Size string `name:"size" help:"size"`
}

func (c *DevopsCodeListDevOpsCodesV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/codes",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size},
		nil)
}

// DevopsCodeCmd groups all devops-code operations.
type DevopsCodeCmd struct {
	CheckCodeTenantDeletableV1 DevopsCodeCheckCodeTenantDeletableV1Cmd `cmd:"" name:"check-code-tenant-deletable-v1" help:"Check Deletable DevOps Code Tenant"`
	CheckCodeTenantUsableV1    DevopsCodeCheckCodeTenantUsableV1Cmd    `cmd:"" name:"check-code-tenant-usable-v1" help:"Check DevOps Code Tenant Duplication"`
	CreateDevOpsCodeV1         DevopsCodeCreateDevOpsCodeV1Cmd         `cmd:"" name:"create-dev-ops-code-v1" help:"Create DevOps Code"`
	DeleteDevOpsCodeV1         DevopsCodeDeleteDevOpsCodeV1Cmd         `cmd:"" name:"delete-dev-ops-code-v1" help:"Delete DevOps Code"`
	DetailDevOpsCodeV1         DevopsCodeDetailDevOpsCodeV1Cmd         `cmd:"" name:"detail-dev-ops-code-v1" help:"Detail DevOps Code"`
	ListDevOpsCodesV1          DevopsCodeListDevOpsCodesV1Cmd          `cmd:"" name:"list-dev-ops-codes-v1" help:"DevOps Code List"`
}
