// Code generated by codegen. DO NOT EDIT.

package commands

type DevopsCheckTenantDeletableV1Cmd struct {
	TenantId string `name:"tenant-id" help:"Tenant Id" required:""`
}

func (c *DevopsCheckTenantDeletableV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/services/{tenantId}/check-deletable",
		map[string]string{"tenantId": c.TenantId},
		map[string]string{},
		nil)
}

type DevopsCheckTenantDuplicationV1Cmd struct {
	TenantCode string `name:"tenant-code" help:"Tenant Code"`
	TenantName string `name:"tenant-name" help:"Tenant Name"`
}

func (c *DevopsCheckTenantDuplicationV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/services/check-duplication",
		map[string]string{},
		map[string]string{"tenantCode": c.TenantCode, "tenantName": c.TenantName},
		nil)
}

type DevopsCreateDevOpsServiceV1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DevopsCreateDevOpsServiceV1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/devops/v1/services",
		map[string]string{},
		map[string]string{},
		b)
}

type DevopsDeleteDevOpsServiceV1Cmd struct {
	TenantId string `name:"tenant-id" help:"Tenant Id" required:""`
}

func (c *DevopsDeleteDevOpsServiceV1Cmd) Run() error {
	return RunRequest("DELETE", "/devops/v1/services/{tenantId}",
		map[string]string{"tenantId": c.TenantId},
		map[string]string{},
		nil)
}

type DevopsDetailDevOpsServiceV1Cmd struct {
	TenantId string `name:"tenant-id" help:"Tenant Id" required:""`
}

func (c *DevopsDetailDevOpsServiceV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/services/{tenantId}",
		map[string]string{"tenantId": c.TenantId},
		map[string]string{},
		nil)
}

type DevopsListDevOpsServicesV1Cmd struct {
	Page string `name:"page" help:"page"`
	Size string `name:"size" help:"size"`
}

func (c *DevopsListDevOpsServicesV1Cmd) Run() error {
	return RunRequest("GET", "/devops/v1/services",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size},
		nil)
}

// DevopsCmd groups all devops operations.
type DevopsCmd struct {
	CheckTenantDeletableV1   DevopsCheckTenantDeletableV1Cmd   `cmd:"" name:"check-tenant-deletable-v1" help:"Check Deletable DevOps Service Tenant"`
	CheckTenantDuplicationV1 DevopsCheckTenantDuplicationV1Cmd `cmd:"" name:"check-tenant-duplication-v1" help:"Check DevOps Service Tenant Duplication"`
	CreateDevOpsServiceV1    DevopsCreateDevOpsServiceV1Cmd    `cmd:"" name:"create-dev-ops-service-v1" help:"Create DevOps Service"`
	DeleteDevOpsServiceV1    DevopsDeleteDevOpsServiceV1Cmd    `cmd:"" name:"delete-dev-ops-service-v1" help:"Delete DevOps Service"`
	DetailDevOpsServiceV1    DevopsDetailDevOpsServiceV1Cmd    `cmd:"" name:"detail-dev-ops-service-v1" help:"Detail DevOps Service"`
	ListDevOpsServicesV1     DevopsListDevOpsServicesV1Cmd     `cmd:"" name:"list-dev-ops-services-v1" help:"DevOps Service List"`
}
