// Code generated by codegen. DO NOT EDIT.

package commands

type DirectConnectCreateDirectConnectConnectionCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DirectConnectCreateDirectConnectConnectionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/direct-connect/v2/direct-connect-connections",
		map[string]string{},
		map[string]string{},
		b)
}

type DirectConnectCreateDirectConnect1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DirectConnectCreateDirectConnect1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/direct-connect/v3/direct-connects",
		map[string]string{},
		map[string]string{},
		b)
}

type DirectConnectDeleteDirectConnectCmd struct {
	DirectConnectId string `name:"direct-connect-id" help:"Direct Connect ID" required:""`
}

func (c *DirectConnectDeleteDirectConnectCmd) Run() error {
	return RunRequest("DELETE", "/direct-connect/v2/direct-connects/{directConnectId}",
		map[string]string{"directConnectId": c.DirectConnectId},
		map[string]string{},
		nil)
}

type DirectConnectDeleteDirectConnectConnectionCmd struct {
	DirectConnectConnectionId string `name:"direct-connect-connection-id" help:"VPC-Direct Connect Connection ID" required:""`
}

func (c *DirectConnectDeleteDirectConnectConnectionCmd) Run() error {
	return RunRequest("DELETE", "/direct-connect/v2/direct-connect-connections/{directConnectConnectionId}",
		map[string]string{"directConnectConnectionId": c.DirectConnectConnectionId},
		map[string]string{},
		nil)
}

type DirectConnectDetailDirectConnectCmd struct {
	DirectConnectId string `name:"direct-connect-id" help:"Direct Connect ID" required:""`
}

func (c *DirectConnectDetailDirectConnectCmd) Run() error {
	return RunRequest("GET", "/direct-connect/v2/direct-connects/{directConnectId}",
		map[string]string{"directConnectId": c.DirectConnectId},
		map[string]string{},
		nil)
}

type DirectConnectDetailDirectConnectConnectionsCmd struct {
	DirectConnectConnectionId string `name:"direct-connect-connection-id" help:"VPC-Direct Connect Connection ID" required:""`
}

func (c *DirectConnectDetailDirectConnectConnectionsCmd) Run() error {
	return RunRequest("GET", "/direct-connect/v2/direct-connect-connections/{directConnectConnectionId}",
		map[string]string{"directConnectConnectionId": c.DirectConnectConnectionId},
		map[string]string{},
		nil)
}

type DirectConnectListDirectConnectConnectionsCmd struct {
	ApproverVpcId                 string `name:"approver-vpc-id" help:"Approver VPC ID vpcId is obtained through Get List of VPCs"`
	DirectConnectConnectionName   string `name:"direct-connect-connection-name" help:"VPC-Direct Connect Connection Name"`
	DirectConnectConnectionStates string `name:"direct-connect-connection-states" help:"VPC-Direct Connect Connection States"`
	RequesterDirectConnectId      string `name:"requester-direct-connect-id" help:"Requester Direct Connect ID"`
	CreatedBy                     string `name:"created-by" help:"Create User ID"`
	Page                          string `name:"page" help:"Request page number"`
	Size                          string `name:"size" help:"Number of items in the Page"`
	Sort                          string `name:"sort" help:"Sort condition"`
}

func (c *DirectConnectListDirectConnectConnectionsCmd) Run() error {
	return RunRequest("GET", "/direct-connect/v2/direct-connect-connections",
		map[string]string{},
		map[string]string{"approverVpcId": c.ApproverVpcId, "directConnectConnectionName": c.DirectConnectConnectionName, "directConnectConnectionStates": c.DirectConnectConnectionStates, "requesterDirectConnectId": c.RequesterDirectConnectId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type DirectConnectListDirectConnectsCmd struct {
	DirectConnectId   string `name:"direct-connect-id" help:"Direct Connect ID"`
	DirectConnectName string `name:"direct-connect-name" help:"Direct Connect Name"`
	CreatedBy         string `name:"created-by" help:"Create User ID"`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *DirectConnectListDirectConnectsCmd) Run() error {
	return RunRequest("GET", "/direct-connect/v2/direct-connects",
		map[string]string{},
		map[string]string{"directConnectId": c.DirectConnectId, "directConnectName": c.DirectConnectName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type DirectConnectUpdateDirectConnectCmd struct {
	DirectConnectId string `name:"direct-connect-id" help:"Direct Connect ID" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DirectConnectUpdateDirectConnectCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/direct-connect/v2/direct-connects/{directConnectId}/description",
		map[string]string{"directConnectId": c.DirectConnectId},
		map[string]string{},
		b)
}

type DirectConnectUpdateDirectConnectConnectionDescriptionCmd struct {
	DirectConnectConnectionId string `name:"direct-connect-connection-id" help:"VPC-Direct Connect Connection ID" required:""`
	Body                      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *DirectConnectUpdateDirectConnectConnectionDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/direct-connect/v2/direct-connect-connections/{directConnectConnectionId}/description",
		map[string]string{"directConnectConnectionId": c.DirectConnectConnectionId},
		map[string]string{},
		b)
}

// DirectConnectCmd groups all direct-connect operations.
type DirectConnectCmd struct {
	CreateDirectConnectConnection            DirectConnectCreateDirectConnectConnectionCmd            `cmd:"" name:"create-direct-connect-connection" help:"Create VPC-Direct Connect Connection"`
	CreateDirectConnect1                     DirectConnectCreateDirectConnect1Cmd                     `cmd:"" name:"create-direct-connect_1" help:"Create Direct Connect"`
	DeleteDirectConnect                      DirectConnectDeleteDirectConnectCmd                      `cmd:"" name:"delete-direct-connect" help:"Delete Direct Connect"`
	DeleteDirectConnectConnection            DirectConnectDeleteDirectConnectConnectionCmd            `cmd:"" name:"delete-direct-connect-connection" help:"Delete VPC-Direct Connect Connection"`
	DetailDirectConnect                      DirectConnectDetailDirectConnectCmd                      `cmd:"" name:"detail-direct-connect" help:"Get Direct Connect details"`
	DetailDirectConnectConnections           DirectConnectDetailDirectConnectConnectionsCmd           `cmd:"" name:"detail-direct-connect-connections" help:"Get VPC-Direct Connect Connection details"`
	ListDirectConnectConnections             DirectConnectListDirectConnectConnectionsCmd             `cmd:"" name:"list-direct-connect-connections" help:"Get List of VPC-Direct Connect Connections"`
	ListDirectConnects                       DirectConnectListDirectConnectsCmd                       `cmd:"" name:"list-direct-connects" help:"Get List of Direct Connects"`
	UpdateDirectConnect                      DirectConnectUpdateDirectConnectCmd                      `cmd:"" name:"update-direct-connect" help:"Modify Direct Connect Description"`
	UpdateDirectConnectConnectionDescription DirectConnectUpdateDirectConnectConnectionDescriptionCmd `cmd:"" name:"update-direct-connect-connection-description" help:"Modify VPC-Direct Connect Connection Description"`
}
