// Code generated by codegen. DO NOT EDIT.

package commands

type EpasAddEpasClusterBlockStoragesCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasAddEpasClusterBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/block-storages",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasAttachEpasClusterSecurityGroupCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasAttachEpasClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/security-groups/attach",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasCreateEpasClusterCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasCreateEpasClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas",
		map[string]string{},
		map[string]string{},
		b)
}

type EpasCreateEpasClusterFullBackupConfigCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasCreateEpasClusterFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/full-backups",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasDeleteEpasClusterCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
}

func (c *EpasDeleteEpasClusterCmd) Run() error {
	return RunRequest("DELETE", "/database/epas/v1/epas/{epasClusterId}",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		nil)
}

type EpasDeleteEpasClusterFullBackupConfigCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
}

func (c *EpasDeleteEpasClusterFullBackupConfigCmd) Run() error {
	return RunRequest("DELETE", "/database/epas/v1/epas/{epasClusterId}/full-backups",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		nil)
}

type EpasDetachEpasClusterSecurityGroupCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasDetachEpasClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/security-groups/detach",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasDetailEpasClusterCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
}

func (c *EpasDetailEpasClusterCmd) Run() error {
	return RunRequest("GET", "/database/epas/v1/epas/{epasClusterId}",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		nil)
}

type EpasListEpasClustersCmd struct {
	EpasClusterName string `name:"epas-cluster-name" help:"EPAS cluster name"`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *EpasListEpasClustersCmd) Run() error {
	return RunRequest("GET", "/database/epas/v1/epas",
		map[string]string{},
		map[string]string{"epasClusterName": c.EpasClusterName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type EpasModifyEpasClusterFullBackupConfigCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasModifyEpasClusterFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/database/epas/v1/epas/{epasClusterId}/full-backups",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasResizeEpasClusterBlockStoragesCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasResizeEpasClusterBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/block-storages/resize",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasResizeEpasClusterVirtualServersCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasResizeEpasClusterVirtualServersCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/virtual-servers/resize",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasRestartEpasClusterCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasRestartEpasClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/restart",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasStartEpasClusterCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasStartEpasClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/start",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

type EpasStopEpasClusterCmd struct {
	EpasClusterId string `name:"epas-cluster-id" help:"EPAS cluster ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *EpasStopEpasClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/epas/v1/epas/{epasClusterId}/stop",
		map[string]string{"epasClusterId": c.EpasClusterId},
		map[string]string{},
		b)
}

// EpasCmd groups all epas operations.
type EpasCmd struct {
	AddEpasClusterBlockStorages       EpasAddEpasClusterBlockStoragesCmd       `cmd:"" name:"add-epas-cluster-block-storages" help:"Add EPAS cluster block storages"`
	AttachEpasClusterSecurityGroup    EpasAttachEpasClusterSecurityGroupCmd    `cmd:"" name:"attach-epas-cluster-security-group" help:"Attach Security Group to EPAS cluster"`
	CreateEpasCluster                 EpasCreateEpasClusterCmd                 `cmd:"" name:"create-epas-cluster" help:"Create EPAS cluster"`
	CreateEpasClusterFullBackupConfig EpasCreateEpasClusterFullBackupConfigCmd `cmd:"" name:"create-epas-cluster-full-backup-config" help:"Create EPAS cluster full backup config"`
	DeleteEpasCluster                 EpasDeleteEpasClusterCmd                 `cmd:"" name:"delete-epas-cluster" help:"Delete EPAS cluster"`
	DeleteEpasClusterFullBackupConfig EpasDeleteEpasClusterFullBackupConfigCmd `cmd:"" name:"delete-epas-cluster-full-backup-config" help:"Delete EPAS cluster full backup config"`
	DetachEpasClusterSecurityGroup    EpasDetachEpasClusterSecurityGroupCmd    `cmd:"" name:"detach-epas-cluster-security-group" help:"Detach Security Group to EPAS cluster"`
	DetailEpasCluster                 EpasDetailEpasClusterCmd                 `cmd:"" name:"detail-epas-cluster" help:"Detail EPAS cluster"`
	ListEpasClusters                  EpasListEpasClustersCmd                  `cmd:"" name:"list-epas-clusters" help:"List EPAS cluster"`
	ModifyEpasClusterFullBackupConfig EpasModifyEpasClusterFullBackupConfigCmd `cmd:"" name:"modify-epas-cluster-full-backup-config" help:"Modify EPAS cluster full backup config"`
	ResizeEpasClusterBlockStorages    EpasResizeEpasClusterBlockStoragesCmd    `cmd:"" name:"resize-epas-cluster-block-storages" help:"Resize EPAS cluster block storages"`
	ResizeEpasClusterVirtualServers   EpasResizeEpasClusterVirtualServersCmd   `cmd:"" name:"resize-epas-cluster-virtual-servers" help:"Resize EPAS cluster virtual servers"`
	RestartEpasCluster                EpasRestartEpasClusterCmd                `cmd:"" name:"restart-epas-cluster" help:"Restart EPAS cluster"`
	StartEpasCluster                  EpasStartEpasClusterCmd                  `cmd:"" name:"start-epas-cluster" help:"Start EPAS cluster"`
	StopEpasCluster                   EpasStopEpasClusterCmd                   `cmd:"" name:"stop-epas-cluster" help:"Stop EPAS cluster"`
}
