// Code generated by codegen. DO NOT EDIT.

package commands

type FaceRecognitionCompareFacesCmd struct {
	FaceRecognitionId string `name:"face-recognition-id" help:"Face Recognition ID Face Recognition ID is obtained through Get list of Face Recognition" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FaceRecognitionCompareFacesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vision-api/v1/face-recognitions/{faceRecognitionId}/compare-faces",
		map[string]string{"faceRecognitionId": c.FaceRecognitionId},
		map[string]string{},
		b)
}

type FaceRecognitionCreateFaceRecognitionCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FaceRecognitionCreateFaceRecognitionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vision-api/v1/face-recognitions",
		map[string]string{},
		map[string]string{},
		b)
}

type FaceRecognitionDeleteFaceRecognitionCmd struct {
	FaceRecognitionId string `name:"face-recognition-id" help:"Face Recognition ID Face Recognition ID is obtained through Get list of Face Recognition" required:""`
}

func (c *FaceRecognitionDeleteFaceRecognitionCmd) Run() error {
	return RunRequest("DELETE", "/vision-api/v1/face-recognitions/{faceRecognitionId}",
		map[string]string{"faceRecognitionId": c.FaceRecognitionId},
		map[string]string{},
		nil)
}

type FaceRecognitionDetailFaceRecognitionCmd struct {
	FaceRecognitionId string `name:"face-recognition-id" help:"Face Recognition ID Face Recognition ID is obtained through Get list of Face Recognition" required:""`
}

func (c *FaceRecognitionDetailFaceRecognitionCmd) Run() error {
	return RunRequest("GET", "/vision-api/v1/face-recognitions/{faceRecognitionId}",
		map[string]string{"faceRecognitionId": c.FaceRecognitionId},
		map[string]string{},
		nil)
}

type FaceRecognitionDetectFacesCmd struct {
	FaceRecognitionId string `name:"face-recognition-id" help:"Face Recognition ID Face Recognition ID is obtained through Get list of Face Recognition" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FaceRecognitionDetectFacesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vision-api/v1/face-recognitions/{faceRecognitionId}/detect-faces",
		map[string]string{"faceRecognitionId": c.FaceRecognitionId},
		map[string]string{},
		b)
}

type FaceRecognitionListFaceRecognitionsCmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *FaceRecognitionListFaceRecognitionsCmd) Run() error {
	return RunRequest("GET", "/vision-api/v1/face-recognitions",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type FaceRecognitionUpdateFaceRecognitionDescriptionCmd struct {
	FaceRecognitionId string `name:"face-recognition-id" help:"Face Recognition ID Face Recognition ID is obtained through Get list of Face Recognition" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FaceRecognitionUpdateFaceRecognitionDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/vision-api/v1/face-recognitions/{faceRecognitionId}/description",
		map[string]string{"faceRecognitionId": c.FaceRecognitionId},
		map[string]string{},
		b)
}

// FaceRecognitionCmd groups all face-recognition operations.
type FaceRecognitionCmd struct {
	CompareFaces                     FaceRecognitionCompareFacesCmd                     `cmd:"" name:"compare-faces" help:"Compare faces"`
	CreateFaceRecognition            FaceRecognitionCreateFaceRecognitionCmd            `cmd:"" name:"create-face-recognition" help:"Create Face Recognition"`
	DeleteFaceRecognition            FaceRecognitionDeleteFaceRecognitionCmd            `cmd:"" name:"delete-face-recognition" help:"Delete Face Recognition"`
	DetailFaceRecognition            FaceRecognitionDetailFaceRecognitionCmd            `cmd:"" name:"detail-face-recognition" help:"Get Face Recognition details"`
	DetectFaces                      FaceRecognitionDetectFacesCmd                      `cmd:"" name:"detect-faces" help:"Detect faces"`
	ListFaceRecognitions             FaceRecognitionListFaceRecognitionsCmd             `cmd:"" name:"list-face-recognitions" help:"Get list of Face Recognition"`
	UpdateFaceRecognitionDescription FaceRecognitionUpdateFaceRecognitionDescriptionCmd `cmd:"" name:"update-face-recognition-description" help:"Update Face Recognition description"`
}
