// Code generated by codegen. DO NOT EDIT.

package commands

type FileStorageVmCheckFileStorageDrAvailableRegionV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmCheckFileStorageDrAvailableRegionV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/dr/{fileStorageId}/region",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmCheckFileStorageDuplicationV2Cmd struct {
	CifsId          string `name:"cifs-id" help:"CIFS ID cifsId is obtained through Query File Storage details"`
	FileStorageName string `name:"file-storage-name" help:"File Storage Name"`
	ServiceZoneId   string `name:"service-zone-id" help:"Service Zone ID serviceZoneId is obtained through View Project Details" required:""`
}

func (c *FileStorageVmCheckFileStorageDuplicationV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/check-duplication",
		map[string]string{},
		map[string]string{"cifsId": c.CifsId, "fileStorageName": c.FileStorageName, "serviceZoneId": c.ServiceZoneId},
		nil)
}

type FileStorageVmCheckMultiRegionV2Cmd struct {
	ServiceZoneId string `name:"service-zone-id" help:"Service Zone ID serviceZoneId is obtained through View Project Details" required:""`
}

func (c *FileStorageVmCheckMultiRegionV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/check-multi-region",
		map[string]string{},
		map[string]string{"serviceZoneId": c.ServiceZoneId},
		nil)
}

type FileStorageVmCreateFileStorageDrV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmCreateFileStorageDrV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v2/storages/dr/{fileStorageId}",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmCreateFileStorageSnapshotScheduleV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmCreateFileStorageSnapshotScheduleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v2/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmCreateFileStorageSnapshotV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmCreateFileStorageSnapshotV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v2/storages/{fileStorageId}/snapshots",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmDeleteFileStorageDrRelationV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmDeleteFileStorageDrRelationV2Cmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v2/storages/dr/{fileStorageId}/relation",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmDeleteFileStorageSnapshotScheduleV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmDeleteFileStorageSnapshotScheduleV2Cmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v2/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmDeleteFileStorageSnapshotV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	SnapshotId    string `name:"snapshot-id" help:"Snapshot ID" required:""`
}

func (c *FileStorageVmDeleteFileStorageSnapshotV2Cmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v2/storages/{fileStorageId}/snapshots/{snapshotId}",
		map[string]string{"fileStorageId": c.FileStorageId, "snapshotId": c.SnapshotId},
		map[string]string{},
		nil)
}

type FileStorageVmDeleteFileStorageV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmDeleteFileStorageV2Cmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v2/storages/{fileStorageId}",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmDetailFileStorageV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmDetailFileStorageV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/{fileStorageId}",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmGetFileStorageDrStateV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	IsDrOrigin    string `name:"is-dr-origin" help:"Original: Y ,DR: N"`
}

func (c *FileStorageVmGetFileStorageDrStateV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/dr/{fileStorageId}/state",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{"isDrOrigin": c.IsDrOrigin},
		nil)
}

type FileStorageVmIncreaseFileStorageCapacityV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmIncreaseFileStorageCapacityV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v2/storages/{fileStorageId}/capacity",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmLinkInstanceToFileStorageV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmLinkInstanceToFileStorageV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v2/storages/{fileStorageId}/instances/link",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmListFileStorageSnapshotsV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmListFileStorageSnapshotsV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/{fileStorageId}/snapshots",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmListFileStoragesV2Cmd struct {
	BlockId             string `name:"block-id" help:"Block Id"`
	FileStorageId       string `name:"file-storage-id" help:"File Storage ID"`
	FileStorageName     string `name:"file-storage-name" help:"File Storage Name"`
	FileStorageProtocol string `name:"file-storage-protocol" help:"File Storage Protocol"`
	FileStorageState    string `name:"file-storage-state" help:"File Storage State"`
	FileStorageStates   string `name:"file-storage-states" help:"File Storage State"`
	ServiceZoneId       string `name:"service-zone-id" help:"Service Zone ID serviceZoneId is obtained through View Project Details"`
	CreatedBy           string `name:"created-by" help:"creator"`
	Page                string `name:"page" help:"Request page number"`
	Size                string `name:"size" help:"Number of items in the Page"`
	Sort                string `name:"sort" help:"Sort condition"`
}

func (c *FileStorageVmListFileStoragesV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages",
		map[string]string{},
		map[string]string{"blockId": c.BlockId, "fileStorageId": c.FileStorageId, "fileStorageName": c.FileStorageName, "fileStorageProtocol": c.FileStorageProtocol, "fileStorageState": c.FileStorageState, "fileStorageStates": c.FileStorageStates, "serviceZoneId": c.ServiceZoneId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type FileStorageVmRestoreFileStorageSnapshotV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	SnapshotId    string `name:"snapshot-id" help:"Snapshot ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmRestoreFileStorageSnapshotV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v2/storages/{fileStorageId}/snapshots/{snapshotId}/restore",
		map[string]string{"fileStorageId": c.FileStorageId, "snapshotId": c.SnapshotId},
		map[string]string{},
		b)
}

type FileStorageVmSearchFileStorageLinkMaxCountV2Cmd struct {
}

func (c *FileStorageVmSearchFileStorageLinkMaxCountV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/instances/link-max-count",
		map[string]string{},
		map[string]string{},
		nil)
}

type FileStorageVmSearchFileStorageSnapshotScheduleV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageVmSearchFileStorageSnapshotScheduleV2Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v2/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageVmUpdateFileStorageDrPolicyV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmUpdateFileStorageDrPolicyV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v2/storages/dr/{fileStorageId}/policy",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmUpdateFileStorageDrScheduleV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmUpdateFileStorageDrScheduleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v2/storages/dr/{fileStorageId}/schedule",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmUpdateFileStorageSnapshotCapacityV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmUpdateFileStorageSnapshotCapacityV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v2/storages/{fileStorageId}/snapshots/capacity",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageVmUpdateFileStorageSnapshotScheduleV2Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageVmUpdateFileStorageSnapshotScheduleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v2/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

// FileStorageVmCmd groups all file-storage-vm operations.
type FileStorageVmCmd struct {
	CheckFileStorageDrAvailableRegionV2 FileStorageVmCheckFileStorageDrAvailableRegionV2Cmd `cmd:"" name:"check-file-storage-dr-available-region-v2" help:"Search File Storage DR Available Region"`
	CheckFileStorageDuplicationV2       FileStorageVmCheckFileStorageDuplicationV2Cmd       `cmd:"" name:"check-file-storage-duplication-v2" help:"Check File Storage duplication"`
	CheckMultiRegionV2                  FileStorageVmCheckMultiRegionV2Cmd                  `cmd:"" name:"check-multi-region-v2" help:"Check Multi Region In Project"`
	CreateFileStorageDrV2               FileStorageVmCreateFileStorageDrV2Cmd               `cmd:"" name:"create-file-storage-dr-v2" help:"Create File Storage DR"`
	CreateFileStorageSnapshotScheduleV2 FileStorageVmCreateFileStorageSnapshotScheduleV2Cmd `cmd:"" name:"create-file-storage-snapshot-schedule-v2" help:"Create File Storage Snapshot Schedule"`
	CreateFileStorageSnapshotV2         FileStorageVmCreateFileStorageSnapshotV2Cmd         `cmd:"" name:"create-file-storage-snapshot-v2" help:"Create File Storage Snapshot"`
	DeleteFileStorageDrRelationV2       FileStorageVmDeleteFileStorageDrRelationV2Cmd       `cmd:"" name:"delete-file-storage-dr-relation-v2" help:"Delete File Storage DR Relation"`
	DeleteFileStorageSnapshotScheduleV2 FileStorageVmDeleteFileStorageSnapshotScheduleV2Cmd `cmd:"" name:"delete-file-storage-snapshot-schedule-v2" help:"Delete File Storage Snapshot Schedule"`
	DeleteFileStorageSnapshotV2         FileStorageVmDeleteFileStorageSnapshotV2Cmd         `cmd:"" name:"delete-file-storage-snapshot-v2" help:"Delete File Storage Snapshot"`
	DeleteFileStorageV2                 FileStorageVmDeleteFileStorageV2Cmd                 `cmd:"" name:"delete-file-storage-v2" help:"Delete File Storage"`
	DetailFileStorageV2                 FileStorageVmDetailFileStorageV2Cmd                 `cmd:"" name:"detail-file-storage-v2" help:"Query File Storage details"`
	GetFileStorageDrStateV2             FileStorageVmGetFileStorageDrStateV2Cmd             `cmd:"" name:"get-file-storage-dr-state-v2" help:"Get File Storage DR State"`
	IncreaseFileStorageCapacityV2       FileStorageVmIncreaseFileStorageCapacityV2Cmd       `cmd:"" name:"increase-file-storage-capacity-v2" help:"Increase File Storage capacity"`
	LinkInstanceToFileStorageV2         FileStorageVmLinkInstanceToFileStorageV2Cmd         `cmd:"" name:"link-instance-to-file-storage-v2" help:"Link Instance to File Storage"`
	ListFileStorageSnapshotsV2          FileStorageVmListFileStorageSnapshotsV2Cmd          `cmd:"" name:"list-file-storage-snapshots-v2" help:"List File Storage Snapshots"`
	ListFileStoragesV2                  FileStorageVmListFileStoragesV2Cmd                  `cmd:"" name:"list-file-storages-v2" help:"List File Storages"`
	RestoreFileStorageSnapshotV2        FileStorageVmRestoreFileStorageSnapshotV2Cmd        `cmd:"" name:"restore-file-storage-snapshot-v2" help:"Restore File Storage Snapshot"`
	SearchFileStorageLinkMaxCountV2     FileStorageVmSearchFileStorageLinkMaxCountV2Cmd     `cmd:"" name:"search-file-storage-link-max-count-v2" help:"Search File Storage Link max count"`
	SearchFileStorageSnapshotScheduleV2 FileStorageVmSearchFileStorageSnapshotScheduleV2Cmd `cmd:"" name:"search-file-storage-snapshot-schedule-v2" help:"Search File Storage Snapshot Schedule"`
	UpdateFileStorageDrPolicyV2         FileStorageVmUpdateFileStorageDrPolicyV2Cmd         `cmd:"" name:"update-file-storage-dr-policy-v2" help:"Update File Storage DR Policy"`
	UpdateFileStorageDrScheduleV2       FileStorageVmUpdateFileStorageDrScheduleV2Cmd       `cmd:"" name:"update-file-storage-dr-schedule-v2" help:"Update File Storage DR Schedule"`
	UpdateFileStorageSnapshotCapacityV2 FileStorageVmUpdateFileStorageSnapshotCapacityV2Cmd `cmd:"" name:"update-file-storage-snapshot-capacity-v2" help:"Update File Storage Snapshot capacity"`
	UpdateFileStorageSnapshotScheduleV2 FileStorageVmUpdateFileStorageSnapshotScheduleV2Cmd `cmd:"" name:"update-file-storage-snapshot-schedule-v2" help:"Update File Storage Snapshot Schedule"`
}
