// Code generated by codegen. DO NOT EDIT.

package commands

type FileStorageCheckFileStorageDuplicationCmd struct {
	FileStorageName string `name:"file-storage-name" help:"File Storage Name" required:""`
}

func (c *FileStorageCheckFileStorageDuplicationCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/check-duplication",
		map[string]string{},
		map[string]string{"fileStorageName": c.FileStorageName},
		nil)
}

type FileStorageCreateFileStorageCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageCreateFileStorageCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v4/storages",
		map[string]string{},
		map[string]string{},
		b)
}

type FileStorageCreateFileStorageRelationCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageCreateFileStorageRelationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v4/storages/{fileStorageId}/relations",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageCreateFileStorageRelationTiering1Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageCreateFileStorageRelationTiering1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v4/storages/{fileStorageId}/tiering",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageCreateFileStorageSnapshotCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageCreateFileStorageSnapshotCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v3/storages/{fileStorageId}/snapshots",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageCreateFileStorageSnapshotScheduleCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageCreateFileStorageSnapshotScheduleCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v3/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageDeleteFileStorageCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageDeleteFileStorageCmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v3/storages/{fileStorageId}",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageDeleteFileStorageRelationCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageDeleteFileStorageRelationCmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v3/storages/{fileStorageId}/relations",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageDeleteFileStorageSnapshotCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	SnapshotId    string `name:"snapshot-id" help:"Snapshot ID" required:""`
}

func (c *FileStorageDeleteFileStorageSnapshotCmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v3/storages/{fileStorageId}/snapshots/{snapshotId}",
		map[string]string{"fileStorageId": c.FileStorageId, "snapshotId": c.SnapshotId},
		map[string]string{},
		nil)
}

type FileStorageDeleteFileStorageSnapshotScheduleCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageDeleteFileStorageSnapshotScheduleCmd) Run() error {
	return RunRequest("DELETE", "/file-storage/v3/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageDetailFileStorageCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageDetailFileStorageCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/{fileStorageId}",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageLinkObjectToFileStorageCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageLinkObjectToFileStorageCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v4/storages/{fileStorageId}/objects/link",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageListFileStorageSnapshotsCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageListFileStorageSnapshotsCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/{fileStorageId}/snapshots",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageListFileStoragesCmd struct {
	BlockId             string `name:"block-id" help:"Block Id"`
	FileStorageCategory string `name:"file-storage-category" help:"File Storage Category"`
	FileStorageId       string `name:"file-storage-id" help:"File Storage ID"`
	FileStorageName     string `name:"file-storage-name" help:"File Storage Name"`
	FileStorageProtocol string `name:"file-storage-protocol" help:"File Storage Protocol"`
	FileStoragePurposes string `name:"file-storage-purposes" help:"File Storage Purpose"`
	FileStorageState    string `name:"file-storage-state" help:"File Storage State"`
	FileStorageStates   string `name:"file-storage-states" help:"File Storage State"`
	ServiceZoneId       string `name:"service-zone-id" help:"Service Zone ID serviceZoneId is obtained through View Project Details"`
	CreatedBy           string `name:"created-by" help:"creator"`
	Page                string `name:"page" help:"Request page number"`
	Size                string `name:"size" help:"Number of items in the Page"`
	Sort                string `name:"sort" help:"Sort condition"`
}

func (c *FileStorageListFileStoragesCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages",
		map[string]string{},
		map[string]string{"blockId": c.BlockId, "fileStorageCategory": c.FileStorageCategory, "fileStorageId": c.FileStorageId, "fileStorageName": c.FileStorageName, "fileStorageProtocol": c.FileStorageProtocol, "fileStoragePurposes": c.FileStoragePurposes, "fileStorageState": c.FileStorageState, "fileStorageStates": c.FileStorageStates, "serviceZoneId": c.ServiceZoneId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type FileStorageListRelationLocation1Cmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	ProductNames  string `name:"product-names" help:"Product Names" required:""`
	RelationType  string `name:"relation-type" help:"Relation Type" required:""`
	ServiceZoneId string `name:"service-zone-id" help:"Service Zone ID serviceZoneId is obtained through View Project Details" required:""`
}

func (c *FileStorageListRelationLocation1Cmd) Run() error {
	return RunRequest("GET", "/file-storage/v4/storages/{fileStorageId}/relation-location",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{"productNames": c.ProductNames, "relationType": c.RelationType, "serviceZoneId": c.ServiceZoneId},
		nil)
}

type FileStorageRestoreFileStorageSnapshotCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	SnapshotId    string `name:"snapshot-id" help:"Snapshot ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageRestoreFileStorageSnapshotCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/file-storage/v3/storages/{fileStorageId}/snapshots/{snapshotId}/restore",
		map[string]string{"fileStorageId": c.FileStorageId, "snapshotId": c.SnapshotId},
		map[string]string{},
		b)
}

type FileStorageSearchFileStorageObjectLinkMaxCountCountCmd struct {
}

func (c *FileStorageSearchFileStorageObjectLinkMaxCountCountCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/objects/link-max-count",
		map[string]string{},
		map[string]string{},
		nil)
}

type FileStorageSearchFileStorageRelationInfoCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageSearchFileStorageRelationInfoCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/{fileStorageId}/relations",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageSearchFileStorageRelationTieringCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageSearchFileStorageRelationTieringCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/{fileStorageId}/tiering",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageSearchFileStorageSnapshotScheduleCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageSearchFileStorageSnapshotScheduleCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageSearchFileStorageUsageCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
}

func (c *FileStorageSearchFileStorageUsageCmd) Run() error {
	return RunRequest("GET", "/file-storage/v3/storages/{fileStorageId}/usage",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		nil)
}

type FileStorageUpdateFileStorageFileUnitRecoveryCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageUpdateFileStorageFileUnitRecoveryCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v3/storages/{fileStorageId}/file-unit-recovery",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageUpdateFileStorageRelationPolicyCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageUpdateFileStorageRelationPolicyCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v3/storages/{fileStorageId}/relation-policy",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageUpdateFileStorageRelationScheduleCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageUpdateFileStorageRelationScheduleCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v3/storages/{fileStorageId}/relation-schedule",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageUpdateFileStorageRelationTieringCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageUpdateFileStorageRelationTieringCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v3/storages/{fileStorageId}/tiering",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

type FileStorageUpdateFileStorageSnapshotScheduleCmd struct {
	FileStorageId string `name:"file-storage-id" help:"File Storage ID" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FileStorageUpdateFileStorageSnapshotScheduleCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/file-storage/v3/storages/{fileStorageId}/snapshots/schedules",
		map[string]string{"fileStorageId": c.FileStorageId},
		map[string]string{},
		b)
}

// FileStorageCmd groups all file-storage operations.
type FileStorageCmd struct {
	CheckFileStorageDuplication              FileStorageCheckFileStorageDuplicationCmd              `cmd:"" name:"check-file-storage-duplication" help:"Check File Storage duplication"`
	CreateFileStorage                        FileStorageCreateFileStorageCmd                        `cmd:"" name:"create-file-storage" help:"Create File Storage"`
	CreateFileStorageRelation                FileStorageCreateFileStorageRelationCmd                `cmd:"" name:"create-file-storage-relation" help:"Create File Storage Relation"`
	CreateFileStorageRelationTiering1        FileStorageCreateFileStorageRelationTiering1Cmd        `cmd:"" name:"create-file-storage-relation-tiering_1" help:"Create File Storage Tiering"`
	CreateFileStorageSnapshot                FileStorageCreateFileStorageSnapshotCmd                `cmd:"" name:"create-file-storage-snapshot" help:"Create File Storage Snapshot"`
	CreateFileStorageSnapshotSchedule        FileStorageCreateFileStorageSnapshotScheduleCmd        `cmd:"" name:"create-file-storage-snapshot-schedule" help:"Create File Storage Snapshot Schedule"`
	DeleteFileStorage                        FileStorageDeleteFileStorageCmd                        `cmd:"" name:"delete-file-storage" help:"Delete File Storage"`
	DeleteFileStorageRelation                FileStorageDeleteFileStorageRelationCmd                `cmd:"" name:"delete-file-storage-relation" help:"Delete File Storage Relation"`
	DeleteFileStorageSnapshot                FileStorageDeleteFileStorageSnapshotCmd                `cmd:"" name:"delete-file-storage-snapshot" help:"Delete File Storage Snapshot"`
	DeleteFileStorageSnapshotSchedule        FileStorageDeleteFileStorageSnapshotScheduleCmd        `cmd:"" name:"delete-file-storage-snapshot-schedule" help:"Delete File Storage Snapshot Schedule"`
	DetailFileStorage                        FileStorageDetailFileStorageCmd                        `cmd:"" name:"detail-file-storage" help:"Query File Storage details"`
	LinkObjectToFileStorage                  FileStorageLinkObjectToFileStorageCmd                  `cmd:"" name:"link-object-to-file-storage" help:"Link Object to File Storage"`
	ListFileStorageSnapshots                 FileStorageListFileStorageSnapshotsCmd                 `cmd:"" name:"list-file-storage-snapshots" help:"Search File Storage Snapshots"`
	ListFileStorages                         FileStorageListFileStoragesCmd                         `cmd:"" name:"list-file-storages" help:"List File Storages"`
	ListRelationLocation1                    FileStorageListRelationLocation1Cmd                    `cmd:"" name:"list-relation-location_1" help:"Search File Storage Relation Location"`
	RestoreFileStorageSnapshot               FileStorageRestoreFileStorageSnapshotCmd               `cmd:"" name:"restore-file-storage-snapshot" help:"Restore File Storage Snapshot"`
	SearchFileStorageObjectLinkMaxCountCount FileStorageSearchFileStorageObjectLinkMaxCountCountCmd `cmd:"" name:"search-file-storage-object-link-max-count-count" help:"Query File Storage Object Link max count"`
	SearchFileStorageRelationInfo            FileStorageSearchFileStorageRelationInfoCmd            `cmd:"" name:"search-file-storage-relation-info" help:"Get File Storage Relation Info"`
	SearchFileStorageRelationTiering         FileStorageSearchFileStorageRelationTieringCmd         `cmd:"" name:"search-file-storage-relation-tiering" help:"Get File Storage Tiering"`
	SearchFileStorageSnapshotSchedule        FileStorageSearchFileStorageSnapshotScheduleCmd        `cmd:"" name:"search-file-storage-snapshot-schedule" help:"Query File Storage Snapshot Schedule"`
	SearchFileStorageUsage                   FileStorageSearchFileStorageUsageCmd                   `cmd:"" name:"search-file-storage-usage" help:"Search File Storage Volume Usage"`
	UpdateFileStorageFileUnitRecovery        FileStorageUpdateFileStorageFileUnitRecoveryCmd        `cmd:"" name:"update-file-storage-file-unit-recovery" help:"Update File Storage File Unit Recovery"`
	UpdateFileStorageRelationPolicy          FileStorageUpdateFileStorageRelationPolicyCmd          `cmd:"" name:"update-file-storage-relation-policy" help:"Update File Storage Relation Policy"`
	UpdateFileStorageRelationSchedule        FileStorageUpdateFileStorageRelationScheduleCmd        `cmd:"" name:"update-file-storage-relation-schedule" help:"Update File Storage Relation Schedule"`
	UpdateFileStorageRelationTiering         FileStorageUpdateFileStorageRelationTieringCmd         `cmd:"" name:"update-file-storage-relation-tiering" help:"Update File Storage Tiering"`
	UpdateFileStorageSnapshotSchedule        FileStorageUpdateFileStorageSnapshotScheduleCmd        `cmd:"" name:"update-file-storage-snapshot-schedule" help:"Update File Storage Snapshot Schedule"`
}
