// Code generated by codegen. DO NOT EDIT.

package commands

type FirewallCreateFirewallBulkRuleV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallCreateFirewallBulkRuleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/firewall/v2/firewalls/{firewallId}/rules/bulk",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		b)
}

type FirewallCreateFirewallLogStorageV2Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallCreateFirewallLogStorageV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/firewall/v2/log-storages",
		map[string]string{},
		map[string]string{},
		b)
}

type FirewallCreateFirewallRuleV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallCreateFirewallRuleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/firewall/v2/firewalls/{firewallId}/rules",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		b)
}

type FirewallDeleteFirewallLogStorageV2Cmd struct {
	LogStorageId string `name:"log-storage-id" help:"Log Storage ID Firewall Log Storage ID is obtained through Get List of Firewall Log Storage" required:""`
}

func (c *FirewallDeleteFirewallLogStorageV2Cmd) Run() error {
	return RunRequest("DELETE", "/firewall/v2/log-storages/{logStorageId}",
		map[string]string{"logStorageId": c.LogStorageId},
		map[string]string{},
		nil)
}

type FirewallDeleteFirewallRuleV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallDeleteFirewallRuleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/firewall/v2/firewalls/{firewallId}/rules",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		b)
}

type FirewallDetailFirewallLogStorageV2Cmd struct {
	LogStorageId string `name:"log-storage-id" help:"Log Storage ID Firewall Log Storage ID is obtained through Get List of Firewall Log Storage" required:""`
}

func (c *FirewallDetailFirewallLogStorageV2Cmd) Run() error {
	return RunRequest("GET", "/firewall/v2/log-storages/{logStorageId}",
		map[string]string{"logStorageId": c.LogStorageId},
		map[string]string{},
		nil)
}

type FirewallDetailFirewallRuleV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	RuleId     string `name:"rule-id" help:"Rule ID Rule ID is obtained through Get List of Firewall Rules" required:""`
}

func (c *FirewallDetailFirewallRuleV2Cmd) Run() error {
	return RunRequest("GET", "/firewall/v2/firewalls/{firewallId}/rules/{ruleId}",
		map[string]string{"firewallId": c.FirewallId, "ruleId": c.RuleId},
		map[string]string{},
		nil)
}

type FirewallDetailFirewallV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
}

func (c *FirewallDetailFirewallV2Cmd) Run() error {
	return RunRequest("GET", "/firewall/v2/firewalls/{firewallId}",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		nil)
}

type FirewallListFirewallLogStoragesV2Cmd struct {
	LogStorageType string `name:"log-storage-type" help:"Log Storage Type"`
	ObsBucketId    string `name:"obs-bucket-id" help:"OBS Bucket ID of Firewall"`
	VpcId          string `name:"vpc-id" help:"VPC ID" required:""`
}

func (c *FirewallListFirewallLogStoragesV2Cmd) Run() error {
	return RunRequest("GET", "/firewall/v2/log-storages",
		map[string]string{},
		map[string]string{"logStorageType": c.LogStorageType, "obsBucketId": c.ObsBucketId, "vpcId": c.VpcId},
		nil)
}

type FirewallListFirewallRulesV2Cmd struct {
	FirewallId           string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	DestinationIpAddress string `name:"destination-ip-address" help:"Destination IP address"`
	IsRuleEnabled        string `name:"is-rule-enabled" help:"Is Rule Enabled"`
	RuleDescription      string `name:"rule-description" help:"Rule description"`
	RuleDirections       string `name:"rule-directions" help:"List of Rule direction"`
	RuleStates           string `name:"rule-states" help:"List of Rule state"`
	SourceIpAddress      string `name:"source-ip-address" help:"Source IP address"`
	CreatedBy            string `name:"created-by" help:"creator"`
	Page                 string `name:"page" help:"Request page number"`
	Size                 string `name:"size" help:"Number of items in the Page"`
	Sort                 string `name:"sort" help:"Sort condition"`
}

func (c *FirewallListFirewallRulesV2Cmd) Run() error {
	return RunRequest("GET", "/firewall/v2/firewalls/{firewallId}/rules",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{"destinationIpAddress": c.DestinationIpAddress, "isRuleEnabled": c.IsRuleEnabled, "ruleDescription": c.RuleDescription, "ruleDirections": c.RuleDirections, "ruleStates": c.RuleStates, "sourceIpAddress": c.SourceIpAddress, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type FirewallListFirewallsV2Cmd struct {
	FirewallName   string `name:"firewall-name" help:"Firewall Name"`
	FirewallStates string `name:"firewall-states" help:"List of Firewall State"`
	IsLoggable     string `name:"is-loggable" help:"Is Loggable"`
	ObjectId       string `name:"object-id" help:"Object ID"`
	ObjectTypes    string `name:"object-types" help:"List of Object Type"`
	VpcId          string `name:"vpc-id" help:"VPC ID"`
	CreatedBy      string `name:"created-by" help:"creator"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *FirewallListFirewallsV2Cmd) Run() error {
	return RunRequest("GET", "/firewall/v2/firewalls",
		map[string]string{},
		map[string]string{"firewallName": c.FirewallName, "firewallStates": c.FirewallStates, "isLoggable": c.IsLoggable, "objectId": c.ObjectId, "objectTypes": c.ObjectTypes, "vpcId": c.VpcId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type FirewallUpdateFirewallEnabledV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallUpdateFirewallEnabledV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/firewall/v2/firewalls/{firewallId}/enabled",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		b)
}

type FirewallUpdateFirewallLogStorageV2Cmd struct {
	LogStorageId string `name:"log-storage-id" help:"Log Storage ID Firewall Log Storage ID is obtained through Get List of Firewall Log Storage" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallUpdateFirewallLogStorageV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/firewall/v2/log-storages/{logStorageId}",
		map[string]string{"logStorageId": c.LogStorageId},
		map[string]string{},
		b)
}

type FirewallUpdateFirewallLoggableV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallUpdateFirewallLoggableV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/firewall/v2/firewalls/{firewallId}/loggable",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		b)
}

type FirewallUpdateFirewallRuleEnabledV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallUpdateFirewallRuleEnabledV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/firewall/v2/firewalls/{firewallId}/rules/enabled",
		map[string]string{"firewallId": c.FirewallId},
		map[string]string{},
		b)
}

type FirewallUpdateFirewallRuleLocationV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	RuleId     string `name:"rule-id" help:"Rule ID Rule ID is obtained through Get List of Firewall Rules" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallUpdateFirewallRuleLocationV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/firewall/v2/firewalls/{firewallId}/rules/{ruleId}/location",
		map[string]string{"firewallId": c.FirewallId, "ruleId": c.RuleId},
		map[string]string{},
		b)
}

type FirewallUpdateFirewallRuleV2Cmd struct {
	FirewallId string `name:"firewall-id" help:"Firewall ID Firewall ID is obtained through Get List of Firewalls" required:""`
	RuleId     string `name:"rule-id" help:"Rule ID Rule ID is obtained through Get List of Firewall Rules" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FirewallUpdateFirewallRuleV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/firewall/v2/firewalls/{firewallId}/rules/{ruleId}",
		map[string]string{"firewallId": c.FirewallId, "ruleId": c.RuleId},
		map[string]string{},
		b)
}

// FirewallCmd groups all firewall operations.
type FirewallCmd struct {
	CreateFirewallBulkRuleV2     FirewallCreateFirewallBulkRuleV2Cmd     `cmd:"" name:"create-firewall-bulk-rule-v2" help:"Create Firewall Bulk Rule"`
	CreateFirewallLogStorageV2   FirewallCreateFirewallLogStorageV2Cmd   `cmd:"" name:"create-firewall-log-storage-v2" help:"Create Firewall Log Storage"`
	CreateFirewallRuleV2         FirewallCreateFirewallRuleV2Cmd         `cmd:"" name:"create-firewall-rule-v2" help:"Create Firewall Rule"`
	DeleteFirewallLogStorageV2   FirewallDeleteFirewallLogStorageV2Cmd   `cmd:"" name:"delete-firewall-log-storage-v2" help:"Delete Firewall Log Storage"`
	DeleteFirewallRuleV2         FirewallDeleteFirewallRuleV2Cmd         `cmd:"" name:"delete-firewall-rule-v2" help:"Delete Firewall Rule"`
	DetailFirewallLogStorageV2   FirewallDetailFirewallLogStorageV2Cmd   `cmd:"" name:"detail-firewall-log-storage-v2" help:"Get Firewall Log Storage details"`
	DetailFirewallRuleV2         FirewallDetailFirewallRuleV2Cmd         `cmd:"" name:"detail-firewall-rule-v2" help:"Get Firewall Rule details"`
	DetailFirewallV2             FirewallDetailFirewallV2Cmd             `cmd:"" name:"detail-firewall-v2" help:"Get Firewall details"`
	ListFirewallLogStoragesV2    FirewallListFirewallLogStoragesV2Cmd    `cmd:"" name:"list-firewall-log-storages-v2" help:"Get List of Firewall Log Storage"`
	ListFirewallRulesV2          FirewallListFirewallRulesV2Cmd          `cmd:"" name:"list-firewall-rules-v2" help:"Get List of Firewall Rules"`
	ListFirewallsV2              FirewallListFirewallsV2Cmd              `cmd:"" name:"list-firewalls-v2" help:"Get List of Firewalls"`
	UpdateFirewallEnabledV2      FirewallUpdateFirewallEnabledV2Cmd      `cmd:"" name:"update-firewall-enabled-v2" help:"Update Firewall Enabled"`
	UpdateFirewallLogStorageV2   FirewallUpdateFirewallLogStorageV2Cmd   `cmd:"" name:"update-firewall-log-storage-v2" help:"Update Firewall Log Storage"`
	UpdateFirewallLoggableV2     FirewallUpdateFirewallLoggableV2Cmd     `cmd:"" name:"update-firewall-loggable-v2" help:"Update Firewall Loggable"`
	UpdateFirewallRuleEnabledV2  FirewallUpdateFirewallRuleEnabledV2Cmd  `cmd:"" name:"update-firewall-rule-enabled-v2" help:"Update Firewall Rule Enabled"`
	UpdateFirewallRuleLocationV2 FirewallUpdateFirewallRuleLocationV2Cmd `cmd:"" name:"update-firewall-rule-location-v2" help:"Update Firewall Rule location"`
	UpdateFirewallRuleV2         FirewallUpdateFirewallRuleV2Cmd         `cmd:"" name:"update-firewall-rule-v2" help:"Update Firewall Rule"`
}
