// Code generated by codegen. DO NOT EDIT.

package commands

type FpmsUpdateFpmsStatusCmd struct {
	FpmsProductId    string `name:"fpms-product-id" help:"FPMS product ID" required:""`
	FpmsStatusInfoVo string `name:"fpms-status-info-vo" help:"Status information of FPMS(number of firewall registrations, installed version, etc.) object" required:""`
	Body             string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *FpmsUpdateFpmsStatusCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/on-service/external/fpms/v1/{fpmsProductId}/status",
		map[string]string{"fpmsProductId": c.FpmsProductId},
		map[string]string{"fpmsStatusInfoVo": c.FpmsStatusInfoVo},
		b)
}

// FpmsCmd groups all fpms operations.
type FpmsCmd struct {
	UpdateFpmsStatus FpmsUpdateFpmsStatusCmd `cmd:"" name:"update-fpms-status" help:"update FPMS production status"`
}
