// Code generated by codegen. DO NOT EDIT.

package commands

type GithubAttachGithubSecurityGroupCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubAttachGithubSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v1/githubs/{githubId}/security-group",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

type GithubAttachNatIpCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	NicId    string `name:"nic-id" help:"NIC ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubAttachNatIpCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v1/githubs/{githubId}/nics/{nicId}/nat-ip/attach",
		map[string]string{"githubId": c.GithubId, "nicId": c.NicId},
		map[string]string{},
		b)
}

type GithubCreateGithub1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubCreateGithub1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v2/githubs",
		map[string]string{},
		map[string]string{},
		b)
}

type GithubDeleteGithubCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
}

func (c *GithubDeleteGithubCmd) Run() error {
	return RunRequest("DELETE", "/github/v1/githubs/{githubId}",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		nil)
}

type GithubDetachGithubSecurityGroupCmd struct {
	GithubId        string `name:"github-id" help:"Github ID" required:""`
	SecurityGroupId string `name:"security-group-id" help:"Security Group ID" required:""`
}

func (c *GithubDetachGithubSecurityGroupCmd) Run() error {
	return RunRequest("DELETE", "/github/v1/githubs/{githubId}/security-group/{securityGroupId}",
		map[string]string{"githubId": c.GithubId, "securityGroupId": c.SecurityGroupId},
		map[string]string{},
		nil)
}

type GithubDetachNatIpCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	NicId    string `name:"nic-id" help:"NIC ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubDetachNatIpCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v1/githubs/{githubId}/nics/{nicId}/nat-ip/detach",
		map[string]string{"githubId": c.GithubId, "nicId": c.NicId},
		map[string]string{},
		b)
}

type GithubDetailGithubCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
}

func (c *GithubDetailGithubCmd) Run() error {
	return RunRequest("GET", "/github/v1/githubs/{githubId}",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		nil)
}

type GithubListGithubsCmd struct {
	GithubName string `name:"github-name" help:"Github name"`
	Page       string `name:"page" help:"Request page number"`
	Size       string `name:"size" help:"Number of items in the Page"`
	Sort       string `name:"sort" help:"Sort condition"`
}

func (c *GithubListGithubsCmd) Run() error {
	return RunRequest("GET", "/github/v1/githubs",
		map[string]string{},
		map[string]string{"githubName": c.GithubName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type GithubListNicsCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
}

func (c *GithubListNicsCmd) Run() error {
	return RunRequest("GET", "/github/v1/githubs/{githubId}/nics",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		nil)
}

type GithubResizeGithub1Cmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubResizeGithub1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v2/githubs/{githubId}/resize",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

type GithubRestartGithubCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubRestartGithubCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v1/githubs/{githubId}/restart",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

type GithubStartGithubCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubStartGithubCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v1/githubs/{githubId}/start",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

type GithubStopGithubCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubStopGithubCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/github/v1/githubs/{githubId}/stop",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

type GithubUpdateGithubDeletionProtectionEnabledCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubUpdateGithubDeletionProtectionEnabledCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/github/v1/githubs/{githubId}/deletion-protection-enabled",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

type GithubUpdateGithubSubnetIpCmd struct {
	GithubId string `name:"github-id" help:"Github ID" required:""`
	Body     string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GithubUpdateGithubSubnetIpCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/github/v1/githubs/{githubId}/nics",
		map[string]string{"githubId": c.GithubId},
		map[string]string{},
		b)
}

// GithubCmd groups all github operations.
type GithubCmd struct {
	AttachGithubSecurityGroup             GithubAttachGithubSecurityGroupCmd             `cmd:"" name:"attach-github-security-group" help:"Attach security group to Github"`
	AttachNatIp                           GithubAttachNatIpCmd                           `cmd:"" name:"attach-nat-ip" help:"Attach NAT IP to Github"`
	CreateGithub1                         GithubCreateGithub1Cmd                         `cmd:"" name:"create-github_1" help:"Create Github"`
	DeleteGithub                          GithubDeleteGithubCmd                          `cmd:"" name:"delete-github" help:"Delete Github"`
	DetachGithubSecurityGroup             GithubDetachGithubSecurityGroupCmd             `cmd:"" name:"detach-github-security-group" help:"Detach security group from Github"`
	DetachNatIp                           GithubDetachNatIpCmd                           `cmd:"" name:"detach-nat-ip" help:"Detach NAT IP from Github"`
	DetailGithub                          GithubDetailGithubCmd                          `cmd:"" name:"detail-github" help:"Get Github details"`
	ListGithubs                           GithubListGithubsCmd                           `cmd:"" name:"list-githubs" help:"Get List of Githubs"`
	ListNics                              GithubListNicsCmd                              `cmd:"" name:"list-nics" help:"Get Github's NIC(Network Interface Card) details"`
	ResizeGithub1                         GithubResizeGithub1Cmd                         `cmd:"" name:"resize-github_1" help:"Resize Github"`
	RestartGithub                         GithubRestartGithubCmd                         `cmd:"" name:"restart-github" help:"Restart Github"`
	StartGithub                           GithubStartGithubCmd                           `cmd:"" name:"start-github" help:"Start Github"`
	StopGithub                            GithubStopGithubCmd                            `cmd:"" name:"stop-github" help:"Stop Github"`
	UpdateGithubDeletionProtectionEnabled GithubUpdateGithubDeletionProtectionEnabledCmd `cmd:"" name:"update-github-deletion-protection-enabled" help:"Update Github's Deletion Protection option"`
	UpdateGithubSubnetIp                  GithubUpdateGithubSubnetIpCmd                  `cmd:"" name:"update-github-subnet-ip" help:"Update Github's Subnet and Ip addresses"`
}
