// Code generated by codegen. DO NOT EDIT.

package commands

type GslbCreateGslb1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GslbCreateGslb1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/gslb/v3/gslbs",
		map[string]string{},
		map[string]string{},
		b)
}

type GslbDeleteGslbCmd struct {
	GslbId string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
}

func (c *GslbDeleteGslbCmd) Run() error {
	return RunRequest("DELETE", "/gslb/v2/gslbs/{gslbId}",
		map[string]string{"gslbId": c.GslbId},
		map[string]string{},
		nil)
}

type GslbDetailGslbCmd struct {
	GslbId string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
}

func (c *GslbDetailGslbCmd) Run() error {
	return RunRequest("GET", "/gslb/v2/gslbs/{gslbId}",
		map[string]string{"gslbId": c.GslbId},
		map[string]string{},
		nil)
}

type GslbListGslbResourcesCmd struct {
	GslbId string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
	Page   string `name:"page" help:"Request page number"`
	Size   string `name:"size" help:"Number of items in the Page"`
	Sort   string `name:"sort" help:"Sort condition"`
}

func (c *GslbListGslbResourcesCmd) Run() error {
	return RunRequest("GET", "/gslb/v2/gslbs/{gslbId}/resources",
		map[string]string{"gslbId": c.GslbId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type GslbListGslbsCmd struct {
	GslbEnvUsage string `name:"gslb-env-usage" help:"GSLB Environment Usage"`
	GslbName     string `name:"gslb-name" help:"GSLB Name(Domain Name : omitted when creating)"`
	CreatedBy    string `name:"created-by" help:"Creator"`
	Page         string `name:"page" help:"Request page number"`
	Size         string `name:"size" help:"Number of items in the Page"`
	Sort         string `name:"sort" help:"Sort condition"`
}

func (c *GslbListGslbsCmd) Run() error {
	return RunRequest("GET", "/gslb/v2/gslbs",
		map[string]string{},
		map[string]string{"gslbEnvUsage": c.GslbEnvUsage, "gslbName": c.GslbName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type GslbUpdateGslbAlgorithmCmd struct {
	GslbId string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GslbUpdateGslbAlgorithmCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/gslb/v2/gslbs/{gslbId}/algorithm",
		map[string]string{"gslbId": c.GslbId},
		map[string]string{},
		b)
}

type GslbUpdateGslbHealthCheckCmd struct {
	GslbId string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GslbUpdateGslbHealthCheckCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/gslb/v2/gslbs/{gslbId}/health-check",
		map[string]string{"gslbId": c.GslbId},
		map[string]string{},
		b)
}

type GslbUpdateGslbResourceDisableCmd struct {
	GslbId     string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
	ResourceId string `name:"resource-id" help:"GSLB Resource ID gslbResourceId is obtained through List GSLB Resources" required:""`
	Body       string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GslbUpdateGslbResourceDisableCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/gslb/v2/gslbs/{gslbId}/resources/{resourceId}/resource-disable",
		map[string]string{"gslbId": c.GslbId, "resourceId": c.ResourceId},
		map[string]string{},
		b)
}

type GslbUpdateGslbResourcesCmd struct {
	GslbId string `name:"gslb-id" help:"GSLB ID GSLB ID is obtained through List GSLB" required:""`
	Body   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *GslbUpdateGslbResourcesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/gslb/v2/gslbs/{gslbId}/resources",
		map[string]string{"gslbId": c.GslbId},
		map[string]string{},
		b)
}

// GslbCmd groups all gslb operations.
type GslbCmd struct {
	CreateGslb1               GslbCreateGslb1Cmd               `cmd:"" name:"create-gslb_1" help:"Create GSLB"`
	DeleteGslb                GslbDeleteGslbCmd                `cmd:"" name:"delete-gslb" help:"Delete GSLB"`
	DetailGslb                GslbDetailGslbCmd                `cmd:"" name:"detail-gslb" help:"GSLB Detail"`
	ListGslbResources         GslbListGslbResourcesCmd         `cmd:"" name:"list-gslb-resources" help:"List GSLB Resources"`
	ListGslbs                 GslbListGslbsCmd                 `cmd:"" name:"list-gslbs" help:"List GSLB"`
	UpdateGslbAlgorithm       GslbUpdateGslbAlgorithmCmd       `cmd:"" name:"update-gslb-algorithm" help:"Update GSLB Algorithm"`
	UpdateGslbHealthCheck     GslbUpdateGslbHealthCheckCmd     `cmd:"" name:"update-gslb-health-check" help:"Update GSLB HealthCheck"`
	UpdateGslbResourceDisable GslbUpdateGslbResourceDisableCmd `cmd:"" name:"update-gslb-resource-disable" help:"Update GSLB Resource Disable Use"`
	UpdateGslbResources       GslbUpdateGslbResourcesCmd       `cmd:"" name:"update-gslb-resources" help:"Update GSLB Resources"`
}
