// Code generated by codegen. DO NOT EDIT.

package commands

type IdentityCenterAttachPolicyToPermissionSetCmd struct {
	PermissionSetId string `name:"permission-set-id" help:"Permission set ID You can search permission set ID using List permission sets" required:""`
	SsoInstanceId   string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterAttachPolicyToPermissionSetCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets/{permissionSetId}/attach",
		map[string]string{"permissionSetId": c.PermissionSetId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterCreateAssignmentCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterCreateAssignmentCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/{ssoInstanceId}/assignments",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterCreateInstanceFromSingleIdCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterCreateInstanceFromSingleIdCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/single-id",
		map[string]string{},
		map[string]string{},
		b)
}

type IdentityCenterCreatePermissionSetCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterCreatePermissionSetCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterDelegateAuthorityCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterDelegateAuthorityCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/{ssoInstanceId}/delegate",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterDeleteAssignmentCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterDeleteAssignmentCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/identity-center/v1/instances/{ssoInstanceId}/assignments",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterDeleteInstanceCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
}

func (c *IdentityCenterDeleteInstanceCmd) Run() error {
	return RunRequest("DELETE", "/identity-center/v1/instances/{ssoInstanceId}",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		nil)
}

type IdentityCenterDeletePermissionSetCmd struct {
	PermissionSetId string `name:"permission-set-id" help:"Permission set ID You can search permission set ID using List permission sets" required:""`
	SsoInstanceId   string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
}

func (c *IdentityCenterDeletePermissionSetCmd) Run() error {
	return RunRequest("DELETE", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets/{permissionSetId}",
		map[string]string{"permissionSetId": c.PermissionSetId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		nil)
}

type IdentityCenterDescribeInstanceCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
}

func (c *IdentityCenterDescribeInstanceCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		nil)
}

type IdentityCenterDescribePermissionSetCmd struct {
	PermissionSetId string `name:"permission-set-id" help:"Permission set ID You can search permission set ID using List permission sets" required:""`
	SsoInstanceId   string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
}

func (c *IdentityCenterDescribePermissionSetCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets/{permissionSetId}",
		map[string]string{"permissionSetId": c.PermissionSetId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		nil)
}

type IdentityCenterDescribeUserCmd struct {
	UserId string `name:"user-id" help:"User ID You can search user ID using Lists user information" required:""`
}

func (c *IdentityCenterDescribeUserCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/users/{userId}",
		map[string]string{"userId": c.UserId},
		map[string]string{},
		nil)
}

type IdentityCenterDetachPolicyFromPermissionSetCmd struct {
	PermissionSetId string `name:"permission-set-id" help:"Permission set ID You can search permission set ID using List permission sets" required:""`
	SsoInstanceId   string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterDetachPolicyFromPermissionSetCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets/{permissionSetId}/detach",
		map[string]string{"permissionSetId": c.PermissionSetId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterListGroupsAssignedToProjectCmd struct {
	ProjectId     string `name:"project-id" help:"Project ID You can search project ID using View Project List of User (Paging applied)" required:""`
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListGroupsAssignedToProjectCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/projects/{projectId}/groups",
		map[string]string{"projectId": c.ProjectId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListInstancesCmd struct {
}

func (c *IdentityCenterListInstancesCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances",
		map[string]string{},
		map[string]string{},
		nil)
}

type IdentityCenterListPermissionSetsCmd struct {
	SsoInstanceId     string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Description       string `name:"description" help:"Description"`
	ModifiedByEmail   string `name:"modified-by-email" help:"Modifier E-mail"`
	PermissionSetName string `name:"permission-set-name" help:"Permission set name"`
	PermissionSetType string `name:"permission-set-type" help:"Permission set type"`
	CreatedByName     string `name:"created-by-name" help:"Creator Name"`
	CreatedByEmail    string `name:"created-by-email" help:"Creator E-mail"`
	ModifiedByName    string `name:"modified-by-name" help:"Modifier Name"`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListPermissionSetsCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{"description": c.Description, "modifiedByEmail": c.ModifiedByEmail, "permissionSetName": c.PermissionSetName, "permissionSetType": c.PermissionSetType, "createdByName": c.CreatedByName, "createdByEmail": c.CreatedByEmail, "modifiedByName": c.ModifiedByName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListPermissionSetsAssignedToGroupCmd struct {
	GroupId       string `name:"group-id" help:"Group ID You can search group ID using List project -> group permission sets" required:""`
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListPermissionSetsAssignedToGroupCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/groups/{groupId}/permission-sets",
		map[string]string{"groupId": c.GroupId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListPermissionSetsAssignedToProjectCmd struct {
	ProjectId     string `name:"project-id" help:"Project ID You can search project ID using View Project List of User (Paging applied)" required:""`
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListPermissionSetsAssignedToProjectCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/projects/{projectId}/permission-sets",
		map[string]string{"projectId": c.ProjectId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListPermissionSetsAssignedToUserCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	UserId        string `name:"user-id" help:"User ID You can search user ID using Lists user information" required:""`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListPermissionSetsAssignedToUserCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/users/{userId}/permission-sets",
		map[string]string{"ssoInstanceId": c.SsoInstanceId, "userId": c.UserId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListProjectsAssignedToPermissionSetCmd struct {
	PermissionSetId string `name:"permission-set-id" help:"Permission set ID You can search permission set ID using List permission sets" required:""`
	SsoInstanceId   string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListProjectsAssignedToPermissionSetCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets/{permissionSetId}/projects",
		map[string]string{"permissionSetId": c.PermissionSetId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListUsersCmd struct {
	ExternalUserId string `name:"external-user-id" help:"External user id"`
	UserId         string `name:"user-id" help:"User ID"`
	UserName       string `name:"user-name" help:"User name"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListUsersCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/users",
		map[string]string{},
		map[string]string{"externalUserId": c.ExternalUserId, "userId": c.UserId, "userName": c.UserName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterListUsersAssignedToProjectCmd struct {
	ProjectId     string `name:"project-id" help:"Project ID You can search project ID using View Project List of User (Paging applied)" required:""`
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *IdentityCenterListUsersAssignedToProjectCmd) Run() error {
	return RunRequest("GET", "/identity-center/v1/instances/{ssoInstanceId}/projects/{projectId}/users",
		map[string]string{"projectId": c.ProjectId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type IdentityCenterUndelegateAuthorityCmd struct {
	SsoInstanceId string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterUndelegateAuthorityCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/instances/{ssoInstanceId}/undelegate",
		map[string]string{"ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterUpdatePermissionSetCmd struct {
	PermissionSetId string `name:"permission-set-id" help:"Permission set ID You can search permission set ID using List permission sets" required:""`
	SsoInstanceId   string `name:"sso-instance-id" help:"Instance ID You can search instance ID using List instances" required:""`
	Body            string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterUpdatePermissionSetCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/identity-center/v1/instances/{ssoInstanceId}/permission-sets/{permissionSetId}",
		map[string]string{"permissionSetId": c.PermissionSetId, "ssoInstanceId": c.SsoInstanceId},
		map[string]string{},
		b)
}

type IdentityCenterValidateInlinePolicyCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *IdentityCenterValidateInlinePolicyCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/identity-center/v1/inline-policys/validate",
		map[string]string{},
		map[string]string{},
		b)
}

// IdentityCenterCmd groups all identity-center operations.
type IdentityCenterCmd struct {
	AttachPolicyToPermissionSet         IdentityCenterAttachPolicyToPermissionSetCmd         `cmd:"" name:"attach-policy-to-permission-set" help:"Attach permission set policy"`
	CreateAssignment                    IdentityCenterCreateAssignmentCmd                    `cmd:"" name:"create-assignment" help:"Assign permission to a permission set"`
	CreateInstanceFromSingleId          IdentityCenterCreateInstanceFromSingleIdCmd          `cmd:"" name:"create-instance-from-single-id" help:"Create instance (SingleID)"`
	CreatePermissionSet                 IdentityCenterCreatePermissionSetCmd                 `cmd:"" name:"create-permission-set" help:"Create permission set"`
	DelegateAuthority                   IdentityCenterDelegateAuthorityCmd                   `cmd:"" name:"delegate-authority" help:"Authority delegation"`
	DeleteAssignment                    IdentityCenterDeleteAssignmentCmd                    `cmd:"" name:"delete-assignment" help:"Delete permission from a permission set"`
	DeleteInstance                      IdentityCenterDeleteInstanceCmd                      `cmd:"" name:"delete-instance" help:"Delete instance"`
	DeletePermissionSet                 IdentityCenterDeletePermissionSetCmd                 `cmd:"" name:"delete-permission-set" help:"Delete permission set"`
	DescribeInstance                    IdentityCenterDescribeInstanceCmd                    `cmd:"" name:"describe-instance" help:"Describe instance details"`
	DescribePermissionSet               IdentityCenterDescribePermissionSetCmd               `cmd:"" name:"describe-permission-set" help:"Describe permission set details"`
	DescribeUser                        IdentityCenterDescribeUserCmd                        `cmd:"" name:"describe-user" help:"Describe user details"`
	DetachPolicyFromPermissionSet       IdentityCenterDetachPolicyFromPermissionSetCmd       `cmd:"" name:"detach-policy-from-permission-set" help:"Detach permission set policy"`
	ListGroupsAssignedToProject         IdentityCenterListGroupsAssignedToProjectCmd         `cmd:"" name:"list-groups-assigned-to-project" help:"List project -> group permission sets"`
	ListInstances                       IdentityCenterListInstancesCmd                       `cmd:"" name:"list-instances" help:"List instances"`
	ListPermissionSets                  IdentityCenterListPermissionSetsCmd                  `cmd:"" name:"list-permission-sets" help:"List permission sets"`
	ListPermissionSetsAssignedToGroup   IdentityCenterListPermissionSetsAssignedToGroupCmd   `cmd:"" name:"list-permission-sets-assigned-to-group" help:"List group -> permission sets of project"`
	ListPermissionSetsAssignedToProject IdentityCenterListPermissionSetsAssignedToProjectCmd `cmd:"" name:"list-permission-sets-assigned-to-project" help:"List project -> permission sets"`
	ListPermissionSetsAssignedToUser    IdentityCenterListPermissionSetsAssignedToUserCmd    `cmd:"" name:"list-permission-sets-assigned-to-user" help:"List user -> project permission sets"`
	ListProjectsAssignedToPermissionSet IdentityCenterListProjectsAssignedToPermissionSetCmd `cmd:"" name:"list-projects-assigned-to-permission-set" help:"List permission set -> projects"`
	ListUsers                           IdentityCenterListUsersCmd                           `cmd:"" name:"list-users" help:"Lists user information"`
	ListUsersAssignedToProject          IdentityCenterListUsersAssignedToProjectCmd          `cmd:"" name:"list-users-assigned-to-project" help:"List project -> user permission sets"`
	UndelegateAuthority                 IdentityCenterUndelegateAuthorityCmd                 `cmd:"" name:"undelegate-authority" help:"Revoke authority"`
	UpdatePermissionSet                 IdentityCenterUpdatePermissionSetCmd                 `cmd:"" name:"update-permission-set" help:"Update permission set"`
	ValidateInlinePolicy                IdentityCenterValidateInlinePolicyCmd                `cmd:"" name:"validate-inline-policy" help:"Validate of inline policy JSON statements"`
}
