// Code generated by codegen. DO NOT EDIT.

package commands

type LoggingAuditCheckTrailNameCmd struct {
	ProjectId string `name:"project-id" help:"Project ID Project ID can be retrieved using View Project List of User" required:""`
	TrailName string `name:"trail-name" help:"Trail Name Trail name can be retrieved using View Trail List" required:""`
}

func (c *LoggingAuditCheckTrailNameCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/trails/{projectId}/{trailName}/validates",
		map[string]string{"projectId": c.ProjectId, "trailName": c.TrailName},
		map[string]string{},
		nil)
}

type LoggingAuditCreateTrailCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditCreateTrailCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/trail",
		map[string]string{},
		map[string]string{},
		b)
}

type LoggingAuditDeleteTrailCmd struct {
	TrailId string `name:"trail-id" help:"Trail ID Trail ID can be retrieved using View Trail List" required:""`
}

func (c *LoggingAuditDeleteTrailCmd) Run() error {
	return RunRequest("DELETE", "/logging-audit/v2/trails/{trailId}",
		map[string]string{"trailId": c.TrailId},
		map[string]string{},
		nil)
}

type LoggingAuditDetailLoggingCmd struct {
	LoggingId string `name:"logging-id" help:"Activity Logging ID Activity logging ID can be retrieved using View Activity List" required:""`
}

func (c *LoggingAuditDetailLoggingCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/logs/{loggingId}",
		map[string]string{"loggingId": c.LoggingId},
		map[string]string{},
		nil)
}

type LoggingAuditDetailTrailCmd struct {
	TrailId string `name:"trail-id" help:"Trail ID Trail ID can be retrieved using View Trail List" required:""`
}

func (c *LoggingAuditDetailTrailCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/trails/{trailId}",
		map[string]string{"trailId": c.TrailId},
		map[string]string{},
		nil)
}

type LoggingAuditListLoggingDownloadCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditListLoggingDownloadCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/logs/download",
		map[string]string{},
		map[string]string{},
		b)
}

type LoggingAuditListLoggingMyProjectsStatisticsCmd struct {
	RequestEndDt   string `name:"request-end-dt" help:"Request End Date and Time (default current date)"`
	RequestStartDt string `name:"request-start-dt" help:"Request Start Date and Time (default 3 months ago)"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *LoggingAuditListLoggingMyProjectsStatisticsCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/logs/my-projects/statistics",
		map[string]string{},
		map[string]string{"requestEndDt": c.RequestEndDt, "requestStartDt": c.RequestStartDt, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type LoggingAuditListLoggingStatisticsCmd struct {
	RequestEndDt   string `name:"request-end-dt" help:"Request End Date and Time (default current date)"`
	RequestStartDt string `name:"request-start-dt" help:"Request Start Date and Time (default 3 months ago)"`
	Page           string `name:"page" help:"Request page number"`
	Size           string `name:"size" help:"Number of items in the Page"`
	Sort           string `name:"sort" help:"Sort condition"`
}

func (c *LoggingAuditListLoggingStatisticsCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/logs/statistics",
		map[string]string{},
		map[string]string{"requestEndDt": c.RequestEndDt, "requestStartDt": c.RequestStartDt, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type LoggingAuditListLoggingsCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditListLoggingsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/logs",
		map[string]string{},
		map[string]string{},
		b)
}

type LoggingAuditListTrailsCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditListTrailsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/trails",
		map[string]string{},
		map[string]string{},
		b)
}

type LoggingAuditListUsersCmd struct {
	UserName string `name:"user-name" help:"User Name"`
	Page     string `name:"page" help:"Request page number"`
	Size     string `name:"size" help:"Number of items in the Page"`
	Sort     string `name:"sort" help:"Sort condition"`
}

func (c *LoggingAuditListUsersCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/users",
		map[string]string{},
		map[string]string{"userName": c.UserName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type LoggingAuditResultValidationTrailCmd struct {
	TrailValidationId string `name:"trail-validation-id" help:"Trail Validation ID" required:""`
}

func (c *LoggingAuditResultValidationTrailCmd) Run() error {
	return RunRequest("GET", "/logging-audit/v2/trails/validation/{trailValidationId}",
		map[string]string{"trailValidationId": c.TrailValidationId},
		map[string]string{},
		nil)
}

type LoggingAuditStartTrailCmd struct {
	TrailId string `name:"trail-id" help:"Trail ID Trail ID can be retrieved using View Trail List" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditStartTrailCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/trails/{trailId}/start",
		map[string]string{"trailId": c.TrailId},
		map[string]string{},
		b)
}

type LoggingAuditStopTrailCmd struct {
	TrailId string `name:"trail-id" help:"Trail ID Trail ID can be retrieved using View Trail List" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditStopTrailCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/trails/{trailId}/stop",
		map[string]string{"trailId": c.TrailId},
		map[string]string{},
		b)
}

type LoggingAuditUpdateTrailCmd struct {
	TrailId string `name:"trail-id" help:"Trail ID Trail ID can be retrieved using View Trail List" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditUpdateTrailCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/logging-audit/v2/trails/{trailId}",
		map[string]string{"trailId": c.TrailId},
		map[string]string{},
		b)
}

type LoggingAuditValidationTrailCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *LoggingAuditValidationTrailCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/logging-audit/v2/trails/validation",
		map[string]string{},
		map[string]string{},
		b)
}

// LoggingAuditCmd groups all logging-audit operations.
type LoggingAuditCmd struct {
	CheckTrailName                  LoggingAuditCheckTrailNameCmd                  `cmd:"" name:"check-trail-name" help:"Trail name validation (check for duplicates)"`
	CreateTrail                     LoggingAuditCreateTrailCmd                     `cmd:"" name:"create-trail" help:"Create Trail"`
	DeleteTrail                     LoggingAuditDeleteTrailCmd                     `cmd:"" name:"delete-trail" help:"Delete Trail"`
	DetailLogging                   LoggingAuditDetailLoggingCmd                   `cmd:"" name:"detail-logging" help:"View Details of Specific Activity"`
	DetailTrail                     LoggingAuditDetailTrailCmd                     `cmd:"" name:"detail-trail" help:"View specific trail details"`
	ListLoggingDownload             LoggingAuditListLoggingDownloadCmd             `cmd:"" name:"list-logging-download" help:"Download Activity List"`
	ListLoggingMyProjectsStatistics LoggingAuditListLoggingMyProjectsStatisticsCmd `cmd:"" name:"list-logging-my-projects-statistics" help:"View Statistics based on Activity Request Date (all my projects)"`
	ListLoggingStatistics           LoggingAuditListLoggingStatisticsCmd           `cmd:"" name:"list-logging-statistics" help:"View Statistics based on Activity Request Date  (based on project)"`
	ListLoggings                    LoggingAuditListLoggingsCmd                    `cmd:"" name:"list-loggings" help:"View Activity List"`
	ListTrails                      LoggingAuditListTrailsCmd                      `cmd:"" name:"list-trails" help:"View Trail List"`
	ListUsers                       LoggingAuditListUsersCmd                       `cmd:"" name:"list-users" help:"Search Users to add in Project by Project ID"`
	ResultValidationTrail           LoggingAuditResultValidationTrailCmd           `cmd:"" name:"result-validation-trail" help:"Validating Trail log file results"`
	StartTrail                      LoggingAuditStartTrailCmd                      `cmd:"" name:"start-trail" help:"Start Trail"`
	StopTrail                       LoggingAuditStopTrailCmd                       `cmd:"" name:"stop-trail" help:"Stop trail"`
	UpdateTrail                     LoggingAuditUpdateTrailCmd                     `cmd:"" name:"update-trail" help:"Modify trail information"`
	ValidationTrail                 LoggingAuditValidationTrailCmd                 `cmd:"" name:"validation-trail" help:"Validating Trail log file"`
}
