// Code generated by codegen. DO NOT EDIT.

package commands

type MonitoringDeleteEventPolicyCmd struct {
	EventPolicyId string `name:"event-policy-id" help:"Event policy Id to delete The event policy ID is searched using Query event policies by product resource" required:""`
}

func (c *MonitoringDeleteEventPolicyCmd) Run() error {
	return RunRequest("DELETE", "/monitoring/event/v2/event-policies/{eventPolicyId}",
		map[string]string{"eventPolicyId": c.EventPolicyId},
		map[string]string{},
		nil)
}

type MonitoringGetAdressBookListCmd struct {
	Page string `name:"page" help:"Page Number (default: 0)"`
	Size string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetAdressBookListCmd) Run() error {
	return RunRequest("GET", "/monitoring/product/v2/users/addrbooks",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetAdressBookMemberListCmd struct {
	AddrbookId string `name:"addrbook-id" help:"Address Book Id The address book ID can be obtained from Querying user's address book." required:""`
	Page       string `name:"page" help:"Page Number (default: 0)"`
	Size       string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort       string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetAdressBookMemberListCmd) Run() error {
	return RunRequest("GET", "/monitoring/product/v2/addrbooks/{addrbookId}/members",
		map[string]string{"addrbookId": c.AddrbookId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetEventDetailCmd struct {
	EventId string `name:"event-id" help:"Event Id The event ID is searched using Query events by product resource" required:""`
}

func (c *MonitoringGetEventDetailCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/events/{eventId}",
		map[string]string{"eventId": c.EventId},
		map[string]string{},
		nil)
}

type MonitoringGetEventNotificationStatesCmd struct {
	EventId string `name:"event-id" help:"Event Id The event ID is searched using Query events by product resource" required:""`
	Page    string `name:"page" help:"Page Number (default: 0)"`
	Size    string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort    string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetEventNotificationStatesCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/events/{eventId}/notification-states",
		map[string]string{"eventId": c.EventId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetEventPolicyDetailCmd struct {
	EventPolicyId string `name:"event-policy-id" help:"Event policy Id to query The event policy ID is searched using Query event policies by product resource" required:""`
}

func (c *MonitoringGetEventPolicyDetailCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/event-policies/{eventPolicyId}",
		map[string]string{"eventPolicyId": c.EventPolicyId},
		map[string]string{},
		nil)
}

type MonitoringGetEventPolicyHistoriesCmd struct {
	EventPolicyId string `name:"event-policy-id" help:"Event policy Id to query The event policy ID is searched using Query event policies by product resource" required:""`
	QueryEndDt    string `name:"query-end-dt" help:"Query EndDt" required:""`
	QueryStartDt  string `name:"query-start-dt" help:"Query StartDt" required:""`
	Page          string `name:"page" help:"Page Number (default: 0)"`
	Size          string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort          string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetEventPolicyHistoriesCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/event-policies/{eventPolicyId}/histories",
		map[string]string{"eventPolicyId": c.EventPolicyId},
		map[string]string{"queryEndDt": c.QueryEndDt, "queryStartDt": c.QueryStartDt, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetEventPolicyNotificationCmd struct {
	EventPolicyId string `name:"event-policy-id" help:"Event policy Id to query The event policy ID is searched using Query event policies by product resource" required:""`
	Page          string `name:"page" help:"Page Number (default: 0)"`
	Size          string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort          string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetEventPolicyNotificationCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/event-policies/{eventPolicyId}/notifications",
		map[string]string{"eventPolicyId": c.EventPolicyId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetMetricListCmd struct {
	ProductTypeCode string `name:"product-type-code" help:"Product Type Code Product type codes are queried using Querying product type codes Query the total metrics when product type code not specified"`
	ObjectType      string `name:"object-type" help:"Object Type Valid values: - LoadBalancer : service, servergroup - Kubernetes : cluster, node, replicaset, deployment, statefulset, daemonset, job, cronjob, pod, namespace - Data Flow, Data Ops : service, pod - Data Wrangler, Quick Query : namespace, pod"`
	Page            string `name:"page" help:"Page Number (default: 0)"`
	Size            string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort            string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetMetricListCmd) Run() error {
	return RunRequest("GET", "/monitoring/product/v2/metrics",
		map[string]string{},
		map[string]string{"productTypeCode": c.ProductTypeCode, "objectType": c.ObjectType, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetMetricPerfDataListCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *MonitoringGetMetricPerfDataListCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/monitoring/product/v2/metric-data",
		map[string]string{},
		map[string]string{},
		b)
}

type MonitoringGetMetricStatisticsPerfDataListCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *MonitoringGetMetricStatisticsPerfDataListCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/monitoring/product/v1/metric-statistics",
		map[string]string{},
		map[string]string{},
		b)
}

type MonitoringGetProductEventListCmd struct {
	EventState        string `name:"event-state" help:"Event State Valid values: ALL, ACTIVE, INACTIVE" required:""`
	MetricKey         string `name:"metric-key" help:"Metric Key The metric key is searched using Querying metrics"`
	ProductResourceId string `name:"product-resource-id" help:"Product Resource Id The product resource ID is searched using Querying products in project" required:""`
	QueryEndDt        string `name:"query-end-dt" help:"Query EndDt" required:""`
	QueryStartDt      string `name:"query-start-dt" help:"Query StartDt" required:""`
	Page              string `name:"page" help:"Page Number (default: 0)"`
	Size              string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort              string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetProductEventListCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/events",
		map[string]string{},
		map[string]string{"eventState": c.EventState, "metricKey": c.MetricKey, "productResourceId": c.ProductResourceId, "queryEndDt": c.QueryEndDt, "queryStartDt": c.QueryStartDt, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetProductEventPolicyListCmd struct {
	MetricKey         string `name:"metric-key" help:"Metric Key The metric key is searched using Querying metrics"`
	ProductResourceId string `name:"product-resource-id" help:"Product Resource Id The product resource ID is searched using Querying products in project" required:""`
	Page              string `name:"page" help:"Page Number (default: 0)"`
	Size              string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort              string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetProductEventPolicyListCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/event-policies",
		map[string]string{},
		map[string]string{"metricKey": c.MetricKey, "productResourceId": c.ProductResourceId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetProductTypeListCmd struct {
	ProductCategoryCode string `name:"product-category-code" help:"Product Type Code Query the total metrics when product type code not specified Valid values: Compute, Storage, Database, Data Analytics, Container, Networking"`
	Page                string `name:"page" help:"Page Number (default: 0)"`
	Size                string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort                string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetProductTypeListCmd) Run() error {
	return RunRequest("GET", "/monitoring/product/v1/product-types",
		map[string]string{},
		map[string]string{"productCategoryCode": c.ProductCategoryCode, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetProjectEventListCmd struct {
	EventState   string `name:"event-state" help:"Event State Valid values: ALL, ACTIVE, INACTIVE" required:""`
	QueryEndDt   string `name:"query-end-dt" help:"Query EndDt" required:""`
	QueryStartDt string `name:"query-start-dt" help:"Query StartDt" required:""`
	Page         string `name:"page" help:"Page Number (default: 0)"`
	Size         string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort         string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetProjectEventListCmd) Run() error {
	return RunRequest("GET", "/monitoring/event/v2/projects/events",
		map[string]string{},
		map[string]string{"eventState": c.EventState, "queryEndDt": c.QueryEndDt, "queryStartDt": c.QueryStartDt, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetProjectMembersCmd struct {
	Page string `name:"page" help:"Page Number (default: 0)"`
	Size string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetProjectMembersCmd) Run() error {
	return RunRequest("GET", "/monitoring/product/v1/projects/members",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringGetProjectProductListCmd struct {
	Page string `name:"page" help:"Page Number (default: 0)"`
	Size string `name:"size" help:"Page Contents Size (default: 10)"`
	Sort string `name:"sort" help:"Sorting Field List This value can be set by referring to the 'sortableFields' of the response result."`
}

func (c *MonitoringGetProjectProductListCmd) Run() error {
	return RunRequest("GET", "/monitoring/product/v2/projects/products",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type MonitoringModifyEventPolicyCmd struct {
	EventPolicyId string `name:"event-policy-id" help:"Event policy Id to update The event policy ID is searched using Query event policies by product resource" required:""`
	Body          string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *MonitoringModifyEventPolicyCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/monitoring/event/v2/event-policies/{eventPolicyId}",
		map[string]string{"eventPolicyId": c.EventPolicyId},
		map[string]string{},
		b)
}

type MonitoringPutEventPolicyCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *MonitoringPutEventPolicyCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/monitoring/event/v2/event-policies",
		map[string]string{},
		map[string]string{},
		b)
}

// MonitoringCmd groups all monitoring operations.
type MonitoringCmd struct {
	DeleteEventPolicy               MonitoringDeleteEventPolicyCmd               `cmd:"" name:"delete-event-policy" help:"Delete an existing event policy about product resource"`
	GetAdressBookList               MonitoringGetAdressBookListCmd               `cmd:"" name:"get-adress-book-list" help:"Querying user's address book"`
	GetAdressBookMemberList         MonitoringGetAdressBookMemberListCmd         `cmd:"" name:"get-adress-book-member-list" help:"Querying users in address book"`
	GetEventDetail                  MonitoringGetEventDetailCmd                  `cmd:"" name:"get-event-detail" help:"Query event by event Id"`
	GetEventNotificationStates      MonitoringGetEventNotificationStatesCmd      `cmd:"" name:"get-event-notification-states" help:"Query notification states of event"`
	GetEventPolicyDetail            MonitoringGetEventPolicyDetailCmd            `cmd:"" name:"get-event-policy-detail" help:"Query event policy by event policy Id"`
	GetEventPolicyHistories         MonitoringGetEventPolicyHistoriesCmd         `cmd:"" name:"get-event-policy-histories" help:"Query event policy history by event policy Id"`
	GetEventPolicyNotification      MonitoringGetEventPolicyNotificationCmd      `cmd:"" name:"get-event-policy-notification" help:"Query notification of event policy"`
	GetMetricList                   MonitoringGetMetricListCmd                   `cmd:"" name:"get-metric-list" help:"Querying metrics"`
	GetMetricPerfDataList           MonitoringGetMetricPerfDataListCmd           `cmd:"" name:"get-metric-perf-data-list" help:"Querying metric perf data"`
	GetMetricStatisticsPerfDataList MonitoringGetMetricStatisticsPerfDataListCmd `cmd:"" name:"get-metric-statistics-perf-data-list" help:"Querying metric statistics perf data"`
	GetProductEventList             MonitoringGetProductEventListCmd             `cmd:"" name:"get-product-event-list" help:"Query events by product resource"`
	GetProductEventPolicyList       MonitoringGetProductEventPolicyListCmd       `cmd:"" name:"get-product-event-policy-list" help:"Query event policies by product resource"`
	GetProductTypeList              MonitoringGetProductTypeListCmd              `cmd:"" name:"get-product-type-list" help:"Querying product type codes"`
	GetProjectEventList             MonitoringGetProjectEventListCmd             `cmd:"" name:"get-project-event-list" help:"Query events by project"`
	GetProjectMembers               MonitoringGetProjectMembersCmd               `cmd:"" name:"get-project-members" help:"Querying projet members"`
	GetProjectProductList           MonitoringGetProjectProductListCmd           `cmd:"" name:"get-project-product-list" help:"Querying products in project"`
	ModifyEventPolicy               MonitoringModifyEventPolicyCmd               `cmd:"" name:"modify-event-policy" help:"Update an existing event policy about product resource"`
	PutEventPolicy                  MonitoringPutEventPolicyCmd                  `cmd:"" name:"put-event-policy" help:"Create a new event policy about product resource"`
}
