// Code generated by codegen. DO NOT EDIT.

package commands

type NatGatewayCreateNatGatewayCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *NatGatewayCreateNatGatewayCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/nat-gateway/v2/nat-gateways",
		map[string]string{},
		map[string]string{},
		b)
}

type NatGatewayDeleteNatGatewayCmd struct {
	NatGatewayId string `name:"nat-gateway-id" help:"Nat Gateway Id Nat Gateway ID is obtained through Get Nat Gateway List" required:""`
}

func (c *NatGatewayDeleteNatGatewayCmd) Run() error {
	return RunRequest("DELETE", "/nat-gateway/v2/nat-gateways/{natGatewayId}",
		map[string]string{"natGatewayId": c.NatGatewayId},
		map[string]string{},
		nil)
}

type NatGatewayDetailNatGatewayCmd struct {
	NatGatewayId string `name:"nat-gateway-id" help:"Nat Gateway Id Nat Gateway ID is obtained through Get Nat Gateway List" required:""`
}

func (c *NatGatewayDetailNatGatewayCmd) Run() error {
	return RunRequest("GET", "/nat-gateway/v2/nat-gateways/{natGatewayId}",
		map[string]string{"natGatewayId": c.NatGatewayId},
		map[string]string{},
		nil)
}

type NatGatewayListNatGatewaysCmd struct {
	NatGatewayId    string `name:"nat-gateway-id" help:"Nat Gateway Id"`
	NatGatewayName  string `name:"nat-gateway-name" help:"Nat Gateway Name"`
	NatGatewayState string `name:"nat-gateway-state" help:"Nat Gateway State (ACTIVE"`
	SubnetId        string `name:"subnet-id" help:"Subnet Id"`
	VpcId           string `name:"vpc-id" help:"Vpc Id"`
	CreatedBy       string `name:"created-by" help:"creator"`
	Page            string `name:"page" help:"Request page number"`
	Size            string `name:"size" help:"Number of items in the Page"`
	Sort            string `name:"sort" help:"Sort condition"`
}

func (c *NatGatewayListNatGatewaysCmd) Run() error {
	return RunRequest("GET", "/nat-gateway/v2/nat-gateways",
		map[string]string{},
		map[string]string{"natGatewayId": c.NatGatewayId, "natGatewayName": c.NatGatewayName, "natGatewayState": c.NatGatewayState, "subnetId": c.SubnetId, "vpcId": c.VpcId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type NatGatewayUpdateNatGatewayDescriptionCmd struct {
	NatGatewayId string `name:"nat-gateway-id" help:"Nat Gateway Id Nat Gateway ID is obtained through Get Nat Gateway List" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *NatGatewayUpdateNatGatewayDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/nat-gateway/v2/nat-gateways/{natGatewayId}/description",
		map[string]string{"natGatewayId": c.NatGatewayId},
		map[string]string{},
		b)
}

// NatGatewayCmd groups all nat-gateway operations.
type NatGatewayCmd struct {
	CreateNatGateway            NatGatewayCreateNatGatewayCmd            `cmd:"" name:"create-nat-gateway" help:"Create Nat Gateway"`
	DeleteNatGateway            NatGatewayDeleteNatGatewayCmd            `cmd:"" name:"delete-nat-gateway" help:"Delete Nat Gateway"`
	DetailNatGateway            NatGatewayDetailNatGatewayCmd            `cmd:"" name:"detail-nat-gateway" help:"Get Nat Gateway"`
	ListNatGateways             NatGatewayListNatGatewaysCmd             `cmd:"" name:"list-nat-gateways" help:"Get Nat Gateway List"`
	UpdateNatGatewayDescription NatGatewayUpdateNatGatewayDescriptionCmd `cmd:"" name:"update-nat-gateway-description" help:"Update Nat Gateway description"`
}
