// Code generated by codegen. DO NOT EDIT.

package commands

type NotificationDeleteMailV3Cmd struct {
	MailId string `name:"mail-id" help:"Mail ID Mail ID is obtained through Search Mail List" required:""`
}

func (c *NotificationDeleteMailV3Cmd) Run() error {
	return RunRequest("DELETE", "/notification/v3/mails/{mailId}",
		map[string]string{"mailId": c.MailId},
		map[string]string{},
		nil)
}

type NotificationDeletePushV3Cmd struct {
	PushId string `name:"push-id" help:"Push ID Push ID is obtained through Search Push List" required:""`
}

func (c *NotificationDeletePushV3Cmd) Run() error {
	return RunRequest("DELETE", "/notification/v3/pushes/{pushId}",
		map[string]string{"pushId": c.PushId},
		map[string]string{},
		nil)
}

type NotificationDeleteSmsV3Cmd struct {
	SmsId string `name:"sms-id" help:"SMS ID SMS ID is obtained through Search SMS List" required:""`
}

func (c *NotificationDeleteSmsV3Cmd) Run() error {
	return RunRequest("DELETE", "/notification/v3/smses/{smsId}",
		map[string]string{"smsId": c.SmsId},
		map[string]string{},
		nil)
}

type NotificationDetailMailV3Cmd struct {
	MailId string `name:"mail-id" help:"Mail ID Mail ID is obtained through Search Mail List" required:""`
}

func (c *NotificationDetailMailV3Cmd) Run() error {
	return RunRequest("GET", "/notification/v3/mails/{mailId}",
		map[string]string{"mailId": c.MailId},
		map[string]string{},
		nil)
}

type NotificationDetailPushV3Cmd struct {
	PushId string `name:"push-id" help:"Push ID Push ID is obtained through Search Push List" required:""`
}

func (c *NotificationDetailPushV3Cmd) Run() error {
	return RunRequest("GET", "/notification/v3/pushes/{pushId}",
		map[string]string{"pushId": c.PushId},
		map[string]string{},
		nil)
}

type NotificationDetailSmsV3Cmd struct {
	SmsId string `name:"sms-id" help:"SMS ID SMS ID is obtained through Search SMS List" required:""`
}

func (c *NotificationDetailSmsV3Cmd) Run() error {
	return RunRequest("GET", "/notification/v3/smses/{smsId}",
		map[string]string{"smsId": c.SmsId},
		map[string]string{},
		nil)
}

type NotificationListMailsV3Cmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *NotificationListMailsV3Cmd) Run() error {
	return RunRequest("GET", "/notification/v3/mails",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type NotificationListPushesV3Cmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *NotificationListPushesV3Cmd) Run() error {
	return RunRequest("GET", "/notification/v3/pushes",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type NotificationListSmsesV3Cmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *NotificationListSmsesV3Cmd) Run() error {
	return RunRequest("GET", "/notification/v3/smses",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

// NotificationCmd groups all notification operations.
type NotificationCmd struct {
	DeleteMailV3 NotificationDeleteMailV3Cmd `cmd:"" name:"delete-mail-v3" help:"Delete Mail"`
	DeletePushV3 NotificationDeletePushV3Cmd `cmd:"" name:"delete-push-v3" help:"Delete Push"`
	DeleteSmsV3  NotificationDeleteSmsV3Cmd  `cmd:"" name:"delete-sms-v3" help:"Delete SMS"`
	DetailMailV3 NotificationDetailMailV3Cmd `cmd:"" name:"detail-mail-v3" help:"Search Detail Mail"`
	DetailPushV3 NotificationDetailPushV3Cmd `cmd:"" name:"detail-push-v3" help:"Search Detail Push"`
	DetailSmsV3  NotificationDetailSmsV3Cmd  `cmd:"" name:"detail-sms-v3" help:"Search Detail SMS"`
	ListMailsV3  NotificationListMailsV3Cmd  `cmd:"" name:"list-mails-v3" help:"Search Mail List"`
	ListPushesV3 NotificationListPushesV3Cmd `cmd:"" name:"list-pushes-v3" help:"Search Push List"`
	ListSmsesV3  NotificationListSmsesV3Cmd  `cmd:"" name:"list-smses-v3" help:"Search SMS List"`
}
