// Code generated by codegen. DO NOT EDIT.

package commands

type PublicIpChangePublicIpV2Cmd struct {
	PublicIpAddressId string `name:"public-ip-address-id" help:"Public IP address ID publicIpAddressId is obtained through Get List of Public IPs" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *PublicIpChangePublicIpV2Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/public-ip/v2/ip-addresses/{publicIpAddressId}",
		map[string]string{"publicIpAddressId": c.PublicIpAddressId},
		map[string]string{},
		b)
}

type PublicIpCreatePublicIpV4Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *PublicIpCreatePublicIpV4Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/public-ip/v4/ip-addresses",
		map[string]string{},
		map[string]string{},
		b)
}

type PublicIpDeletePublicIpV2Cmd struct {
	PublicIpAddressId string `name:"public-ip-address-id" help:"Public IP address ID publicIpAddressId is obtained through Get List of Public IPs" required:""`
}

func (c *PublicIpDeletePublicIpV2Cmd) Run() error {
	return RunRequest("DELETE", "/public-ip/v2/ip-addresses/{publicIpAddressId}",
		map[string]string{"publicIpAddressId": c.PublicIpAddressId},
		map[string]string{},
		nil)
}

type PublicIpDetailPublicIpV2Cmd struct {
	PublicIpAddressId string `name:"public-ip-address-id" help:"Public IP address ID publicIpAddressId is obtained through Get List of Public IPs" required:""`
}

func (c *PublicIpDetailPublicIpV2Cmd) Run() error {
	return RunRequest("GET", "/public-ip/v2/ip-addresses/{publicIpAddressId}",
		map[string]string{"publicIpAddressId": c.PublicIpAddressId},
		map[string]string{},
		nil)
}

type PublicIpListPublicIpsV3Cmd struct {
	IpAddress     string `name:"ip-address" help:"IP address"`
	PublicIpState string `name:"public-ip-state" help:"State of Public IP"`
	ServiceZoneId string `name:"service-zone-id" help:"Zone ID for Service serviceZoneId is obtained through View Project Details"`
	UplinkType    string `name:"uplink-type" help:"Uplink type"`
	VpcId         string `name:"vpc-id" help:"VPC ID vpcId is obtained through Get List of VPCs"`
	CreatedBy     string `name:"created-by" help:"User ID"`
	Page          string `name:"page" help:"Request page number"`
	Size          string `name:"size" help:"Number of items in the Page"`
	Sort          string `name:"sort" help:"Sort condition"`
}

func (c *PublicIpListPublicIpsV3Cmd) Run() error {
	return RunRequest("GET", "/public-ip/v3/ip-addresses",
		map[string]string{},
		map[string]string{"ipAddress": c.IpAddress, "publicIpState": c.PublicIpState, "serviceZoneId": c.ServiceZoneId, "uplinkType": c.UplinkType, "vpcId": c.VpcId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

// PublicIpCmd groups all public-ip operations.
type PublicIpCmd struct {
	ChangePublicIpV2 PublicIpChangePublicIpV2Cmd `cmd:"" name:"change-public-ip-v2" help:"Change Public IP"`
	CreatePublicIpV4 PublicIpCreatePublicIpV4Cmd `cmd:"" name:"create-public-ip-v4" help:"Create Public IP"`
	DeletePublicIpV2 PublicIpDeletePublicIpV2Cmd `cmd:"" name:"delete-public-ip-v2" help:"Delete Public IP"`
	DetailPublicIpV2 PublicIpDetailPublicIpV2Cmd `cmd:"" name:"detail-public-ip-v2" help:"Get Public IP details"`
	ListPublicIpsV3  PublicIpListPublicIpsV3Cmd  `cmd:"" name:"list-public-ips-v3" help:"Get List of Public IPs"`
}
