// Code generated by codegen. DO NOT EDIT.

package commands

type RedisAttachRedisClusterSecurityGroupCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisAttachRedisClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/security-groups/attach",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisAttachRedisSecurityGroupCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisAttachRedisSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/security-groups/attach",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisCreateRedisCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisCreateRedisCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis",
		map[string]string{},
		map[string]string{},
		b)
}

type RedisCreateRedisClusterCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisCreateRedisClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster",
		map[string]string{},
		map[string]string{},
		b)
}

type RedisCreateRedisClusterFullBackupConfigCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisCreateRedisClusterFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/full-backups",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisCreateRedisFullBackupConfigCmd struct {
	RedisId string `name:"redis-id" help:"" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisCreateRedisFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/full-backups",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisDeleteRedisCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
}

func (c *RedisDeleteRedisCmd) Run() error {
	return RunRequest("DELETE", "/database/redis/v1/redis/{redisId}",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		nil)
}

type RedisDeleteRedisClusterCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
}

func (c *RedisDeleteRedisClusterCmd) Run() error {
	return RunRequest("DELETE", "/database/redis/v1/redis-cluster/{redisClusterId}",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		nil)
}

type RedisDeleteRedisClusterFullBackupConfigCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
}

func (c *RedisDeleteRedisClusterFullBackupConfigCmd) Run() error {
	return RunRequest("DELETE", "/database/redis/v1/redis-cluster/{redisClusterId}/full-backups",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		nil)
}

type RedisDeleteRedisFullBackupConfigCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
}

func (c *RedisDeleteRedisFullBackupConfigCmd) Run() error {
	return RunRequest("DELETE", "/database/redis/v1/redis/{redisId}/full-backups",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		nil)
}

type RedisDetachRedisClusterSecurityGroupCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisDetachRedisClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/security-groups/detach",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisDetachRedisSecurityGroupCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisDetachRedisSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/security-groups/detach",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisDetailRedisCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
}

func (c *RedisDetailRedisCmd) Run() error {
	return RunRequest("GET", "/database/redis/v1/redis/{redisId}",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		nil)
}

type RedisDetailRedisClusterCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
}

func (c *RedisDetailRedisClusterCmd) Run() error {
	return RunRequest("GET", "/database/redis/v1/redis-cluster/{redisClusterId}",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		nil)
}

type RedisListRedisCmd struct {
	RedisName string `name:"redis-name" help:"Redis name"`
	Page      string `name:"page" help:"Request page number"`
	Size      string `name:"size" help:"Number of items in the Page"`
	Sort      string `name:"sort" help:"Sort condition"`
}

func (c *RedisListRedisCmd) Run() error {
	return RunRequest("GET", "/database/redis/v1/redis",
		map[string]string{},
		map[string]string{"redisName": c.RedisName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RedisListRedisClusterCmd struct {
	RedisName string `name:"redis-name" help:"Redis name"`
	Page      string `name:"page" help:"Request page number"`
	Size      string `name:"size" help:"Number of items in the Page"`
	Sort      string `name:"sort" help:"Sort condition"`
}

func (c *RedisListRedisClusterCmd) Run() error {
	return RunRequest("GET", "/database/redis/v1/redis-cluster",
		map[string]string{},
		map[string]string{"redisName": c.RedisName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RedisModifyRedisClusterFullBackupConfigCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisModifyRedisClusterFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/database/redis/v1/redis-cluster/{redisClusterId}/full-backups",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisModifyRedisFullBackupConfigCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisModifyRedisFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/database/redis/v1/redis/{redisId}/full-backups",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisResizeRedisBlockStoragesCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisResizeRedisBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/block-storages/resize",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisResizeRedisClusterBlockStoragesCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisResizeRedisClusterBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/block-storages/resize",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisResizeRedisClusterVirtualServersCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisResizeRedisClusterVirtualServersCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/virtual-servers/resize",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisResizeRedisVirtualServersCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisResizeRedisVirtualServersCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/virtual-servers/resize",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisRestartRedisCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisRestartRedisCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/restart",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisRestartRedisClusterCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisRestartRedisClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/restart",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisStartRedisCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisStartRedisCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/start",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisStartRedisClusterCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisStartRedisClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/start",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

type RedisStopRedisCmd struct {
	RedisId string `name:"redis-id" help:"Redis ID" required:""`
	Body    string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisStopRedisCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis/{redisId}/stop",
		map[string]string{"redisId": c.RedisId},
		map[string]string{},
		b)
}

type RedisStopRedisClusterCmd struct {
	RedisClusterId string `name:"redis-cluster-id" help:"Redis Cluster ID" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RedisStopRedisClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/redis/v1/redis-cluster/{redisClusterId}/stop",
		map[string]string{"redisClusterId": c.RedisClusterId},
		map[string]string{},
		b)
}

// RedisCmd groups all redis operations.
type RedisCmd struct {
	AttachRedisClusterSecurityGroup    RedisAttachRedisClusterSecurityGroupCmd    `cmd:"" name:"attach-redis-cluster-security-group" help:"Attach Security Group to Redis Cluster"`
	AttachRedisSecurityGroup           RedisAttachRedisSecurityGroupCmd           `cmd:"" name:"attach-redis-security-group" help:"Attach Security Group to Redis"`
	CreateRedis                        RedisCreateRedisCmd                        `cmd:"" name:"create-redis" help:"Create Redis"`
	CreateRedisCluster                 RedisCreateRedisClusterCmd                 `cmd:"" name:"create-redis-cluster" help:"Create Redis Cluster"`
	CreateRedisClusterFullBackupConfig RedisCreateRedisClusterFullBackupConfigCmd `cmd:"" name:"create-redis-cluster-full-backup-config" help:"Create Redis Cluster full backup"`
	CreateRedisFullBackupConfig        RedisCreateRedisFullBackupConfigCmd        `cmd:"" name:"create-redis-full-backup-config" help:"Create Redis full backup"`
	DeleteRedis                        RedisDeleteRedisCmd                        `cmd:"" name:"delete-redis" help:"Delete Redis"`
	DeleteRedisCluster                 RedisDeleteRedisClusterCmd                 `cmd:"" name:"delete-redis-cluster" help:"Delete Redis Cluster"`
	DeleteRedisClusterFullBackupConfig RedisDeleteRedisClusterFullBackupConfigCmd `cmd:"" name:"delete-redis-cluster-full-backup-config" help:"Delete Redis Cluster full backup"`
	DeleteRedisFullBackupConfig        RedisDeleteRedisFullBackupConfigCmd        `cmd:"" name:"delete-redis-full-backup-config" help:"Delete Redis full backup"`
	DetachRedisClusterSecurityGroup    RedisDetachRedisClusterSecurityGroupCmd    `cmd:"" name:"detach-redis-cluster-security-group" help:"Detach Security Group to Redis Cluster"`
	DetachRedisSecurityGroup           RedisDetachRedisSecurityGroupCmd           `cmd:"" name:"detach-redis-security-group" help:"Detach Security Group to Redis"`
	DetailRedis                        RedisDetailRedisCmd                        `cmd:"" name:"detail-redis" help:"Detail Redis"`
	DetailRedisCluster                 RedisDetailRedisClusterCmd                 `cmd:"" name:"detail-redis-cluster" help:"Detail Redis Cluster"`
	ListRedis                          RedisListRedisCmd                          `cmd:"" name:"list-redis" help:"List Redis"`
	ListRedisCluster                   RedisListRedisClusterCmd                   `cmd:"" name:"list-redis-cluster" help:"List Redis Cluster"`
	ModifyRedisClusterFullBackupConfig RedisModifyRedisClusterFullBackupConfigCmd `cmd:"" name:"modify-redis-cluster-full-backup-config" help:"Modify Redis Cluster full backup"`
	ModifyRedisFullBackupConfig        RedisModifyRedisFullBackupConfigCmd        `cmd:"" name:"modify-redis-full-backup-config" help:"Modify Redis full backup"`
	ResizeRedisBlockStorages           RedisResizeRedisBlockStoragesCmd           `cmd:"" name:"resize-redis-block-storages" help:"Resize Redis block storages"`
	ResizeRedisClusterBlockStorages    RedisResizeRedisClusterBlockStoragesCmd    `cmd:"" name:"resize-redis-cluster-block-storages" help:"Resize Redis Cluster block storages"`
	ResizeRedisClusterVirtualServers   RedisResizeRedisClusterVirtualServersCmd   `cmd:"" name:"resize-redis-cluster-virtual-servers" help:"Resize Redis Cluster virtual servers"`
	ResizeRedisVirtualServers          RedisResizeRedisVirtualServersCmd          `cmd:"" name:"resize-redis-virtual-servers" help:"Resize Redis virtual servers"`
	RestartRedis                       RedisRestartRedisCmd                       `cmd:"" name:"restart-redis" help:"Restart Redis"`
	RestartRedisCluster                RedisRestartRedisClusterCmd                `cmd:"" name:"restart-redis-cluster" help:"Restart Redis Cluster"`
	StartRedis                         RedisStartRedisCmd                         `cmd:"" name:"start-redis" help:"Start Redis"`
	StartRedisCluster                  RedisStartRedisClusterCmd                  `cmd:"" name:"start-redis-cluster" help:"Start Redis Cluster"`
	StopRedis                          RedisStopRedisCmd                          `cmd:"" name:"stop-redis" help:"Stop Redis"`
	StopRedisCluster                   RedisStopRedisClusterCmd                   `cmd:"" name:"stop-redis-cluster" help:"Stop Redis Cluster"`
}
