// Code generated by codegen. DO NOT EDIT.

package commands

type RequestDetailRequestCmd struct {
	RequestId string `name:"request-id" help:"Requestor ID" required:""`
}

func (c *RequestDetailRequestCmd) Run() error {
	return RunRequest("GET", "/request/v2/requests/{requestId}",
		map[string]string{"requestId": c.RequestId},
		map[string]string{},
		nil)
}

// RequestCmd groups all request operations.
type RequestCmd struct {
	DetailRequest RequestDetailRequestCmd `cmd:"" name:"detail-request" help:"Get Request details"`
}
