// Code generated by codegen. DO NOT EDIT.

package commands

type RoutingCreateDcRoutingRulesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Direct Connect Routing Tables" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RoutingCreateDcRoutingRulesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/direct-connect-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		b)
}

type RoutingCreateTgwRoutingRulesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Transit Gateway Routing Tables" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RoutingCreateTgwRoutingRulesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/transit-gateway-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		b)
}

type RoutingCreateVpcRoutingRulesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of VPC Routing Tables" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RoutingCreateVpcRoutingRulesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vpc-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		b)
}

type RoutingDeleteDcRoutingRulesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Direct Connect Routing Tables" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RoutingDeleteDcRoutingRulesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/direct-connect-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		b)
}

type RoutingDeleteTgwRoutingRulesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Transit Gateway Routing Tables" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RoutingDeleteTgwRoutingRulesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/transit-gateway-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		b)
}

type RoutingDeleteVpcRoutingRulesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of VPC Routing Tables" required:""`
	Body           string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *RoutingDeleteVpcRoutingRulesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("DELETE", "/vpc-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		b)
}

type RoutingDetailDcRoutingTablesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID" required:""`
}

func (c *RoutingDetailDcRoutingTablesCmd) Run() error {
	return RunRequest("GET", "/direct-connect-routing/v2/routing-tables/{routingTableId}",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		nil)
}

type RoutingDetailTgwRoutingTablesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID" required:""`
}

func (c *RoutingDetailTgwRoutingTablesCmd) Run() error {
	return RunRequest("GET", "/transit-gateway-routing/v2/routing-tables/{routingTableId}",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		nil)
}

type RoutingDetailVpcRoutingTablesCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID" required:""`
}

func (c *RoutingDetailVpcRoutingTablesCmd) Run() error {
	return RunRequest("GET", "/vpc-routing/v2/routing-tables/{routingTableId}",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		nil)
}

type RoutingListDcRoutingRulesCmd struct {
	RoutingTableId           string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Direct Connect Routing Tables" required:""`
	DestinationNetworkCidr   string `name:"destination-network-cidr" help:"Destination Network"`
	Editable                 string `name:"editable" help:"Editable"`
	RoutingRuleId            string `name:"routing-rule-id" help:"Routing Rule ID"`
	SourceServiceInterfaceId string `name:"source-service-interface-id" help:"Source Service Interface ID Source Service Interface ID is obtained through Get List of VPC Routing Rules Route"`
	Page                     string `name:"page" help:"Request page number"`
	Size                     string `name:"size" help:"Number of items in the Page"`
	Sort                     string `name:"sort" help:"Sort condition"`
}

func (c *RoutingListDcRoutingRulesCmd) Run() error {
	return RunRequest("GET", "/direct-connect-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{"destinationNetworkCidr": c.DestinationNetworkCidr, "editable": c.Editable, "routingRuleId": c.RoutingRuleId, "sourceServiceInterfaceId": c.SourceServiceInterfaceId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RoutingListDcRoutingRulesRouteCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Direct Connect Routing Tables" required:""`
}

func (c *RoutingListDcRoutingRulesRouteCmd) Run() error {
	return RunRequest("GET", "/direct-connect-routing/v2/routing-tables/{routingTableId}/routes",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		nil)
}

type RoutingListDcRoutingTablesCmd struct {
	DirectConnectConnectionId string `name:"direct-connect-connection-id" help:"Direct Connection ID Direct Connect Connection ID is obtained through Get List of VPC-Direct Connect Connections"`
	RoutingTableId            string `name:"routing-table-id" help:"Routing Table ID"`
	RoutingTableName          string `name:"routing-table-name" help:"Routing Table name"`
	CreatedBy                 string `name:"created-by" help:"creator"`
	Page                      string `name:"page" help:"Request page number"`
	Size                      string `name:"size" help:"Number of items in the Page"`
	Sort                      string `name:"sort" help:"Sort condition"`
}

func (c *RoutingListDcRoutingTablesCmd) Run() error {
	return RunRequest("GET", "/direct-connect-routing/v2/routing-tables",
		map[string]string{},
		map[string]string{"directConnectConnectionId": c.DirectConnectConnectionId, "routingTableId": c.RoutingTableId, "routingTableName": c.RoutingTableName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RoutingListTgwRoutingRulesCmd struct {
	RoutingTableId           string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Transit Gateway Routing Tables" required:""`
	DestinationNetworkCidr   string `name:"destination-network-cidr" help:"Destination Network"`
	Editable                 string `name:"editable" help:"Editable"`
	RoutingRuleId            string `name:"routing-rule-id" help:"Routing Rule ID"`
	SourceServiceInterfaceId string `name:"source-service-interface-id" help:"Source Service Interface ID Source Service Interface ID is obtained through Get List of VPC Routing Rules Route"`
	Page                     string `name:"page" help:"Request page number"`
	Size                     string `name:"size" help:"Number of items in the Page"`
	Sort                     string `name:"sort" help:"Sort condition"`
}

func (c *RoutingListTgwRoutingRulesCmd) Run() error {
	return RunRequest("GET", "/transit-gateway-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{"destinationNetworkCidr": c.DestinationNetworkCidr, "editable": c.Editable, "routingRuleId": c.RoutingRuleId, "sourceServiceInterfaceId": c.SourceServiceInterfaceId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RoutingListTgwRoutingRulesRouteCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of Transit Gateway Routing Tables" required:""`
}

func (c *RoutingListTgwRoutingRulesRouteCmd) Run() error {
	return RunRequest("GET", "/transit-gateway-routing/v2/routing-tables/{routingTableId}/routes",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		nil)
}

type RoutingListTgwRoutingTablesCmd struct {
	RoutingTableId             string `name:"routing-table-id" help:"Routing Table ID"`
	RoutingTableName           string `name:"routing-table-name" help:"Routing Table name"`
	TransitGatewayConnectionId string `name:"transit-gateway-connection-id" help:"Transit Gateway ID Transit Gateway Connection ID is obtained through Get List of VPC-Transit Gateway Connections"`
	CreatedBy                  string `name:"created-by" help:"creator"`
	Page                       string `name:"page" help:"Request page number"`
	Size                       string `name:"size" help:"Number of items in the Page"`
	Sort                       string `name:"sort" help:"Sort condition"`
}

func (c *RoutingListTgwRoutingTablesCmd) Run() error {
	return RunRequest("GET", "/transit-gateway-routing/v2/routing-tables",
		map[string]string{},
		map[string]string{"routingTableId": c.RoutingTableId, "routingTableName": c.RoutingTableName, "transitGatewayConnectionId": c.TransitGatewayConnectionId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RoutingListVpcRoutingRulesCmd struct {
	RoutingTableId           string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of VPC Routing Tables" required:""`
	DestinationNetworkCidr   string `name:"destination-network-cidr" help:"Destination Network"`
	Editable                 string `name:"editable" help:"Editable"`
	RoutingRuleId            string `name:"routing-rule-id" help:"Routing Rule ID"`
	SourceServiceInterfaceId string `name:"source-service-interface-id" help:"Source Service Interface ID Source Service Interface ID is obtained through Get List of VPC Routing Rules Route"`
	Page                     string `name:"page" help:"Request page number"`
	Size                     string `name:"size" help:"Number of items in the Page"`
	Sort                     string `name:"sort" help:"Sort condition"`
}

func (c *RoutingListVpcRoutingRulesCmd) Run() error {
	return RunRequest("GET", "/vpc-routing/v2/routing-tables/{routingTableId}/routing-rules",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{"destinationNetworkCidr": c.DestinationNetworkCidr, "editable": c.Editable, "routingRuleId": c.RoutingRuleId, "sourceServiceInterfaceId": c.SourceServiceInterfaceId, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type RoutingListVpcRoutingRulesRouteCmd struct {
	RoutingTableId string `name:"routing-table-id" help:"Routing Table ID Routing Table ID is obtained through Get List of VPC Routing Tables" required:""`
}

func (c *RoutingListVpcRoutingRulesRouteCmd) Run() error {
	return RunRequest("GET", "/vpc-routing/v2/routing-tables/{routingTableId}/routes",
		map[string]string{"routingTableId": c.RoutingTableId},
		map[string]string{},
		nil)
}

type RoutingListVpcRoutingTablesCmd struct {
	RoutingTableId   string `name:"routing-table-id" help:"Routing Table ID"`
	RoutingTableName string `name:"routing-table-name" help:"Routing Table name"`
	VpcId            string `name:"vpc-id" help:"VPC ID vpcId is obtained through Get List of VPCs"`
	CreatedBy        string `name:"created-by" help:"creator"`
	Page             string `name:"page" help:"Request page number"`
	Size             string `name:"size" help:"Number of items in the Page"`
	Sort             string `name:"sort" help:"Sort condition"`
}

func (c *RoutingListVpcRoutingTablesCmd) Run() error {
	return RunRequest("GET", "/vpc-routing/v2/routing-tables",
		map[string]string{},
		map[string]string{"routingTableId": c.RoutingTableId, "routingTableName": c.RoutingTableName, "vpcId": c.VpcId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

// RoutingCmd groups all routing operations.
type RoutingCmd struct {
	CreateDcRoutingRules     RoutingCreateDcRoutingRulesCmd     `cmd:"" name:"create-dc-routing-rules" help:"Create Direct Connect Routing Rules"`
	CreateTgwRoutingRules    RoutingCreateTgwRoutingRulesCmd    `cmd:"" name:"create-tgw-routing-rules" help:"Create Transit Gateway Routing Rules"`
	CreateVpcRoutingRules    RoutingCreateVpcRoutingRulesCmd    `cmd:"" name:"create-vpc-routing-rules" help:"Create VPC Routing Rules"`
	DeleteDcRoutingRules     RoutingDeleteDcRoutingRulesCmd     `cmd:"" name:"delete-dc-routing-rules" help:"Delete Direct Connect Routing Rules"`
	DeleteTgwRoutingRules    RoutingDeleteTgwRoutingRulesCmd    `cmd:"" name:"delete-tgw-routing-rules" help:"Delete Transit Gateway Routing Rules"`
	DeleteVpcRoutingRules    RoutingDeleteVpcRoutingRulesCmd    `cmd:"" name:"delete-vpc-routing-rules" help:"Delete VPC Routing Rules"`
	DetailDcRoutingTables    RoutingDetailDcRoutingTablesCmd    `cmd:"" name:"detail-dc-routing-tables" help:"Get Direct Connect Routing Detail"`
	DetailTgwRoutingTables   RoutingDetailTgwRoutingTablesCmd   `cmd:"" name:"detail-tgw-routing-tables" help:"Get Transit Gateway Routing Detail"`
	DetailVpcRoutingTables   RoutingDetailVpcRoutingTablesCmd   `cmd:"" name:"detail-vpc-routing-tables" help:"Get VPC Routing Detail"`
	ListDcRoutingRules       RoutingListDcRoutingRulesCmd       `cmd:"" name:"list-dc-routing-rules" help:"Get List of Direct Connect Routing Rules"`
	ListDcRoutingRulesRoute  RoutingListDcRoutingRulesRouteCmd  `cmd:"" name:"list-dc-routing-rules-route" help:"Get List of Direct Connect Routing Rules Route"`
	ListDcRoutingTables      RoutingListDcRoutingTablesCmd      `cmd:"" name:"list-dc-routing-tables" help:"Get List of Direct Connect Routing Tables"`
	ListTgwRoutingRules      RoutingListTgwRoutingRulesCmd      `cmd:"" name:"list-tgw-routing-rules" help:"Get List of Transit Gateway Routing Rules"`
	ListTgwRoutingRulesRoute RoutingListTgwRoutingRulesRouteCmd `cmd:"" name:"list-tgw-routing-rules-route" help:"Get List of Transit Gateway Routing Rules Route"`
	ListTgwRoutingTables     RoutingListTgwRoutingTablesCmd     `cmd:"" name:"list-tgw-routing-tables" help:"Get List of Transit Gateway Routing Tables"`
	ListVpcRoutingRules      RoutingListVpcRoutingRulesCmd      `cmd:"" name:"list-vpc-routing-rules" help:"Get List of VPC Routing Rules"`
	ListVpcRoutingRulesRoute RoutingListVpcRoutingRulesRouteCmd `cmd:"" name:"list-vpc-routing-rules-route" help:"Get List of VPC Routing Rules Route"`
	ListVpcRoutingTables     RoutingListVpcRoutingTablesCmd     `cmd:"" name:"list-vpc-routing-tables" help:"Get List of VPC Routing Tables"`
}
