// Code generated by codegen. DO NOT EDIT.

package commands

type SemanticTextualSimilarityAnalyzeStsCmd struct {
	StsId string `name:"sts-id" help:"Semantic Textual Similarity ID Semantic Textual Similarity ID is obtained through Get list of Semantic Textual Similarity" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SemanticTextualSimilarityAnalyzeStsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/text-api/v1/semantic-textual-similarity/{stsId}/analyze-semantic-textual-similarity",
		map[string]string{"stsId": c.StsId},
		map[string]string{},
		b)
}

type SemanticTextualSimilarityCreateStsCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SemanticTextualSimilarityCreateStsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/text-api/v1/semantic-textual-similarity",
		map[string]string{},
		map[string]string{},
		b)
}

type SemanticTextualSimilarityDeleteStsCmd struct {
	StsId string `name:"sts-id" help:"Semantic Textual Similarity ID Semantic Textual Similarity ID is obtained through Get list of Semantic Textual Similarity" required:""`
}

func (c *SemanticTextualSimilarityDeleteStsCmd) Run() error {
	return RunRequest("DELETE", "/text-api/v1/semantic-textual-similarity/{stsId}",
		map[string]string{"stsId": c.StsId},
		map[string]string{},
		nil)
}

type SemanticTextualSimilarityDetailStsCmd struct {
	StsId string `name:"sts-id" help:"Semantic Textual Similarity ID Semantic Textual Similarity ID is obtained through Get list of Semantic Textual Similarity" required:""`
}

func (c *SemanticTextualSimilarityDetailStsCmd) Run() error {
	return RunRequest("GET", "/text-api/v1/semantic-textual-similarity/{stsId}",
		map[string]string{"stsId": c.StsId},
		map[string]string{},
		nil)
}

type SemanticTextualSimilarityListStsCmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *SemanticTextualSimilarityListStsCmd) Run() error {
	return RunRequest("GET", "/text-api/v1/semantic-textual-similarity",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type SemanticTextualSimilarityUpdateDescStsCmd struct {
	StsId string `name:"sts-id" help:"Semantic Textual Similarity ID Semantic Textual Similarity ID is obtained through Get list of Semantic Textual Similarity" required:""`
	Body  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SemanticTextualSimilarityUpdateDescStsCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/text-api/v1/semantic-textual-similarity/{stsId}/description",
		map[string]string{"stsId": c.StsId},
		map[string]string{},
		b)
}

// SemanticTextualSimilarityCmd groups all semantic-textual-similarity operations.
type SemanticTextualSimilarityCmd struct {
	AnalyzeSts    SemanticTextualSimilarityAnalyzeStsCmd    `cmd:"" name:"analyze-sts" help:"Analyze Semantic Textual Similarity"`
	CreateSts     SemanticTextualSimilarityCreateStsCmd     `cmd:"" name:"create-sts" help:"Create Semantic Textual Similarity"`
	DeleteSts     SemanticTextualSimilarityDeleteStsCmd     `cmd:"" name:"delete-sts" help:"Delete Semantic Textual Similarity"`
	DetailSts     SemanticTextualSimilarityDetailStsCmd     `cmd:"" name:"detail-sts" help:"Get Semantic Textual Similarity details"`
	ListSts       SemanticTextualSimilarityListStsCmd       `cmd:"" name:"list-sts" help:"Get list of Semantic Textual Similarity"`
	UpdateDescSts SemanticTextualSimilarityUpdateDescStsCmd `cmd:"" name:"update-desc-sts" help:"Update Semantic Textual Similarity description"`
}
