// Code generated by codegen. DO NOT EDIT.

package commands

type SqlserverAttachSqlserverClusterSecurityGroupCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverAttachSqlserverClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/security-groups/attach",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverCreateSqlserverClusterCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverCreateSqlserverClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver",
		map[string]string{},
		map[string]string{},
		b)
}

type SqlserverCreateSqlserverClusterFullBackupConfigCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverCreateSqlserverClusterFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/full-backups",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverDeleteSqlserverClusterCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
}

func (c *SqlserverDeleteSqlserverClusterCmd) Run() error {
	return RunRequest("DELETE", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		nil)
}

type SqlserverDeleteSqlserverClusterFullBackupConfigCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
}

func (c *SqlserverDeleteSqlserverClusterFullBackupConfigCmd) Run() error {
	return RunRequest("DELETE", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/full-backups",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		nil)
}

type SqlserverDetachSqlserverClusterSecurityGroupCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverDetachSqlserverClusterSecurityGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/security-groups/detach",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverDetailSqlserverClusterCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
}

func (c *SqlserverDetailSqlserverClusterCmd) Run() error {
	return RunRequest("GET", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		nil)
}

type SqlserverListSqlserverClustersCmd struct {
	SqlserverClusterName string `name:"sqlserver-cluster-name" help:"MS SQL Server cluster name"`
	Page                 string `name:"page" help:"Request page number"`
	Size                 string `name:"size" help:"Number of items in the Page"`
	Sort                 string `name:"sort" help:"Sort condition"`
}

func (c *SqlserverListSqlserverClustersCmd) Run() error {
	return RunRequest("GET", "/database/sqlserver/v1/sqlserver",
		map[string]string{},
		map[string]string{"sqlserverClusterName": c.SqlserverClusterName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type SqlserverModifySqlserverClusterFullBackupConfigCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverModifySqlserverClusterFullBackupConfigCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/full-backups",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverResizeSqlserverClusterBlockStoragesCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverResizeSqlserverClusterBlockStoragesCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/block-storages/resize",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverResizeSqlserverClusterVirtualServersCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverResizeSqlserverClusterVirtualServersCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/virtual-servers/resize",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverRestartSqlserverClusterCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverRestartSqlserverClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/restart",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverStartSqlserverClusterCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverStartSqlserverClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/start",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

type SqlserverStopSqlserverClusterCmd struct {
	SqlserverClusterId string `name:"sqlserver-cluster-id" help:"MS SQL Server cluster ID" required:""`
	Body               string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SqlserverStopSqlserverClusterCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/database/sqlserver/v1/sqlserver/{sqlserverClusterId}/stop",
		map[string]string{"sqlserverClusterId": c.SqlserverClusterId},
		map[string]string{},
		b)
}

// SqlserverCmd groups all sqlserver operations.
type SqlserverCmd struct {
	AttachSqlserverClusterSecurityGroup    SqlserverAttachSqlserverClusterSecurityGroupCmd    `cmd:"" name:"attach-sqlserver-cluster-security-group" help:"Attach Security Group to MS SQL Server cluster"`
	CreateSqlserverCluster                 SqlserverCreateSqlserverClusterCmd                 `cmd:"" name:"create-sqlserver-cluster" help:"Create MS SQL Server cluster"`
	CreateSqlserverClusterFullBackupConfig SqlserverCreateSqlserverClusterFullBackupConfigCmd `cmd:"" name:"create-sqlserver-cluster-full-backup-config" help:"Create MS SQL Server cluster full backup config"`
	DeleteSqlserverCluster                 SqlserverDeleteSqlserverClusterCmd                 `cmd:"" name:"delete-sqlserver-cluster" help:"Delete MS SQL Server cluster"`
	DeleteSqlserverClusterFullBackupConfig SqlserverDeleteSqlserverClusterFullBackupConfigCmd `cmd:"" name:"delete-sqlserver-cluster-full-backup-config" help:"Delete MS SQL Server cluster full backup config"`
	DetachSqlserverClusterSecurityGroup    SqlserverDetachSqlserverClusterSecurityGroupCmd    `cmd:"" name:"detach-sqlserver-cluster-security-group" help:"Detach Security Group to MS SQL Server cluster"`
	DetailSqlserverCluster                 SqlserverDetailSqlserverClusterCmd                 `cmd:"" name:"detail-sqlserver-cluster" help:"Detail MS SQL Server cluster"`
	ListSqlserverClusters                  SqlserverListSqlserverClustersCmd                  `cmd:"" name:"list-sqlserver-clusters" help:"List MS SQL Server cluster"`
	ModifySqlserverClusterFullBackupConfig SqlserverModifySqlserverClusterFullBackupConfigCmd `cmd:"" name:"modify-sqlserver-cluster-full-backup-config" help:"Modify MS SQL Server cluster full backup config"`
	ResizeSqlserverClusterBlockStorages    SqlserverResizeSqlserverClusterBlockStoragesCmd    `cmd:"" name:"resize-sqlserver-cluster-block-storages" help:"Resize MS SQL Server cluster block storages"`
	ResizeSqlserverClusterVirtualServers   SqlserverResizeSqlserverClusterVirtualServersCmd   `cmd:"" name:"resize-sqlserver-cluster-virtual-servers" help:"Resize MS SQL Server cluster virtual servers"`
	RestartSqlserverCluster                SqlserverRestartSqlserverClusterCmd                `cmd:"" name:"restart-sqlserver-cluster" help:"Restart MS SQL Server cluster"`
	StartSqlserverCluster                  SqlserverStartSqlserverClusterCmd                  `cmd:"" name:"start-sqlserver-cluster" help:"Start MS SQL Server cluster"`
	StopSqlserverCluster                   SqlserverStopSqlserverClusterCmd                   `cmd:"" name:"stop-sqlserver-cluster" help:"Stop MS SQL Server cluster"`
}
