// Code generated by codegen. DO NOT EDIT.

package commands

type SummaryCreateSummaryCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SummaryCreateSummaryCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/text-api/v1/summaries",
		map[string]string{},
		map[string]string{},
		b)
}

type SummaryDeleteSummaryCmd struct {
	SummaryId string `name:"summary-id" help:"Summary ID Summary ID is obtained through Get list of Summary" required:""`
}

func (c *SummaryDeleteSummaryCmd) Run() error {
	return RunRequest("DELETE", "/text-api/v1/summaries/{summaryId}",
		map[string]string{"summaryId": c.SummaryId},
		map[string]string{},
		nil)
}

type SummaryDetailSummaryCmd struct {
	SummaryId string `name:"summary-id" help:"Summary ID Summary ID is obtained through Get list of Summary" required:""`
}

func (c *SummaryDetailSummaryCmd) Run() error {
	return RunRequest("GET", "/text-api/v1/summaries/{summaryId}",
		map[string]string{"summaryId": c.SummaryId},
		map[string]string{},
		nil)
}

type SummaryListSummariesCmd struct {
	Page string `name:"page" help:"Request page number"`
	Size string `name:"size" help:"Number of items in the Page"`
	Sort string `name:"sort" help:"Sort condition"`
}

func (c *SummaryListSummariesCmd) Run() error {
	return RunRequest("GET", "/text-api/v1/summaries",
		map[string]string{},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type SummarySummarizeTextCmd struct {
	SummaryId string `name:"summary-id" help:"Summary ID Summary ID is obtained through Get list of Summary" required:""`
	Body      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SummarySummarizeTextCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/text-api/v1/summaries/{summaryId}/summarize",
		map[string]string{"summaryId": c.SummaryId},
		map[string]string{},
		b)
}

type SummaryUpdateSummaryCmd struct {
	SummaryId string `name:"summary-id" help:"Summary ID Summary ID is obtained through Get list of Summary" required:""`
	Body      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *SummaryUpdateSummaryCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/text-api/v1/summaries/{summaryId}/description",
		map[string]string{"summaryId": c.SummaryId},
		map[string]string{},
		b)
}

// SummaryCmd groups all summary operations.
type SummaryCmd struct {
	CreateSummary SummaryCreateSummaryCmd `cmd:"" name:"create-summary" help:"Create Summary"`
	DeleteSummary SummaryDeleteSummaryCmd `cmd:"" name:"delete-summary" help:"Delete Summary"`
	DetailSummary SummaryDetailSummaryCmd `cmd:"" name:"detail-summary" help:"Get Summary details"`
	ListSummaries SummaryListSummariesCmd `cmd:"" name:"list-summaries" help:"Get list of Summary"`
	SummarizeText SummarySummarizeTextCmd `cmd:"" name:"summarize-text" help:"Summarize Text"`
	UpdateSummary SummaryUpdateSummaryCmd `cmd:"" name:"update-summary" help:"Update Summary description"`
}
