// Code generated by codegen. DO NOT EDIT.

package commands

type TiberoDetailTiberoClusterCmd struct {
	TiberoClusterId string `name:"tibero-cluster-id" help:"TIBERO cluster ID" required:""`
}

func (c *TiberoDetailTiberoClusterCmd) Run() error {
	return RunRequest("GET", "/database/tibero/v1/tibero/{tiberoClusterId}",
		map[string]string{"tiberoClusterId": c.TiberoClusterId},
		map[string]string{},
		nil)
}

type TiberoListTiberoClustersCmd struct {
	TiberoClusterName string `name:"tibero-cluster-name" help:"TIBERO cluster name"`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *TiberoListTiberoClustersCmd) Run() error {
	return RunRequest("GET", "/database/tibero/v1/tibero",
		map[string]string{},
		map[string]string{"tiberoClusterName": c.TiberoClusterName, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

// TiberoCmd groups all tibero operations.
type TiberoCmd struct {
	DetailTiberoCluster TiberoDetailTiberoClusterCmd `cmd:"" name:"detail-tibero-cluster" help:"Detail TIBERO cluster"`
	ListTiberoClusters  TiberoListTiberoClustersCmd  `cmd:"" name:"list-tibero-clusters" help:"List TIBERO cluster"`
}
