// Code generated by codegen. DO NOT EDIT.

package commands

type VirtualServerDrCreateVirtualServerDrGroupCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrCreateVirtualServerDrGroupCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-group/v1/dr-groups",
		map[string]string{},
		map[string]string{},
		b)
}

type VirtualServerDrCreateVirtualServerDrGroupPlanAssocCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrCreateVirtualServerDrGroupPlanAssocCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-group-plan-assoc/v1/dr-group-plan-assocs",
		map[string]string{},
		map[string]string{},
		b)
}

type VirtualServerDrCreateVirtualServerDrNetworkPairingCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrCreateVirtualServerDrNetworkPairingCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-network-pairing/v1/dr-network-pairings",
		map[string]string{},
		map[string]string{},
		b)
}

type VirtualServerDrCreateVirtualServerDrPlanCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrCreateVirtualServerDrPlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-plan/v1/dr-plans",
		map[string]string{},
		map[string]string{},
		b)
}

type VirtualServerDrCreateVirtualServerDrReplicationCmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrCreateVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-replication/v1/dr-replications",
		map[string]string{},
		map[string]string{},
		b)
}

type VirtualServerDrDeleteVirtualServerDrGroupCmd struct {
	VirtualServerDrGroupId string `name:"virtual-server-dr-group-id" help:"Virtual Server DR Group ID" required:""`
}

func (c *VirtualServerDrDeleteVirtualServerDrGroupCmd) Run() error {
	return RunRequest("DELETE", "/virtual-server-dr/dr-group/v1/dr-groups/{virtualServerDrGroupId}",
		map[string]string{"virtualServerDrGroupId": c.VirtualServerDrGroupId},
		map[string]string{},
		nil)
}

type VirtualServerDrDeleteVirtualServerDrGroupPlanAssocCmd struct {
	VirtualServerDrGroupId string `name:"virtual-server-dr-group-id" help:"Virtual Server DR Group ID" required:""`
	VirtualServerDrPlanId  string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
}

func (c *VirtualServerDrDeleteVirtualServerDrGroupPlanAssocCmd) Run() error {
	return RunRequest("DELETE", "/virtual-server-dr/dr-group-plan-assoc/v1/dr-group-plan-assocs/dr-groups/{virtualServerDrGroupId}/dr-plans/{virtualServerDrPlanId}",
		map[string]string{"virtualServerDrGroupId": c.VirtualServerDrGroupId, "virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		nil)
}

type VirtualServerDrDeleteVirtualServerDrPlanCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
}

func (c *VirtualServerDrDeleteVirtualServerDrPlanCmd) Run() error {
	return RunRequest("DELETE", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		nil)
}

type VirtualServerDrDeleteVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
}

func (c *VirtualServerDrDeleteVirtualServerDrReplicationCmd) Run() error {
	return RunRequest("DELETE", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		nil)
}

type VirtualServerDrDetailVirtualServerDrGroupCmd struct {
	VirtualServerDrGroupId string `name:"virtual-server-dr-group-id" help:"Virtual Server DR Group ID" required:""`
}

func (c *VirtualServerDrDetailVirtualServerDrGroupCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-group/v1/dr-groups/{virtualServerDrGroupId}",
		map[string]string{"virtualServerDrGroupId": c.VirtualServerDrGroupId},
		map[string]string{},
		nil)
}

type VirtualServerDrDetailVirtualServerDrNetworkPairingCmd struct {
	VirtualServerDrNetworkPairingId string `name:"virtual-server-dr-network-pairing-id" help:"" required:""`
}

func (c *VirtualServerDrDetailVirtualServerDrNetworkPairingCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-network-pairing/v1/dr-network-pairings/{virtualServerDrNetworkPairingId}",
		map[string]string{"virtualServerDrNetworkPairingId": c.VirtualServerDrNetworkPairingId},
		map[string]string{},
		nil)
}

type VirtualServerDrDetailVirtualServerDrPlanCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"" required:""`
}

func (c *VirtualServerDrDetailVirtualServerDrPlanCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		nil)
}

type VirtualServerDrDetailVirtualServerDrPlanHistoryCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
}

func (c *VirtualServerDrDetailVirtualServerDrPlanHistoryCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}/history",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		nil)
}

type VirtualServerDrDetailVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
}

func (c *VirtualServerDrDetailVirtualServerDrReplicationCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		nil)
}

type VirtualServerDrListVirtualServerDrGroupPlanAssocCmd struct {
	VirtualServerDrGroupId string `name:"virtual-server-dr-group-id" help:"Virtual Server DR Group ID"`
	VirtualServerDrPlanId  string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID"`
	CreatedBy              string `name:"created-by" help:"Creator User ID"`
	Page                   string `name:"page" help:"Request page number"`
	Size                   string `name:"size" help:"Number of items in the Page"`
	Sort                   string `name:"sort" help:"Sort condition"`
}

func (c *VirtualServerDrListVirtualServerDrGroupPlanAssocCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-group-plan-assoc/v1/dr-group-plan-assocs",
		map[string]string{},
		map[string]string{"virtualServerDrGroupId": c.VirtualServerDrGroupId, "virtualServerDrPlanId": c.VirtualServerDrPlanId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VirtualServerDrListVirtualServerDrGroupsCmd struct {
	ServiceZoneId                 string `name:"service-zone-id" help:"Zone ID serviceZoneId is obtained through View Project Details"`
	TargetServiceZoneId           string `name:"target-service-zone-id" help:"Target Zone ID serviceZoneId is obtained through View Project Details"`
	VirtualServerDrDirectionId    string `name:"virtual-server-dr-direction-id" help:"Virtual Server DR Direction ID"`
	VirtualServerDrGroupName      string `name:"virtual-server-dr-group-name" help:"Virtual Server DR Group name"`
	VirtualServerDrGroupStateList string `name:"virtual-server-dr-group-state-list" help:""`
	VpcId                         string `name:"vpc-id" help:"VPC ID"`
	CreatedBy                     string `name:"created-by" help:"Creator User ID"`
	Page                          string `name:"page" help:"Request page number"`
	Size                          string `name:"size" help:"Number of items in the Page"`
	Sort                          string `name:"sort" help:"Sort condition"`
}

func (c *VirtualServerDrListVirtualServerDrGroupsCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-group/v1/dr-groups",
		map[string]string{},
		map[string]string{"serviceZoneId": c.ServiceZoneId, "targetServiceZoneId": c.TargetServiceZoneId, "virtualServerDrDirectionId": c.VirtualServerDrDirectionId, "virtualServerDrGroupName": c.VirtualServerDrGroupName, "virtualServerDrGroupStateList": c.VirtualServerDrGroupStateList, "vpcId": c.VpcId, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VirtualServerDrListVirtualServerDrNetworkPairingCmd struct {
	SourceSubnetId                         string `name:"source-subnet-id" help:"Source Subnet ID"`
	SourceVpcId                            string `name:"source-vpc-id" help:"Source VPC ID"`
	TargetSubnetId                         string `name:"target-subnet-id" help:"Target Subnet ID"`
	TargetVpcId                            string `name:"target-vpc-id" help:"Target VPC ID"`
	VirtualServerDrDirectionId             string `name:"virtual-server-dr-direction-id" help:"Virtual Server DR Direction ID"`
	VirtualServerDrNetworkPairingStateList string `name:"virtual-server-dr-network-pairing-state-list" help:""`
	CreatedBy                              string `name:"created-by" help:"Creator User ID"`
	Page                                   string `name:"page" help:"Request page number"`
	Size                                   string `name:"size" help:"Number of items in the Page"`
	Sort                                   string `name:"sort" help:"Sort condition"`
}

func (c *VirtualServerDrListVirtualServerDrNetworkPairingCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-network-pairing/v1/dr-network-pairings",
		map[string]string{},
		map[string]string{"sourceSubnetId": c.SourceSubnetId, "sourceVpcId": c.SourceVpcId, "targetSubnetId": c.TargetSubnetId, "targetVpcId": c.TargetVpcId, "virtualServerDrDirectionId": c.VirtualServerDrDirectionId, "virtualServerDrNetworkPairingStateList": c.VirtualServerDrNetworkPairingStateList, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VirtualServerDrListVirtualServerDrPlanCmd struct {
	ServiceZoneId                string `name:"service-zone-id" help:"Zone ID"`
	VirtualServerDrDirectionId   string `name:"virtual-server-dr-direction-id" help:"Virtual Server DR Direction ID"`
	VirtualServerDrPlanName      string `name:"virtual-server-dr-plan-name" help:"Virtual Server DR Plan Name"`
	VirtualServerDrPlanStateList string `name:"virtual-server-dr-plan-state-list" help:"Virtual Server DR Plan State List"`
	CreatedBy                    string `name:"created-by" help:"Creator User ID"`
	Page                         string `name:"page" help:"Request page number"`
	Size                         string `name:"size" help:"Number of items in the Page"`
	Sort                         string `name:"sort" help:"Sort condition"`
}

func (c *VirtualServerDrListVirtualServerDrPlanCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-plan/v1/dr-plans",
		map[string]string{},
		map[string]string{"serviceZoneId": c.ServiceZoneId, "virtualServerDrDirectionId": c.VirtualServerDrDirectionId, "virtualServerDrPlanName": c.VirtualServerDrPlanName, "virtualServerDrPlanStateList": c.VirtualServerDrPlanStateList, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VirtualServerDrListVirtualServerDrReplicationSnapshotsCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"" required:""`
	Page              string `name:"page" help:"Request page number"`
	Size              string `name:"size" help:"Number of items in the Page"`
	Sort              string `name:"sort" help:"Sort condition"`
}

func (c *VirtualServerDrListVirtualServerDrReplicationSnapshotsCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/snapshots",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{"page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VirtualServerDrListVirtualServerDrReplicationsCmd struct {
	VirtualServerDrGroupName string `name:"virtual-server-dr-group-name" help:"Virtual Server DR Group name"`
	VirtualServerDrStateList string `name:"virtual-server-dr-state-list" help:"Virtual Server DR State List"`
	VirtualServerName        string `name:"virtual-server-name" help:"Virtual Server name"`
	CreatedBy                string `name:"created-by" help:"Creator User ID"`
	Page                     string `name:"page" help:"Request page number"`
	Size                     string `name:"size" help:"Number of items in the Page"`
	Sort                     string `name:"sort" help:"Sort condition"`
}

func (c *VirtualServerDrListVirtualServerDrReplicationsCmd) Run() error {
	return RunRequest("GET", "/virtual-server-dr/dr-replication/v1/dr-replications",
		map[string]string{},
		map[string]string{"virtualServerDrGroupName": c.VirtualServerDrGroupName, "virtualServerDrStateList": c.VirtualServerDrStateList, "virtualServerName": c.VirtualServerName, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VirtualServerDrRecoverCompleteVirtualServerDrPlanCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
	Body                  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrRecoverCompleteVirtualServerDrPlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}/recover-complete",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		b)
}

type VirtualServerDrRecoverTestCleanUpVirtualServerDrPlanCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
	Body                  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrRecoverTestCleanUpVirtualServerDrPlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}/recover-test-cleanup",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		b)
}

type VirtualServerDrRecoverTestVirtualServerDrPlanCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
	Body                  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrRecoverTestVirtualServerDrPlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}/recover-test",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		b)
}

type VirtualServerDrRecoverVirtualServerDrPlanCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
	Body                  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrRecoverVirtualServerDrPlanCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}/recover",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		b)
}

type VirtualServerDrRestoreVirtualServerDrReplicationSnapshotCmd struct {
	VirtualServerDrId         string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	VirtualServerDrSnapshotId string `name:"virtual-server-dr-snapshot-id" help:"Virtual Server DR Snapshot ID" required:""`
	Body                      string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrRestoreVirtualServerDrReplicationSnapshotCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/snapshots/{virtualServerDrSnapshotId}/restore",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId, "virtualServerDrSnapshotId": c.VirtualServerDrSnapshotId},
		map[string]string{},
		b)
}

type VirtualServerDrSyncStartVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrSyncStartVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/sync-start",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		b)
}

type VirtualServerDrSyncStopVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrSyncStopVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/sync-stop",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		b)
}

type VirtualServerDrUpdateDrGroupVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrUpdateDrGroupVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/dr-group",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		b)
}

type VirtualServerDrUpdatePriorityVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrUpdatePriorityVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/priority",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		b)
}

type VirtualServerDrUpdateSnapshotVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrUpdateSnapshotVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/snapshot",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		b)
}

type VirtualServerDrUpdateSyncPeriodVirtualServerDrReplicationCmd struct {
	VirtualServerDrId string `name:"virtual-server-dr-id" help:"Virtual Server DR ID" required:""`
	Body              string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrUpdateSyncPeriodVirtualServerDrReplicationCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/virtual-server-dr/dr-replication/v1/dr-replications/{virtualServerDrId}/sync-period",
		map[string]string{"virtualServerDrId": c.VirtualServerDrId},
		map[string]string{},
		b)
}

type VirtualServerDrUpdateVirtualServerDrGroupDescriptionCmd struct {
	VirtualServerDrGroupId string `name:"virtual-server-dr-group-id" help:"Virtual Server DR Group ID" required:""`
	Body                   string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrUpdateVirtualServerDrGroupDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/virtual-server-dr/dr-group/v1/dr-groups/{virtualServerDrGroupId}/description",
		map[string]string{"virtualServerDrGroupId": c.VirtualServerDrGroupId},
		map[string]string{},
		b)
}

type VirtualServerDrUpdateVirtualServerDrPlanDescriptionCmd struct {
	VirtualServerDrPlanId string `name:"virtual-server-dr-plan-id" help:"Virtual Server DR Plan ID" required:""`
	Body                  string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VirtualServerDrUpdateVirtualServerDrPlanDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/virtual-server-dr/dr-plan/v1/dr-plans/{virtualServerDrPlanId}/description",
		map[string]string{"virtualServerDrPlanId": c.VirtualServerDrPlanId},
		map[string]string{},
		b)
}

// VirtualServerDrCmd groups all virtual-server-dr operations.
type VirtualServerDrCmd struct {
	CreateVirtualServerDrGroup                 VirtualServerDrCreateVirtualServerDrGroupCmd                 `cmd:"" name:"create-virtual-server-dr-group" help:"Create Virtual Server DR Group"`
	CreateVirtualServerDrGroupPlanAssoc        VirtualServerDrCreateVirtualServerDrGroupPlanAssocCmd        `cmd:"" name:"create-virtual-server-dr-group-plan-assoc" help:"Create Virtual Server DR Group Plan Assoc"`
	CreateVirtualServerDrNetworkPairing        VirtualServerDrCreateVirtualServerDrNetworkPairingCmd        `cmd:"" name:"create-virtual-server-dr-network-pairing" help:"Create Virtual Server DR Network Pairing"`
	CreateVirtualServerDrPlan                  VirtualServerDrCreateVirtualServerDrPlanCmd                  `cmd:"" name:"create-virtual-server-dr-plan" help:"Create Virtual Server DR Plan"`
	CreateVirtualServerDrReplication           VirtualServerDrCreateVirtualServerDrReplicationCmd           `cmd:"" name:"create-virtual-server-dr-replication" help:"Create Virtual Server DR Replication"`
	DeleteVirtualServerDrGroup                 VirtualServerDrDeleteVirtualServerDrGroupCmd                 `cmd:"" name:"delete-virtual-server-dr-group" help:"Delete Virtual Server DR Group"`
	DeleteVirtualServerDrGroupPlanAssoc        VirtualServerDrDeleteVirtualServerDrGroupPlanAssocCmd        `cmd:"" name:"delete-virtual-server-dr-group-plan-assoc" help:"Delete Virtual Server DR Group Plan Assoc"`
	DeleteVirtualServerDrPlan                  VirtualServerDrDeleteVirtualServerDrPlanCmd                  `cmd:"" name:"delete-virtual-server-dr-plan" help:"Delete Virtual Server DR Plan"`
	DeleteVirtualServerDrReplication           VirtualServerDrDeleteVirtualServerDrReplicationCmd           `cmd:"" name:"delete-virtual-server-dr-replication" help:"Delete Virtual Server DR Replication"`
	DetailVirtualServerDrGroup                 VirtualServerDrDetailVirtualServerDrGroupCmd                 `cmd:"" name:"detail-virtual-server-dr-group" help:"Get Detail of Virtual Server DR Group"`
	DetailVirtualServerDrNetworkPairing        VirtualServerDrDetailVirtualServerDrNetworkPairingCmd        `cmd:"" name:"detail-virtual-server-dr-network-pairing" help:"Get Detail Of Virtual Server DR Network Pairing"`
	DetailVirtualServerDrPlan                  VirtualServerDrDetailVirtualServerDrPlanCmd                  `cmd:"" name:"detail-virtual-server-dr-plan" help:"Get Detail of Virtual Server DR Plan"`
	DetailVirtualServerDrPlanHistory           VirtualServerDrDetailVirtualServerDrPlanHistoryCmd           `cmd:"" name:"detail-virtual-server-dr-plan-history" help:"Get Detail of Virtual Server DR Plan History"`
	DetailVirtualServerDrReplication           VirtualServerDrDetailVirtualServerDrReplicationCmd           `cmd:"" name:"detail-virtual-server-dr-replication" help:"Get Detail of Virtual Server DR Replication"`
	ListVirtualServerDrGroupPlanAssoc          VirtualServerDrListVirtualServerDrGroupPlanAssocCmd          `cmd:"" name:"list-virtual-server-dr-group-plan-assoc" help:"Get List Of Virtual Server DR Group Plan Assoc"`
	ListVirtualServerDrGroups                  VirtualServerDrListVirtualServerDrGroupsCmd                  `cmd:"" name:"list-virtual-server-dr-groups" help:"Get List of Virtual Server DR Group in Project"`
	ListVirtualServerDrNetworkPairing          VirtualServerDrListVirtualServerDrNetworkPairingCmd          `cmd:"" name:"list-virtual-server-dr-network-pairing" help:"Get List Of Virtual Server DR Network Pairing"`
	ListVirtualServerDrPlan                    VirtualServerDrListVirtualServerDrPlanCmd                    `cmd:"" name:"list-virtual-server-dr-plan" help:"Get List Virtual Server DR Plan"`
	ListVirtualServerDrReplicationSnapshots    VirtualServerDrListVirtualServerDrReplicationSnapshotsCmd    `cmd:"" name:"list-virtual-server-dr-replication-snapshots" help:"Get List of Virtual Server Dr Replication Snapshots"`
	ListVirtualServerDrReplications            VirtualServerDrListVirtualServerDrReplicationsCmd            `cmd:"" name:"list-virtual-server-dr-replications" help:"Get List of Virtual Server DR Replication in Project"`
	RecoverCompleteVirtualServerDrPlan         VirtualServerDrRecoverCompleteVirtualServerDrPlanCmd         `cmd:"" name:"recover-complete-virtual-server-dr-plan" help:"Complete Recover Virtual Server DR Plan"`
	RecoverTestCleanUpVirtualServerDrPlan      VirtualServerDrRecoverTestCleanUpVirtualServerDrPlanCmd      `cmd:"" name:"recover-test-clean-up-virtual-server-dr-plan" help:"Cleanup Recover Test Virtual Server DR Plan"`
	RecoverTestVirtualServerDrPlan             VirtualServerDrRecoverTestVirtualServerDrPlanCmd             `cmd:"" name:"recover-test-virtual-server-dr-plan" help:"Recover Test Virtual Server DR Plan"`
	RecoverVirtualServerDrPlan                 VirtualServerDrRecoverVirtualServerDrPlanCmd                 `cmd:"" name:"recover-virtual-server-dr-plan" help:"Recover Virtual Server DR Plan"`
	RestoreVirtualServerDrReplicationSnapshot  VirtualServerDrRestoreVirtualServerDrReplicationSnapshotCmd  `cmd:"" name:"restore-virtual-server-dr-replication-snapshot" help:"Restore Virtual Server Dr Replication Snapshot"`
	SyncStartVirtualServerDrReplication        VirtualServerDrSyncStartVirtualServerDrReplicationCmd        `cmd:"" name:"sync-start-virtual-server-dr-replication" help:"Sync Start Virtual Server DR Replication"`
	SyncStopVirtualServerDrReplication         VirtualServerDrSyncStopVirtualServerDrReplicationCmd         `cmd:"" name:"sync-stop-virtual-server-dr-replication" help:"Sync Stop Virtual Server DR Replication"`
	UpdateDrGroupVirtualServerDrReplication    VirtualServerDrUpdateDrGroupVirtualServerDrReplicationCmd    `cmd:"" name:"update-dr-group-virtual-server-dr-replication" help:"Update DR Group Virtual Server DR Replication"`
	UpdatePriorityVirtualServerDrReplication   VirtualServerDrUpdatePriorityVirtualServerDrReplicationCmd   `cmd:"" name:"update-priority-virtual-server-dr-replication" help:"Update Priority Virtual Server DR Replication"`
	UpdateSnapshotVirtualServerDrReplication   VirtualServerDrUpdateSnapshotVirtualServerDrReplicationCmd   `cmd:"" name:"update-snapshot-virtual-server-dr-replication" help:"Update Snapshot Virtual Server DR Replication"`
	UpdateSyncPeriodVirtualServerDrReplication VirtualServerDrUpdateSyncPeriodVirtualServerDrReplicationCmd `cmd:"" name:"update-sync-period-virtual-server-dr-replication" help:"Update Sync Period Virtual Server DR Replication"`
	UpdateVirtualServerDrGroupDescription      VirtualServerDrUpdateVirtualServerDrGroupDescriptionCmd      `cmd:"" name:"update-virtual-server-dr-group-description" help:"Update Virtual Server DR Group's Description"`
	UpdateVirtualServerDrPlanDescription       VirtualServerDrUpdateVirtualServerDrPlanDescriptionCmd       `cmd:"" name:"update-virtual-server-dr-plan-description" help:"Update Virtual Server DR Plan Description"`
}
