// Code generated by codegen. DO NOT EDIT.

package commands

type VisionApiReportGetVisionApiAverageCmd struct {
	ApiName     string `name:"api-name" help:"API name"`
	EndDate     string `name:"end-date" help:"End date (YYYY-MM-DD)" required:""`
	Offset      string `name:"offset" help:"Offset ex) +00:00, -01:00, +05:00" required:""`
	PeriodUnit  string `name:"period-unit" help:"Search term(day/week/month)" required:""`
	ServiceName string `name:"service-name" help:"Service name"`
	StartDate   string `name:"start-date" help:"Start date (YYYY-MM-DD)" required:""`
}

func (c *VisionApiReportGetVisionApiAverageCmd) Run() error {
	return RunRequest("GET", "/vision-api/v1/report/average",
		map[string]string{},
		map[string]string{"apiName": c.ApiName, "endDate": c.EndDate, "offset": c.Offset, "periodUnit": c.PeriodUnit, "serviceName": c.ServiceName, "startDate": c.StartDate},
		nil)
}

type VisionApiReportGetVisionApiCategoriesCmd struct {
}

func (c *VisionApiReportGetVisionApiCategoriesCmd) Run() error {
	return RunRequest("GET", "/vision-api/v1/report/categories",
		map[string]string{},
		map[string]string{},
		nil)
}

type VisionApiReportGetVisionApiStatisticsCmd struct {
	ApiName     string `name:"api-name" help:"API name"`
	EndDate     string `name:"end-date" help:"End date (YYYY-MM-DD)" required:""`
	Offset      string `name:"offset" help:"Offset ex) +00:00, -01:00, +05:00" required:""`
	PeriodUnit  string `name:"period-unit" help:"Search term(day/week/month)" required:""`
	ServiceName string `name:"service-name" help:"Service name"`
	StartDate   string `name:"start-date" help:"Start date (YYYY-MM-DD)" required:""`
}

func (c *VisionApiReportGetVisionApiStatisticsCmd) Run() error {
	return RunRequest("GET", "/vision-api/v1/report/statistics",
		map[string]string{},
		map[string]string{"apiName": c.ApiName, "endDate": c.EndDate, "offset": c.Offset, "periodUnit": c.PeriodUnit, "serviceName": c.ServiceName, "startDate": c.StartDate},
		nil)
}

// VisionApiReportCmd groups all vision-api-report operations.
type VisionApiReportCmd struct {
	GetVisionApiAverage    VisionApiReportGetVisionApiAverageCmd    `cmd:"" name:"get-vision-api-average" help:"Get average data for the period"`
	GetVisionApiCategories VisionApiReportGetVisionApiCategoriesCmd `cmd:"" name:"get-vision-api-categories" help:"Get category data"`
	GetVisionApiStatistics VisionApiReportGetVisionApiStatisticsCmd `cmd:"" name:"get-vision-api-statistics" help:"Get statistics for each request"`
}
