// Code generated by codegen. DO NOT EDIT.

package commands

type VpcPeeringApproveVpcPeeringCmd struct {
	VpcPeeringId string `name:"vpc-peering-id" help:"VPC Peering ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VpcPeeringApproveVpcPeeringCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vpc-peering/v2/vpc-peerings/{vpcPeeringId}/approve",
		map[string]string{"vpcPeeringId": c.VpcPeeringId},
		map[string]string{},
		b)
}

type VpcPeeringCancelVpcPeeringCmd struct {
	VpcPeeringId string `name:"vpc-peering-id" help:"VPC Peering ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VpcPeeringCancelVpcPeeringCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vpc-peering/v2/vpc-peerings/{vpcPeeringId}/cancel",
		map[string]string{"vpcPeeringId": c.VpcPeeringId},
		map[string]string{},
		b)
}

type VpcPeeringCreateVpcPeering1Cmd struct {
	Body string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VpcPeeringCreateVpcPeering1Cmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vpc-peering/v3/vpc-peerings",
		map[string]string{},
		map[string]string{},
		b)
}

type VpcPeeringDeleteVpcPeeringCmd struct {
	VpcPeeringId string `name:"vpc-peering-id" help:"VPC Peering ID" required:""`
}

func (c *VpcPeeringDeleteVpcPeeringCmd) Run() error {
	return RunRequest("DELETE", "/vpc-peering/v2/vpc-peerings/{vpcPeeringId}",
		map[string]string{"vpcPeeringId": c.VpcPeeringId},
		map[string]string{},
		nil)
}

type VpcPeeringDetailVpcPeeringCmd struct {
	VpcPeeringId string `name:"vpc-peering-id" help:"VPC Peering ID" required:""`
}

func (c *VpcPeeringDetailVpcPeeringCmd) Run() error {
	return RunRequest("GET", "/vpc-peering/v2/vpc-peerings/{vpcPeeringId}",
		map[string]string{"vpcPeeringId": c.VpcPeeringId},
		map[string]string{},
		nil)
}

type VpcPeeringListVpcPeeringsCmd struct {
	ApproverVpcId    string `name:"approver-vpc-id" help:"Approver VPC ID vpcId is obtained through Get List of VPCs"`
	RequesterVpcId   string `name:"requester-vpc-id" help:"Requester VPC ID vpcId is obtained through Get List of VPCs"`
	VpcPeeringName   string `name:"vpc-peering-name" help:"VPC Peering Name"`
	VpcPeeringStates string `name:"vpc-peering-states" help:"VPC Peering States"`
	CreatedBy        string `name:"created-by" help:"Created By"`
	Page             string `name:"page" help:"Request page number"`
	Size             string `name:"size" help:"Number of items in the Page"`
	Sort             string `name:"sort" help:"Sort condition"`
}

func (c *VpcPeeringListVpcPeeringsCmd) Run() error {
	return RunRequest("GET", "/vpc-peering/v2/vpc-peerings",
		map[string]string{},
		map[string]string{"approverVpcId": c.ApproverVpcId, "requesterVpcId": c.RequesterVpcId, "vpcPeeringName": c.VpcPeeringName, "vpcPeeringStates": c.VpcPeeringStates, "createdBy": c.CreatedBy, "page": c.Page, "size": c.Size, "sort": c.Sort},
		nil)
}

type VpcPeeringRejectVpcPeeringCmd struct {
	VpcPeeringId string `name:"vpc-peering-id" help:"VPC Peering ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VpcPeeringRejectVpcPeeringCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("POST", "/vpc-peering/v2/vpc-peerings/{vpcPeeringId}/reject",
		map[string]string{"vpcPeeringId": c.VpcPeeringId},
		map[string]string{},
		b)
}

type VpcPeeringUpdateVpcPeeringDescriptionCmd struct {
	VpcPeeringId string `name:"vpc-peering-id" help:"VPC Peering ID" required:""`
	Body         string `name:"body" help:"request body as JSON string or @filename"`
}

func (c *VpcPeeringUpdateVpcPeeringDescriptionCmd) Run() error {
	b, err := resolveBody(c.Body)
	if err != nil {
		return err
	}
	return RunRequest("PUT", "/vpc-peering/v2/vpc-peerings/{vpcPeeringId}/description",
		map[string]string{"vpcPeeringId": c.VpcPeeringId},
		map[string]string{},
		b)
}

// VpcPeeringCmd groups all vpc-peering operations.
type VpcPeeringCmd struct {
	ApproveVpcPeering           VpcPeeringApproveVpcPeeringCmd           `cmd:"" name:"approve-vpc-peering" help:"Approve VPC Peering"`
	CancelVpcPeering            VpcPeeringCancelVpcPeeringCmd            `cmd:"" name:"cancel-vpc-peering" help:"Cancel VPC Peering"`
	CreateVpcPeering1           VpcPeeringCreateVpcPeering1Cmd           `cmd:"" name:"create-vpc-peering_1" help:"Create VPC Peering"`
	DeleteVpcPeering            VpcPeeringDeleteVpcPeeringCmd            `cmd:"" name:"delete-vpc-peering" help:"Delete VPC Peering"`
	DetailVpcPeering            VpcPeeringDetailVpcPeeringCmd            `cmd:"" name:"detail-vpc-peering" help:"Get VPC Peering Details"`
	ListVpcPeerings             VpcPeeringListVpcPeeringsCmd             `cmd:"" name:"list-vpc-peerings" help:"Get List of VPC Peerings"`
	RejectVpcPeering            VpcPeeringRejectVpcPeeringCmd            `cmd:"" name:"reject-vpc-peering" help:"Reject VPC Peering"`
	UpdateVpcPeeringDescription VpcPeeringUpdateVpcPeeringDescriptionCmd `cmd:"" name:"update-vpc-peering-description" help:"Modify VPC Peering Description"`
}
